# akdeniz_tarifleri.py
#
# Bolgesel genisleme -- III. Parti: AKDENİZ BÖLGESİ (24 tarif).
# yukle_yeni_tarifler.py ile (mevcutlari atlayarak) Supabase'e eklenir.
#
# Yeni malzeme gerekmedi -- NAR, NAR EKŞİSİ, SUMAK, TAHİN, HUMUS zaten
# katalogda mevcuttu.

BOLGE_ADI = "Akdeniz"

AKDENIZ_TARIFLERI = [
    # ---- I. Grup (ana yemek) -- 9 ----
    {"ad": "Adana Kebap", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["kirmizi_et", "izgara"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "SIĞIR KIYMA", "miktar_gram": 140},
        {"ad": "PUL BİBER", "miktar_gram": 3},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Akdeniz Usulü Karides Sote", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["balik"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "KARİDES", "miktar_gram": 150},
        {"ad": "SARIMSAK", "miktar_gram": 5},
        {"ad": "DOMATES", "miktar_gram": 50},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Muhammara Soslu Tavuk", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["beyaz_et"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 150},
        {"ad": "CEVİZ (İÇ)", "miktar_gram": 20},
        {"ad": "PUL BİBER", "miktar_gram": 3},
        {"ad": "KONSERVE DOMATES SALÇASI", "miktar_gram": 15},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
     ]},
    {"ad": "Akdeniz Usulü Fırın Levrek (Sumaklı)", "grup": 1, "mevsim_etiketi": "kis",
     "etiketler": ["balik"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "LEVREK", "miktar_gram": 180},
        {"ad": "SUMAK", "miktar_gram": 3},
        {"ad": "LİMON", "miktar_gram": 20},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Nar Ekşili Köfte", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "SIĞIR KIYMA", "miktar_gram": 130},
        {"ad": "NAR EKŞİSİ", "miktar_gram": 10},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Sumaklı Tavuk Şiş", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["beyaz_et", "izgara"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 150},
        {"ad": "SUMAK", "miktar_gram": 3},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "LİMON", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Etli Yeşil Mercimek Yemeği", "grup": 1, "mevsim_etiketi": "kis",
     "etiketler": ["kuru_baklagil"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "YEŞİL MERCİMEK", "miktar_gram": 60},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Karidesli Bulgur Pilavı", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["balik"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "KARİDES", "miktar_gram": 130},
        {"ad": "BULGUR", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Patlıcan Kebabı (Yoğurtlu)", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "SIĞIR KIYMA", "miktar_gram": 110},
        {"ad": "PATLICAN", "miktar_gram": 150},
        {"ad": "YOĞURT (TAM)", "miktar_gram": 60},
        {"ad": "SARIMSAK", "miktar_gram": 3},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # ---- II. Grup (yardımcı yemek) -- 7 ----
    {"ad": "Yeşil Mercimek Çorbası", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["corba", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "YEŞİL MERCİMEK", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Akdeniz Usulü Bulgur Pilavı (Domatesli)", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "BULGUR", "miktar_gram": 50},
        {"ad": "KONSERVE DOMATES SALÇASI", "miktar_gram": 15},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Nar Ekşili Zeytinyağlı Patlıcan", "grup": 2, "mevsim_etiketi": "yaz",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "PATLICAN", "miktar_gram": 200},
        {"ad": "NAR EKŞİSİ", "miktar_gram": 10},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Kabak (Akdeniz Usulü)", "grup": 2, "mevsim_etiketi": "yaz",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "KABAK", "miktar_gram": 200},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "DOMATES", "miktar_gram": 40},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Sumaklı Mercimek Köftesi", "grup": 2, "mevsim_etiketi": "sonbahar",
     "etiketler": ["kuru_baklagil", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "KIRMIZI MERCİMEK", "miktar_gram": 50},
        {"ad": "İNCE BULGUR", "miktar_gram": 40},
        {"ad": "SUMAK", "miktar_gram": 3},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
     ]},
    {"ad": "Hatay Usulü Katmer (Peynirli)", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "YUFKA", "miktar_gram": 80},
        {"ad": "LOR PEYNİRİ", "miktar_gram": 60},
        {"ad": "TEREYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},
    {"ad": "Akdeniz Usulü Bakla", "grup": 2, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "BAKLA", "miktar_gram": 200},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "TAZE DEREOTU", "miktar_gram": 5},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # ---- III. Grup (tamamlayıcılar) -- 8 ----
    {"ad": "Humus", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 15,
     "malzemeler": [
        {"ad": "NOHUT", "miktar_gram": 120},
        {"ad": "TAHİN", "miktar_gram": 20},
        {"ad": "LİMON SUYU", "miktar_gram": 10},
        {"ad": "SARIMSAK", "miktar_gram": 3},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
     ]},
    {"ad": "Muhammara", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 15,
     "malzemeler": [
        {"ad": "CEVİZ (İÇ)", "miktar_gram": 40},
        {"ad": "PUL BİBER", "miktar_gram": 5},
        {"ad": "KONSERVE DOMATES SALÇASI", "miktar_gram": 15},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "LİMON SUYU", "miktar_gram": 5},
     ]},
    {"ad": "Nar Ekşili Roka Salatası", "grup": 3, "mevsim_etiketi": "sonbahar",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "ROKA", "miktar_gram": 70},
        {"ad": "NAR", "miktar_gram": 50},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "NAR EKŞİSİ", "miktar_gram": 5},
     ]},
    {"ad": "Kısır", "grup": 3, "mevsim_etiketi": "yaz",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "İNCE BULGUR", "miktar_gram": 50},
        {"ad": "DOMATES", "miktar_gram": 40},
        {"ad": "MAYDONOZ", "miktar_gram": 10},
        {"ad": "NAR EKŞİSİ", "miktar_gram": 10},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
     ]},
    {"ad": "Nar Ekşili Yoğurt", "grup": 3, "mevsim_etiketi": "sonbahar",
     "etiketler": ["yogurt", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "YOĞURT (TAM)", "miktar_gram": 180},
        {"ad": "NAR", "miktar_gram": 40},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 5},
     ]},
    {"ad": "Künefe", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "KADAYIF", "miktar_gram": 70},
        {"ad": "KAŞAR PEYNİRİ", "miktar_gram": 60},
        {"ad": "TEREYAĞI", "miktar_gram": 20},
        {"ad": "ŞEKER", "miktar_gram": 30},
        {"ad": "SU", "miktar_gram": 40},
     ]},
    {"ad": "Nar Taneli Meyve Tabağı", "grup": 3, "mevsim_etiketi": "sonbahar",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "NAR", "miktar_gram": 80},
        {"ad": "ÜZÜM", "miktar_gram": 60},
        {"ad": "ELMA", "miktar_gram": 60},
     ]},
    {"ad": "Şam Tatlısı", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "İRMİK", "miktar_gram": 50},
        {"ad": "ŞEKER", "miktar_gram": 50},
        {"ad": "TEREYAĞI", "miktar_gram": 20},
        {"ad": "SU", "miktar_gram": 60},
     ]},
]
