# asamalar_dogu_anadolu.py
#
# Uretim asamalari -- Dogu Anadolu Bolgesi (24 tarif, 7. ve son bolge).
# asamalar_parti1.py'deki sema ve kurallarla birebir ayni; verimlilik
# oranlari kaynakli ticari ekipman sabitleriyle (bkz. asamalar_akdeniz.py
# basindaki not).

ASAMALAR = {

    "Cağ Kebabı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 20, "aktif_dakika": 20,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 200, "verimlilik_orani": 0.35,
         "malzemeler": ["KUZU TANDIR", "KURU SOĞAN"], "bagimli": ["Hazırlık"]},
    ],
    "Van Usulü Kahvaltı Tabağı (Otlu Peynirli)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 7, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Yumurta Pişirme", "sira": 2, "sure_dakika": 8, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["TAVUK YUMURTASI", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Kadayıf Dolması (Etli, Erzurum)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kıyma Sotesi", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.42, "malzemeler": ["SIĞIR KIYMA", "KURU SOĞAN"],
         "bagimli": ["Hazırlık"]},
        {"ad": "Sarma", "sira": 3, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Kıyma Sotesi"]},
        {"ad": "Fırınlama", "sira": 4, "sure_dakika": 20, "aktif_dakika": 5,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.58,
         "malzemeler": ["KADAYIF", "TEREYAĞI"], "bagimli": ["Sarma"]},
    ],
    "Erzincan Usulü Kavurmalı Yumurta": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 7, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["PASTIRMA", "TAVUK YUMURTASI", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Tulumlu Kuzu Tandır": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Ağır Ateş Pişirme", "sira": 2, "sure_dakika": 75, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 155, "verimlilik_orani": 0.58,
         "malzemeler": ["KUZU TANDIR", "KURU SOĞAN"], "bagimli": ["Hazırlık"]},
        {"ad": "Peynir Ekleme", "sira": 3, "sure_dakika": 2, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Ağır Ateş Pişirme"]},
    ],
    "Erzurum Usulü Etli Ekmek": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kıyma Sotesi", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.42, "malzemeler": ["SIĞIR KIYMA", "KURU SOĞAN"],
         "bagimli": ["Hazırlık"]},
        {"ad": "Fırınlama", "sira": 3, "sure_dakika": 15, "aktif_dakika": 5,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 200, "verimlilik_orani": 0.58,
         "malzemeler": ["BUĞDAY UNU"], "bagimli": ["Kıyma Sotesi"]},
    ],
    "Otlu Peynirli Gözleme": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 15, "aktif_dakika": 15,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.42,
         "malzemeler": ["YUFKA", "OTLU PEYNİR", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
    ],
    "Kavurma (Erzurum Usulü)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma", "sira": 2, "sure_dakika": 30, "aktif_dakika": 10,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 150, "verimlilik_orani": 0.42,
         "malzemeler": ["SIĞIR KIYMA"], "bagimli": ["Hazırlık"]},
    ],
    "Erzurum Usulü Etli Nohut": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 40, "aktif_dakika": 10,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "SIĞIR KIYMA", "NOHUT"], "bagimli": ["Hazırlık"]},
    ],

    "Ayran Aşı (Etli)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kıyma Sotesi", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.42, "malzemeler": ["SIĞIR KIYMA"],
         "bagimli": ["Hazırlık"]},  # Terbiye ile PARALEL
        {"ad": "Terbiye ve Kaynatma", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 90,
         "verimlilik_orani": 0.42, "malzemeler": ["YOĞURT (TAM)", "BUĞDAY UNU"],
         "bagimli": ["Hazırlık"]},
    ],
    "Doğu Anadolu Usulü Mercimek Çorbası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Kaynatma", "sira": 2, "sure_dakika": 25, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "KIRMIZI MERCİMEK", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
    ],
    "Tulumlu Bulgur Pilavı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Kaynatma", "sira": 2, "sure_dakika": 15, "aktif_dakika": 7,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["BULGUR", "TULUM PEYNİRİ", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Demlendirme", "sira": 3, "sure_dakika": 10, "aktif_dakika": 0,
         "isil_islem_mi": False, "malzemeler": [], "bagimli": ["Kavurma ve Kaynatma"]},
    ],
    "Erzurum Usulü Kavurmalı Kuru Fasulye": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 55, "aktif_dakika": 15,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "SIĞIR KIYMA", "KURU FASULYE"], "bagimli": ["Hazırlık"]},
    ],
    "Otlu Peynirli Börek": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Fırınlama", "sira": 2, "sure_dakika": 20, "aktif_dakika": 5,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.58,
         "malzemeler": ["YUFKA", "OTLU PEYNİR", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
    ],
    "Nohutlu Erişte": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 18, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["BUĞDAY UNU", "NOHUT", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Kaymaklı Bulgur Çorbası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kaynatma", "sira": 2, "sure_dakika": 20, "aktif_dakika": 6,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["BULGUR", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Kaymak Ekleme", "sira": 3, "sure_dakika": 2, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Kaynatma"]},
    ],

    "Bal Kaymak": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Erzurum Usulü Kayısı Tatlısı (Ballı)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Otlu Peynir Tabağı (Meze)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Yoğurtlu Semizotu Salatası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Ballı Ceviz Tabağı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Erzurum Usulü Kete": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Fırınlama", "sira": 2, "sure_dakika": 25, "aktif_dakika": 5,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.58,
         "malzemeler": ["BUĞDAY UNU", "ŞEKER", "TEREYAĞI", "TAVUK YUMURTASI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Doğu Anadolu Usulü Karışık Turşu": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Doğu Anadolu Usulü Kayısı Kompostosu": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kaynatma", "sira": 2, "sure_dakika": 18, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["KAYISI", "ŞEKER", "SU"],
         "bagimli": ["Hazırlık"]},
    ],

}
