# asamalar_parti2.py
#
# Uretim asamalari -- II. Parti: orijinal 75 "Klasik" kutuphanenin kalan
# 27 ana yemegi (talimatlar_parti1.py'deki detayli pisirme talimatlarindan
# yapisal veriye donusturuldu). Basitlik icin cogu tarif 2-3 asamaya
# indirgendi (Hazirlik + birlesik Isil Islem), surekli/ayni-kap
# sureclerinde ayri "kaynatma"/"agir pisirme" gibi alt-asamalar TEK bir
# isil islem asamasinda birlestirildi (Q=mcDeltaT hesabinda ikinci
# asamanin zaten hedef sicaklikta baslamasi -> delta_t=0 sorununu onlemek
# icin). aktif_dakika sadece sure_dakika'dan FARKLI oldugunda aciyla
# belirtiliyor -- belirtilmezse (cogu kisa/tek-kisilik islem) DB'de NULL
# kalir ve sure_dakika ile ayni sayilir.
#
# asama_yukle.py ile (recete_id/recete_malzeme_id'yi isme gore cozerek)
# Supabase'e islenir.

ASAMALAR = {
    "Dana Kuşbaşı Sote": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Mühürleme ve Pişirme", "sira": 2, "sure_dakika": 34, "aktif_dakika": 14,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20,
         "hedef_sicaklik": 150, "verimlilik_orani": 0.45,
         "malzemeler": ["DANA BİFTEK", "KURU SOĞAN", "YEŞİL BİBER", "DOMATES"], "bagimli": ["Hazırlık"]},
    ],
    "Izgara Dana Biftek": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 20, "aktif_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 9, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 240,
         "verimlilik_orani": 0.35, "malzemeler": ["DANA BİFTEK"], "bagimli": ["Hazırlık"]},
        {"ad": "Dinlendirme", "sira": 3, "sure_dakika": 5, "aktif_dakika": 1, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Izgara"]},
    ],
    "Sığır Kaburga Haşlama": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama", "sira": 2, "sure_dakika": 130, "aktif_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4, "malzemeler": ["SIĞIR KABURGA", "HAVUÇ", "PATATES", "KURU SOĞAN"],
         "bagimli": ["Hazırlık"]},
    ],
    "Kuzu Pirzola Izgara": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 20, "aktif_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 7, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 240,
         "verimlilik_orani": 0.35, "malzemeler": ["KUZU PİRZOLA"], "bagimli": ["Hazırlık"]},
        {"ad": "Dinlendirme", "sira": 3, "sure_dakika": 4, "aktif_dakika": 1, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Izgara"]},
    ],
    "Fırında Tavuk But": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Fırınlama", "sira": 2, "sure_dakika": 38, "aktif_dakika": 6, "isil_islem_mi": True,
         "enerji_kaynagi": "elektrik", "baslangic_sicaklik": 20, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.55, "malzemeler": ["TAVUK BUT"], "bagimli": ["Hazırlık"]},
        {"ad": "Dinlendirme", "sira": 3, "sure_dakika": 5, "aktif_dakika": 1, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Fırınlama"]},
    ],
    "Tavuk Şiş": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 35, "aktif_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 11, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 210,
         "verimlilik_orani": 0.4, "malzemeler": ["TAVUK GÖĞÜS"], "bagimli": ["Hazırlık"]},
    ],
    "Tavuk Sote": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 6, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 16, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.5, "malzemeler": ["TAVUK GÖĞÜS", "KURU SOĞAN", "SARI BİBER", "DOMATES"],
         "bagimli": ["Hazırlık"]},
    ],
    "Tavuk Suyu Haşlama": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama", "sira": 2, "sure_dakika": 53, "aktif_dakika": 13, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 95,
         "verimlilik_orani": 0.4, "malzemeler": ["TAVUK BÜTÜN", "HAVUÇ", "KEREVİZ"], "bagimli": ["Hazırlık"]},
    ],
    "Kremalı Mantarlı Tavuk": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 6, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Mühürleme", "sira": 2, "sure_dakika": 7, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.45, "malzemeler": ["TAVUK GÖĞÜS"], "bagimli": ["Hazırlık"]},
        {"ad": "Sos ve Birleştirme", "sira": 3, "sure_dakika": 13, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 130,
         "verimlilik_orani": 0.5, "malzemeler": ["MANTAR", "KREMA (SIVI)"], "bagimli": ["Mühürleme"]},
    ],
    "Izgara Tavuk Göğsü": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "aktif_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 11, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 190,
         "verimlilik_orani": 0.4, "malzemeler": ["TAVUK GÖĞÜS"], "bagimli": ["Hazırlık"]},
    ],
    "Fırında Levrek": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Fırınlama", "sira": 2, "sure_dakika": 22, "aktif_dakika": 4, "isil_islem_mi": True,
         "enerji_kaynagi": "elektrik", "baslangic_sicaklik": 20, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.5, "malzemeler": ["LEVREK"], "bagimli": ["Hazırlık"]},
    ],
    "Izgara Çipura": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 6, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 14, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 190,
         "verimlilik_orani": 0.4, "malzemeler": ["ÇİPURA"], "bagimli": ["Hazırlık"]},
    ],
    "Hamsi Tava": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kızartma", "sira": 2, "sure_dakika": 5, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 178,
         "verimlilik_orani": 0.35, "malzemeler": ["HAMSİ"], "bagimli": ["Hazırlık"]},
    ],
    "Somon Izgara": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "aktif_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 8, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.4, "malzemeler": ["SOMON"], "bagimli": ["Hazırlık"]},
    ],
    "Karides Güveç": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Sos Tabanı", "sira": 2, "sure_dakika": 7, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.5, "malzemeler": ["KURU SOĞAN", "DOMATES"], "bagimli": ["Hazırlık"]},
        {"ad": "Karides ve Fırınlama", "sira": 3, "sure_dakika": 9, "isil_islem_mi": True,
         "enerji_kaynagi": "elektrik", "baslangic_sicaklik": 20, "hedef_sicaklik": 210,
         "verimlilik_orani": 0.5, "malzemeler": ["KARİDES"], "bagimli": ["Sos Tabanı"]},
    ],
    "Kalamar Tava": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kızartma", "sira": 2, "sure_dakika": 2, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 185,
         "verimlilik_orani": 0.3, "malzemeler": ["KALAMAR"], "bagimli": ["Hazırlık"]},
    ],
    "Etli Biber Dolması": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 12, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Doldurma", "sira": 2, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Hazırlık"]},
        {"ad": "Pişirme", "sira": 3, "sure_dakika": 42, "aktif_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4,
         "malzemeler": ["YEŞİL BİBER", "SIĞIR KIYMA", "PİRİNÇ (HAM)", "KURU SOĞAN", "DOMATES"],
         "bagimli": ["Doldurma"]},
    ],
    "Etli Kabak Dolması": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 12, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Doldurma", "sira": 2, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Hazırlık"]},
        {"ad": "Pişirme", "sira": 3, "sure_dakika": 37, "aktif_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4,
         "malzemeler": ["KABAK", "SIĞIR KIYMA", "PİRİNÇ (HAM)", "KURU SOĞAN"], "bagimli": ["Doldurma"]},
    ],
    "Etli Yaprak Sarma": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Sarma", "sira": 2, "sure_dakika": 22, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Hazırlık"]},
        {"ad": "Pişirme", "sira": 3, "sure_dakika": 42, "aktif_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4,
         "malzemeler": ["SALAMURA YAPRAK", "SIĞIR KIYMA", "PİRİNÇ (HAM)", "KURU SOĞAN"], "bagimli": ["Sarma"]},
    ],
    "Patlıcan Musakka": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 20, "aktif_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Patlıcan Kızartma", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 175,
         "verimlilik_orani": 0.4, "malzemeler": ["PATLICAN"], "bagimli": ["Hazırlık"]},
        {"ad": "Kıyma Harcı", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.5, "malzemeler": ["SIĞIR KIYMA", "KURU SOĞAN", "KONSERVE DOMATES"],
         "bagimli": ["Hazırlık"]},
        {"ad": "Montaj ve Fırınlama", "sira": 3, "sure_dakika": 22, "aktif_dakika": 4, "isil_islem_mi": True,
         "enerji_kaynagi": "elektrik", "baslangic_sicaklik": 20, "hedef_sicaklik": 180,
         "verimlilik_orani": 0.6, "malzemeler": ["PATLICAN", "SIĞIR KIYMA"],
         "bagimli": ["Patlıcan Kızartma", "Kıyma Harcı"]},
    ],
    "Etli Kuru Fasulye": [
        {"ad": "Kavurma", "sira": 1, "sure_dakika": 5, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.5, "malzemeler": ["SIĞIR KIYMA", "KURU SOĞAN"], "bagimli": []},
        {"ad": "Ana Pişirme", "sira": 2, "sure_dakika": 75, "aktif_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4, "malzemeler": ["KURU FASULYE", "KONSERVE DOMATES SALÇASI"],
         "bagimli": ["Kavurma"]},
    ],
    "Etli Nohut Yemeği": [
        {"ad": "Kavurma", "sira": 1, "sure_dakika": 5, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.5, "malzemeler": ["SIĞIR KIYMA", "KURU SOĞAN"], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 32, "aktif_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4, "malzemeler": ["NOHUT", "KONSERVE DOMATES"], "bagimli": ["Kavurma"]},
    ],
    "Mercimek Köftesi": [
        {"ad": "Haşlama", "sira": 1, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4, "malzemeler": ["KIRMIZI MERCİMEK"], "bagimli": []},
        {"ad": "Demlenme ve Soğuma", "sira": 2, "sure_dakika": 20, "aktif_dakika": 2, "isil_islem_mi": False,
         "malzemeler": ["İNCE BULGUR"], "bagimli": ["Haşlama"]},
        {"ad": "Şekillendirme", "sira": 3, "sure_dakika": 11, "isil_islem_mi": False,
         "malzemeler": ["MAYDONOZ"], "bagimli": ["Demlenme ve Soğuma"]},
    ],
    "Zeytinyağlı Barbunya Pilaki": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 30, "aktif_dakika": 12, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4, "malzemeler": ["BARBUNYA", "HAVUÇ", "KURU SOĞAN"], "bagimli": ["Hazırlık"]},
    ],
    "Zeytinyağlı Nohut Yemeği": [
        {"ad": "Pişirme", "sira": 1, "sure_dakika": 22, "aktif_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4, "malzemeler": ["NOHUT", "HAVUÇ", "KURU SOĞAN"], "bagimli": []},
    ],
    "Sahanda Yumurta (Sucuklu)": [
        {"ad": "Sucuk Kavurma", "sira": 1, "sure_dakika": 5, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 160,
         "verimlilik_orani": 0.4, "malzemeler": ["SUCUK"], "bagimli": []},
        {"ad": "Yumurta", "sira": 2, "sure_dakika": 5, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.4, "malzemeler": ["TAVUK YUMURTASI"], "bagimli": ["Sucuk Kavurma"]},
    ],
    "Dana Rosto": [
        {"ad": "Mühürleme", "sira": 1, "sure_dakika": 7, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.4, "malzemeler": ["DANA ROSTO"], "bagimli": []},
        {"ad": "Kavurma", "sira": 2, "sure_dakika": 4, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.5, "malzemeler": ["KURU SOĞAN", "HAVUÇ"], "bagimli": ["Mühürleme"]},
        {"ad": "Ağır Pişirme", "sira": 3, "sure_dakika": 75, "aktif_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.45, "malzemeler": ["DANA ROSTO"], "bagimli": ["Kavurma"]},
    ],
}
