# asamalar_marmara.py
#
# Uretim asamalari -- Marmara Bolgesi (24 tarif). asamalar_parti1.py'deki
# sema ve kurallarla birebir ayni (bkz. asamalar_parti3.py basindaki not).

ASAMALAR = {

    "İskender Kebap": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Et Izgara", "sira": 2, "sure_dakika": 9, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.5, "malzemeler": ["DANA BİFTEK"], "bagimli": ["Hazırlık"]},
        {"ad": "Salça Sosu", "sira": 2, "sure_dakika": 3, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 110,
         "verimlilik_orani": 0.5, "malzemeler": ["KONSERVE DOMATES SALÇASI", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},  # Et Izgara İLE PARALEL
    ],
    "Hünkar Beğendi": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Patlıcan Közleme", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 220,
         "verimlilik_orani": 0.4, "malzemeler": ["PATLICAN"], "bagimli": ["Hazırlık"]},
        {"ad": "Kıyma Yahnisi", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.5, "malzemeler": ["SIĞIR KIYMA"],
         "bagimli": ["Hazırlık"]},  # Patlıcan Közleme İLE PARALEL
        {"ad": "Beğendi Yapma", "sira": 3, "sure_dakika": 8, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 90,
         "verimlilik_orani": 0.5, "malzemeler": ["SÜT (TAM YAĞ)", "KAŞAR PEYNİRİ", "BUĞDAY UNU"],
         "bagimli": ["Patlıcan Közleme"]},
    ],
    "Midye Tava": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kızartma", "sira": 2, "sure_dakika": 7, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 180,
         "verimlilik_orani": 0.45, "malzemeler": ["MİDYE", "BUĞDAY UNU", "AYÇİÇEK YAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Kestaneli Tavuk": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 35, "aktif_dakika": 10,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 150, "verimlilik_orani": 0.5,
         "malzemeler": ["TAVUK BUT", "KESTANE", "KURU SOĞAN", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Kağıtta Somon (Marmara Usulü)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 7, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Fırınlama", "sira": 2, "sure_dakika": 19, "aktif_dakika": 2,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 200, "verimlilik_orani": 0.6,
         "malzemeler": ["SOMON"], "bagimli": ["Hazırlık"]},
    ],
    "Bursa Usulü İnegöl Köfte": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.5, "malzemeler": ["SIĞIR KIYMA"], "bagimli": ["Hazırlık"]},
    ],
    "Kaymaklı Mantı (Marmara Usulü)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 45, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama", "sira": 2, "sure_dakika": 17, "aktif_dakika": 5,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.5,
         "malzemeler": ["BUĞDAY UNU", "SIĞIR KIYMA"], "bagimli": ["Hazırlık"]},
    ],
    "Bursa Usulü Kestaneli Kuzu": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Ağır Ateş Pişirme", "sira": 2, "sure_dakika": 75, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 155, "verimlilik_orani": 0.55,
         "malzemeler": ["KUZU TANDIR", "KESTANE"], "bagimli": ["Hazırlık"]},
    ],
    "İstanbul Usulü Karides Güveç (Kaşarlı)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 7, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Sote", "sira": 2, "sure_dakika": 12, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 110,
         "verimlilik_orani": 0.5, "malzemeler": ["KARİDES", "KONSERVE DOMATES", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},
        {"ad": "Fırınlama", "sira": 3, "sure_dakika": 8, "isil_islem_mi": True,
         "enerji_kaynagi": "elektrik", "baslangic_sicaklik": 110, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.55, "malzemeler": ["KAŞAR PEYNİRİ"], "bagimli": ["Sote"]},
    ],

    "Kestaneli Pilav": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Kaynatma", "sira": 2, "sure_dakika": 20, "aktif_dakika": 7,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.55,
         "malzemeler": ["PİRİNÇ (HAM)", "KESTANE", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Demlendirme", "sira": 3, "sure_dakika": 10, "aktif_dakika": 0,
         "isil_islem_mi": False, "malzemeler": [], "bagimli": ["Kavurma ve Kaynatma"]},
    ],
    "Zeytinyağlı Midye Pilaki": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 30, "aktif_dakika": 10,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 95, "verimlilik_orani": 0.5,
         "malzemeler": ["MİDYE", "PİRİNÇ (HAM)", "KURU SOĞAN", "ZEYTİNYAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Bursa Usulü Kıymalı Katmer": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kıyma Sotesi", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.5, "malzemeler": ["SIĞIR KIYMA", "KURU SOĞAN"],
         "bagimli": ["Hazırlık"]},
        {"ad": "Katmer Pişirme", "sira": 3, "sure_dakika": 12, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 150, "hedef_sicaklik": 180,
         "verimlilik_orani": 0.5, "malzemeler": ["YUFKA", "TEREYAĞI"],
         "bagimli": ["Kıyma Sotesi"]},
    ],
    "Kestaneli Bulgur Pilavı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Kaynatma", "sira": 2, "sure_dakika": 19, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.55,
         "malzemeler": ["BULGUR", "KESTANE", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Demlendirme", "sira": 3, "sure_dakika": 10, "aktif_dakika": 0,
         "isil_islem_mi": False, "malzemeler": [], "bagimli": ["Kavurma ve Kaynatma"]},
    ],
    "Marmara Usulü Zeytinyağlı Pırasa": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 30, "aktif_dakika": 10,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 95, "verimlilik_orani": 0.5,
         "malzemeler": ["PIRASA", "HAVUÇ", "ZEYTİNYAĞI"], "bagimli": ["Hazırlık"]},
    ],
    "Bursa Usulü Zeytinyağlı Nohut": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 25, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 95, "verimlilik_orani": 0.5,
         "malzemeler": ["NOHUT", "ZEYTİNYAĞI", "KURU SOĞAN"], "bagimli": ["Hazırlık"]},
    ],
    "Kestaneli Çorba": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kaynatma", "sira": 2, "sure_dakika": 20, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.5,
         "malzemeler": ["KESTANE", "TAVUK SUYU", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
    ],

    "Kestane Şekeri": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama", "sira": 2, "sure_dakika": 20, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.5, "malzemeler": ["KESTANE"], "bagimli": ["Hazırlık"]},
        {"ad": "Şerbetleme", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 105,
         "verimlilik_orani": 0.5, "malzemeler": ["ŞEKER", "SU"],
         "bagimli": ["Hazırlık"]},  # Haşlama İLE PARALEL
    ],
    "Kaymaklı Ekmek Kadayıfı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Şerbetleme", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.5, "malzemeler": ["ŞEKER", "SU"], "bagimli": ["Hazırlık"]},
        {"ad": "Emdirme", "sira": 3, "sure_dakika": 15, "aktif_dakika": 0,
         "isil_islem_mi": False, "malzemeler": [], "bagimli": ["Şerbetleme"]},
    ],
    "Vişne Reçelli Yoğurt": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Marmara Usulü Yeşil Salata": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Nar Ekşili Pancar Salatası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.5, "malzemeler": ["PANCAR"], "bagimli": ["Hazırlık"]},
    ],
    "Kestaneli Muhallebi": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 90,
         "verimlilik_orani": 0.5,
         "malzemeler": ["KESTANE", "SÜT (TAM YAĞ)", "MISIR NİŞASTASI", "ŞEKER"],
         "bagimli": ["Hazırlık"]},
    ],
    "Marmara Usulü Karışık Turşu": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Marmara Usulü Vişne Kompostosu": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kaynatma", "sira": 2, "sure_dakika": 18, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.5, "malzemeler": ["VİŞNE", "ŞEKER", "SU"],
         "bagimli": ["Hazırlık"]},
    ],

}
