# asamalar_guneydogu.py
#
# Uretim asamalari -- Guneydogu Anadolu Bolgesi (24 tarif).
# asamalar_parti1.py'deki sema ve kurallarla birebir ayni; verimlilik
# oranlari kaynakli ticari ekipman sabitleriyle (bkz. asamalar_akdeniz.py
# basindaki not).

ASAMALAR = {

    "Çiğ Köfte (Vejetaryen)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 40, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Kuzu Şiş (Isotlu)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 12, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.35, "malzemeler": ["KUZU ŞİŞ"], "bagimli": ["Hazırlık"]},
    ],
    "Alinazik Kebap": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Patlıcan Közleme", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 220,
         "verimlilik_orani": 0.42, "malzemeler": ["PATLICAN"], "bagimli": ["Hazırlık"]},
        {"ad": "Kıyma Sotesi", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.42, "malzemeler": ["SIĞIR KIYMA"],
         "bagimli": ["Hazırlık"]},  # Patlıcan Közleme İLE PARALEL
        {"ad": "Beğendi ve Birleştirme", "sira": 3, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Patlıcan Közleme", "Kıyma Sotesi"]},
    ],
    "İçli Köfte": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "İç Harç Kavurma", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.42, "malzemeler": ["KURU SOĞAN", "SIĞIR KIYMA", "CEVİZ (İÇ)"],
         "bagimli": ["Hazırlık"]},
        {"ad": "Doldurma ve Şekillendirme", "sira": 3, "sure_dakika": 20, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["İç Harç Kavurma"]},
        {"ad": "Haşlama", "sira": 4, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["İNCE BULGUR"],
         "bagimli": ["Doldurma ve Şekillendirme"]},
    ],
    "Küşleme (Kuzu Kavurma)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma", "sira": 2, "sure_dakika": 35, "aktif_dakika": 15,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 150, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "KUZU TANDIR", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
    ],
    "Antep Fıstıklı Tavuk Sote": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 6, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Sote", "sira": 2, "sure_dakika": 20, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 150, "verimlilik_orani": 0.42,
         "malzemeler": ["TAVUK GÖĞÜS", "ANTEP FISTIĞI", "KURU SOĞAN", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Isotlu Tavuk Şiş": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Izgara", "sira": 2, "sure_dakika": 12, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 200,
         "verimlilik_orani": 0.35, "malzemeler": ["TAVUK GÖĞÜS"], "bagimli": ["Hazırlık"]},
    ],
    "Nohutlu Kuzu Yahnisi": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 45, "aktif_dakika": 12,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "KUZU TANDIR", "NOHUT"], "bagimli": ["Hazırlık"]},
    ],
    "Antep Usulü Mercimekli Köfte": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Mercimek Haşlama", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["KIRMIZI MERCİMEK"], "bagimli": ["Hazırlık"]},
        {"ad": "Yoğurma ve Şekillendirme", "sira": 3, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Mercimek Haşlama"]},
    ],

    "Yoğurtlu Mercimek Çorbası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kaynatma", "sira": 2, "sure_dakika": 20, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["KIRMIZI MERCİMEK", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},
        {"ad": "Terbiye", "sira": 3, "sure_dakika": 8, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 85,
         "verimlilik_orani": 0.42, "malzemeler": ["YOĞURT (TAM)"], "bagimli": ["Kaynatma"]},
    ],
    "Antep Usulü Bulgur Pilavı (İsotlu)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Kaynatma", "sira": 2, "sure_dakika": 15, "aktif_dakika": 7,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "BULGUR", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Demlendirme", "sira": 3, "sure_dakika": 10, "aktif_dakika": 0,
         "isil_islem_mi": False, "malzemeler": [], "bagimli": ["Kavurma ve Kaynatma"]},
    ],
    "Antep Usulü Nohutlu Bulgur": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Kaynatma", "sira": 2, "sure_dakika": 17, "aktif_dakika": 7,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "NOHUT", "BULGUR", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Demlendirme", "sira": 3, "sure_dakika": 10, "aktif_dakika": 0,
         "isil_islem_mi": False, "malzemeler": [], "bagimli": ["Kavurma ve Kaynatma"]},
    ],
    "Güneydoğu Usulü Ispanaklı Börek": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Ispanak Kavurma", "sira": 2, "sure_dakika": 7, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 110,
         "verimlilik_orani": 0.42, "malzemeler": ["ISPANAK"], "bagimli": ["Hazırlık"]},
        {"ad": "Harç Birleştirme", "sira": 3, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Ispanak Kavurma"]},
        {"ad": "Fırınlama", "sira": 4, "sure_dakika": 25, "aktif_dakika": 10,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.58,
         "malzemeler": ["YUFKA", "LOR PEYNİRİ", "TEREYAĞI"], "bagimli": ["Harç Birleştirme"]},
    ],
    "Zeytinyağlı Nane Soslu Kabak": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kabak Haşlama", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["KABAK"], "bagimli": ["Hazırlık"]},
        {"ad": "Terbiye", "sira": 3, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Kabak Haşlama"]},
    ],
    "Antep Usulü Katmer (Kahvaltılık)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 15, "aktif_dakika": 15,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.42,
         "malzemeler": ["YUFKA", "KAŞAR PEYNİRİ", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
    ],
    "Antep Usulü Zeytinyağlı Nohut": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 25, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 95, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "NOHUT", "ZEYTİNYAĞI", "LİMON SUYU"],
         "bagimli": ["Hazırlık"]},
    ],

    "Sumaklı Soğan Salatası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Antep Usulü Baklava": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 20, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Fırınlama", "sira": 2, "sure_dakika": 25, "aktif_dakika": 5,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.58,
         "malzemeler": ["YUFKA", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Şerbet", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 105,
         "verimlilik_orani": 0.42, "malzemeler": ["ŞEKER", "SU"],
         "bagimli": ["Hazırlık"]},  # Fırınlama İLE PARALEL
        {"ad": "Şerbetleme", "sira": 3, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Fırınlama", "Şerbet"]},
    ],
    "Fıstıklı Katmer (Tatlı, Kaymaklı)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 15, "aktif_dakika": 15,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.42,
         "malzemeler": ["YUFKA", "TEREYAĞI", "ŞEKER"], "bagimli": ["Hazırlık"]},
    ],
    "Antep Fıstıklı Künefe": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 15, "aktif_dakika": 15,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.42,
         "malzemeler": ["KADAYIF", "KAŞAR PEYNİRİ", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Şerbet", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 105,
         "verimlilik_orani": 0.42, "malzemeler": ["ŞEKER"],
         "bagimli": ["Hazırlık"]},  # Pişirme İLE PARALEL
    ],
    "Kayısı Tatlısı (Cevizli)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 20, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Sumaklı Cacık": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Sumaklı Kırmızı Lahana Salatası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Yoğurtlu Bulgur Salatası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 20, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],

}
