# asamalar_ic_anadolu.py
#
# Uretim asamalari -- Ic Anadolu Bolgesi (24 tarif). asamalar_parti1.py'deki
# sema ve kurallarla birebir ayni; verimlilik oranlari kaynakli ticari
# ekipman sabitleriyle (bkz. asamalar_akdeniz.py basindaki not).

ASAMALAR = {

    "Keşkek": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama ve Dövme", "sira": 2, "sure_dakika": 100, "aktif_dakika": 20,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["BUĞDAY (TAM TANE)", "TAVUK BUT"], "bagimli": ["Hazırlık"]},
        {"ad": "Tereyağı Ekleme", "sira": 3, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": ["Haşlama ve Dövme"]},
    ],
    "Etli Ekmek (Konya)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kıyma Sotesi", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 150,
         "verimlilik_orani": 0.42, "malzemeler": ["SIĞIR KIYMA", "KURU SOĞAN", "DOMATES"],
         "bagimli": ["Hazırlık"]},
        {"ad": "Fırınlama", "sira": 3, "sure_dakika": 15, "aktif_dakika": 5,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 200, "verimlilik_orani": 0.58,
         "malzemeler": ["BUĞDAY UNU"], "bagimli": ["Kıyma Sotesi"]},
    ],
    "Testi Kebabı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Ağır Ateş Pişirme", "sira": 2, "sure_dakika": 70, "aktif_dakika": 5,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 155, "verimlilik_orani": 0.58,
         "malzemeler": ["KUZU TANDIR", "DOMATES", "YEŞİL BİBER", "KURU SOĞAN"],
         "bagimli": ["Hazırlık"]},
    ],
    "Kayseri Mantısı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 40, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["BUĞDAY UNU", "SIĞIR KIYMA"],
         "bagimli": ["Hazırlık"]},
    ],
    "Pastırmalı Yumurta": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 7, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["PASTIRMA", "TAVUK YUMURTASI", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Bamya Yemeği (Etli)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 35, "aktif_dakika": 15,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "SIĞIR KIYMA", "BAMYA", "KONSERVE DOMATES"],
         "bagimli": ["Hazırlık"]},
    ],
    "Kavurmalı Nohut": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Isıtma ve Pişirme", "sira": 2, "sure_dakika": 25, "aktif_dakika": 10,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 110, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "KAVURMA", "NOHUT"], "bagimli": ["Hazırlık"]},
    ],
    "Sucuklu Kuru Fasulye": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 55, "aktif_dakika": 15,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "SUCUK", "KURU FASULYE", "KONSERVE DOMATES SALÇASI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Kayısılı Kuzu Tandır": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Ağır Ateş Pişirme", "sira": 2, "sure_dakika": 85, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "elektrik",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 155, "verimlilik_orani": 0.58,
         "malzemeler": ["KUZU TANDIR", "KAYISI", "KURU SOĞAN"], "bagimli": ["Hazırlık"]},
    ],

    "Tarhana Çorbası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kaynatma", "sira": 2, "sure_dakika": 18, "aktif_dakika": 10,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["TARHANA", "SU", "TEREYAĞI", "KONSERVE DOMATES SALÇASI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Arpa Şehriyeli Çorba": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kaynatma", "sira": 2, "sure_dakika": 20, "aktif_dakika": 8,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["TAVUK SUYU", "HAVUÇ", "ŞEHRİYE"], "bagimli": ["Hazırlık"]},
    ],
    "Bamya Yemeği (Zeytinyağlı)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Pişirme", "sira": 2, "sure_dakika": 25, "aktif_dakika": 10,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 95, "verimlilik_orani": 0.42,
         "malzemeler": ["KURU SOĞAN", "BAMYA", "KONSERVE DOMATES", "ZEYTİNYAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Şehriyeli Bulgur Pilavı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma ve Kaynatma", "sira": 2, "sure_dakika": 15, "aktif_dakika": 7,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 100, "verimlilik_orani": 0.42,
         "malzemeler": ["ŞEHRİYE", "BULGUR", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Demlendirme", "sira": 3, "sure_dakika": 10, "aktif_dakika": 0,
         "isil_islem_mi": False, "malzemeler": [], "bagimli": ["Kavurma ve Kaynatma"]},
    ],
    "Mantı Çorbası (Yoğurtlu)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 15, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["BUĞDAY UNU"], "bagimli": ["Hazırlık"]},
        {"ad": "Terbiye", "sira": 3, "sure_dakika": 8, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 85,
         "verimlilik_orani": 0.42, "malzemeler": ["YOĞURT (TAM)", "TEREYAĞI"],
         "bagimli": ["Haşlama"]},
    ],
    "Erişte (Ev Yapımı Makarna)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 20, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Haşlama", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["BUĞDAY UNU", "TEREYAĞI"],
         "bagimli": ["Hazırlık"]},
    ],
    "Sac Böreği (Peynirli)": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 10, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 15, "aktif_dakika": 15,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 180, "verimlilik_orani": 0.42,
         "malzemeler": ["YUFKA", "KAŞAR PEYNİRİ", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
    ],

    "Höşmerim": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Pişirme", "sira": 2, "sure_dakika": 20, "aktif_dakika": 20,
         "isil_islem_mi": True, "enerji_kaynagi": "dogalgaz",
         "baslangic_sicaklik": 20, "hedef_sicaklik": 150, "verimlilik_orani": 0.42,
         "malzemeler": ["İRMİK", "LOR PEYNİRİ", "ŞEKER", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
    ],
    "Malatya Usulü Kayısı Tatlısı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 20, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Kuru Kayısı Kompostosu": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kaynatma", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["KURU KAYISI", "ŞEKER", "SU"],
         "bagimli": ["Hazırlık"]},
    ],
    "Kuru Fasulye Piyazı": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 12, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Konya Usulü Kavun Dilimi": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Kuru Üzümlü İrmik Helvası": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 3, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
        {"ad": "Kavurma", "sira": 2, "sure_dakika": 10, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 110,
         "verimlilik_orani": 0.42, "malzemeler": ["İRMİK", "TEREYAĞI"], "bagimli": ["Hazırlık"]},
        {"ad": "Şerbet", "sira": 2, "sure_dakika": 15, "isil_islem_mi": True,
         "enerji_kaynagi": "dogalgaz", "baslangic_sicaklik": 20, "hedef_sicaklik": 100,
         "verimlilik_orani": 0.42, "malzemeler": ["ŞEKER", "SU", "KURU ÜZÜM"],
         "bagimli": ["Hazırlık"]},  # Kavurma İLE PARALEL
        {"ad": "Şerbetleme", "sira": 3, "sure_dakika": 10, "aktif_dakika": 0,
         "isil_islem_mi": False, "malzemeler": [], "bagimli": ["Kavurma", "Şerbet"]},
    ],
    "Ev Yapımı Karışık Turşu": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 5, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],
    "Kuru Üzümlü Yoğurt": [
        {"ad": "Hazırlık", "sira": 1, "sure_dakika": 8, "isil_islem_mi": False,
         "malzemeler": [], "bagimli": []},
    ],

}
