# ege_tarifleri.py
#
# Bolgesel genisleme -- II. Parti: EGE BÖLGESİ (26 tarif).
# yukle_yeni_tarifler.py ile (mevcutlari atlayarak) Supabase'e eklenir.
#
# Yeni malzemeler (18_ege_malzemeleri_ekle.sql ile eklendi):
# BAKLA, PAZI, RADİKA, BADEM.

BOLGE_ADI = "Ege"

EGE_TARIFLERI = [
    # ---- I. Grup (ana yemek) -- 10 ----
    {"ad": "Zeytinyağlı Bakla", "grup": 1, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "BAKLA", "miktar_gram": 200},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "TAZE DEREOTU", "miktar_gram": 5},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Ahtapot Izgara", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["balik", "izgara"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "AHTAPOT", "miktar_gram": 180},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "LİMON", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Pazı Kavurma (Etli)", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["etli_sebze"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "PAZI", "miktar_gram": 200},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 70},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Fırında Çipura (Sebzeli)", "grup": 1, "mevsim_etiketi": "kis",
     "etiketler": ["balik"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "ÇİPURA", "miktar_gram": 180},
        {"ad": "DOMATES", "miktar_gram": 40},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "LİMON", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "İzmir Köfte", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "SIĞIR KIYMA", "miktar_gram": 120},
        {"ad": "PATATES", "miktar_gram": 60},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "KONSERVE DOMATES", "miktar_gram": 40},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Etli Enginar Dolması", "grup": 1, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["etli_sebze", "dolma", "etli_zeytinyagli_dolma"], "hazirlik_dakika": 55,
     "malzemeler": [
        {"ad": "ENGİNAR KALBİ", "miktar_gram": 150},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 70},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 25},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Midyeli Pilav", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["balik"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "MİDYE", "miktar_gram": 150},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
     ]},
    {"ad": "Domates Dolması (Zeytinyağlı)", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["zeytinyagli", "dolma", "etli_zeytinyagli_dolma", "vejetaryen"], "hazirlik_dakika": 50,
     "malzemeler": [
        {"ad": "DOMATES", "miktar_gram": 220},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 30},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Ege Usulü Fırın Tavuk (Zeytinli)", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["beyaz_et"], "hazirlik_dakika": 50,
     "malzemeler": [
        {"ad": "TAVUK BUT", "miktar_gram": 180},
        {"ad": "SİYAH ZEYTİN", "miktar_gram": 30},
        {"ad": "DOMATES", "miktar_gram": 40},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Bademli Tavuk Sote", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["beyaz_et"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 150},
        {"ad": "BADEM", "miktar_gram": 20},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # ---- II. Grup (yardımcı yemek) -- 8 ----
    {"ad": "Pazı Çorbası", "grup": 2, "mevsim_etiketi": "sonbahar",
     "etiketler": ["corba", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "PAZI", "miktar_gram": 120},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 20},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Ege Otlu Bulgur Pilavı", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "BULGUR", "miktar_gram": 50},
        {"ad": "TAZE FESLEĞEN", "miktar_gram": 5},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Enginar Kalbi", "grup": 2, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "ENGİNAR KALBİ", "miktar_gram": 150},
        {"ad": "HAVUÇ", "miktar_gram": 30},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "LİMON SUYU", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Radika", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "RADİKA", "miktar_gram": 150},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "LİMON SUYU", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Bademli Pilav", "grup": 2, "mevsim_etiketi": "sonbahar",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 50},
        {"ad": "BADEM", "miktar_gram": 15},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Ispanaklı Makarna (Ege Usulü)", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "MAKARNA", "miktar_gram": 50},
        {"ad": "ISPANAK", "miktar_gram": 80},
        {"ad": "SARIMSAK", "miktar_gram": 3},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Yer Elması", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "YER ELMASI", "miktar_gram": 180},
        {"ad": "HAVUÇ", "miktar_gram": 30},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "LİMON SUYU", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Ege Peynirli Gözleme", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "YUFKA", "miktar_gram": 80},
        {"ad": "LOR PEYNİRİ", "miktar_gram": 60},
        {"ad": "MAYDONOZ", "miktar_gram": 5},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},

    # ---- III. Grup (tamamlayıcılar) -- 8 ----
    {"ad": "Radika Salatası (Haşlanmış)", "grup": 3, "mevsim_etiketi": "kis",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 15,
     "malzemeler": [
        {"ad": "RADİKA", "miktar_gram": 100},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "LİMON SUYU", "miktar_gram": 5},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},
    {"ad": "Midye Dolma", "grup": 3, "mevsim_etiketi": "sonbahar",
     "etiketler": [], "hazirlik_dakika": 60,
     "malzemeler": [
        {"ad": "MİDYE", "miktar_gram": 120},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 40},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "KARABİBER", "miktar_gram": 1},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},
    {"ad": "Bademli Kurabiye", "grup": 3, "mevsim_etiketi": "sonbahar",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "BUĞDAY UNU", "miktar_gram": 50},
        {"ad": "BADEM", "miktar_gram": 25},
        {"ad": "TEREYAĞI", "miktar_gram": 25},
        {"ad": "ŞEKER", "miktar_gram": 20},
        {"ad": "TAVUK YUMURTASI", "miktar_gram": 15},
     ]},
    {"ad": "Şeftalili Komposto", "grup": 3, "mevsim_etiketi": "yaz",
     "etiketler": ["komposto", "vejetaryen"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "ŞEFTALİ", "miktar_gram": 150},
        {"ad": "ŞEKER", "miktar_gram": 20},
        {"ad": "SU", "miktar_gram": 150},
     ]},
    {"ad": "Üzüm Salatası", "grup": 3, "mevsim_etiketi": "sonbahar",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "ROKA", "miktar_gram": 60},
        {"ad": "ÜZÜM", "miktar_gram": 60},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "LİMON SUYU", "miktar_gram": 5},
     ]},
    {"ad": "İncir Tatlısı (Kremalı)", "grup": 3, "mevsim_etiketi": "sonbahar",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "İNCİR", "miktar_gram": 120},
        {"ad": "KREMA (AĞIR)", "miktar_gram": 60},
        {"ad": "CEVİZ (İÇ)", "miktar_gram": 15},
        {"ad": "ŞEKER", "miktar_gram": 15},
     ]},
    {"ad": "Zeytin Ezmesi", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "SİYAH ZEYTİN", "miktar_gram": 100},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "LİMON SUYU", "miktar_gram": 5},
     ]},
    {"ad": "Limonlu Kek", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "BUĞDAY UNU", "miktar_gram": 70},
        {"ad": "LİMON", "miktar_gram": 30},
        {"ad": "ŞEKER", "miktar_gram": 40},
        {"ad": "TEREYAĞI", "miktar_gram": 25},
        {"ad": "TAVUK YUMURTASI", "miktar_gram": 30},
     ]},
]
