# guneydogu_tarifleri.py
#
# Bolgesel genisleme -- IV. Parti: GÜNEYDOĞU ANADOLU BÖLGESİ (24 tarif).
# yukle_yeni_tarifler.py ile (mevcutlari atlayarak) Supabase'e eklenir.
#
# Yeni malzeme (20_guneydogu_malzemeleri_ekle.sql ile eklendi): ISOT.

BOLGE_ADI = "Güneydoğu Anadolu"

GUNEYDOGU_TARIFLERI = [
    # ---- I. Grup (ana yemek) -- 9 ----
    {"ad": "Çiğ Köfte (Vejetaryen)", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "İNCE BULGUR", "miktar_gram": 100},
        {"ad": "KONSERVE DOMATES SALÇASI", "miktar_gram": 30},
        {"ad": "PUL BİBER", "miktar_gram": 3},
        {"ad": "İSOT", "miktar_gram": 2},
        {"ad": "SARIMSAK", "miktar_gram": 3},
        {"ad": "NAR EKŞİSİ", "miktar_gram": 10},
     ]},
    {"ad": "Kuzu Şiş (Isotlu)", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["kirmizi_et", "izgara"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "KUZU ŞİŞ", "miktar_gram": 150},
        {"ad": "İSOT", "miktar_gram": 2},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Alinazik Kebap", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "SIĞIR KIYMA", "miktar_gram": 110},
        {"ad": "PATLICAN", "miktar_gram": 150},
        {"ad": "YOĞURT (TAM)", "miktar_gram": 60},
        {"ad": "SARIMSAK", "miktar_gram": 3},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
     ]},
    {"ad": "İçli Köfte", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 60,
     "malzemeler": [
        {"ad": "SIĞIR KIYMA", "miktar_gram": 100},
        {"ad": "İNCE BULGUR", "miktar_gram": 60},
        {"ad": "CEVİZ (İÇ)", "miktar_gram": 15},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "İSOT", "miktar_gram": 2},
     ]},
    {"ad": "Küşleme (Kuzu Kavurma)", "grup": 1, "mevsim_etiketi": "kis",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "KUZU TANDIR", "miktar_gram": 140},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Antep Fıstıklı Tavuk Sote", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["beyaz_et"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 150},
        {"ad": "ANTEP FISTIĞI", "miktar_gram": 20},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
     ]},
    {"ad": "Isotlu Tavuk Şiş", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["beyaz_et", "izgara"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 150},
        {"ad": "İSOT", "miktar_gram": 2},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "LİMON", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Nohutlu Kuzu Yahnisi", "grup": 1, "mevsim_etiketi": "kis",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 60,
     "malzemeler": [
        {"ad": "KUZU TANDIR", "miktar_gram": 120},
        {"ad": "NOHUT", "miktar_gram": 40},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Antep Usulü Mercimekli Köfte", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["kuru_baklagil", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "KIRMIZI MERCİMEK", "miktar_gram": 50},
        {"ad": "İNCE BULGUR", "miktar_gram": 40},
        {"ad": "İSOT", "miktar_gram": 2},
        {"ad": "SARIMSAK", "miktar_gram": 3},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
     ]},

    # ---- II. Grup (yardımcı yemek) -- 7 ----
    {"ad": "Yoğurtlu Mercimek Çorbası", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["corba", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "KIRMIZI MERCİMEK", "miktar_gram": 45},
        {"ad": "YOĞURT (TAM)", "miktar_gram": 60},
        {"ad": "TEREYAĞI", "miktar_gram": 8},
        {"ad": "KURU NANE", "miktar_gram": 1},
     ]},
    {"ad": "Antep Usulü Bulgur Pilavı (İsotlu)", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "BULGUR", "miktar_gram": 50},
        {"ad": "İSOT", "miktar_gram": 2},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
     ]},
    {"ad": "Antep Usulü Nohutlu Bulgur", "grup": 2, "mevsim_etiketi": "sonbahar",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "NOHUT", "miktar_gram": 30},
        {"ad": "BULGUR", "miktar_gram": 45},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
     ]},
    {"ad": "Güneydoğu Usulü Ispanaklı Börek", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "YUFKA", "miktar_gram": 80},
        {"ad": "ISPANAK", "miktar_gram": 100},
        {"ad": "LOR PEYNİRİ", "miktar_gram": 30},
        {"ad": "TEREYAĞI", "miktar_gram": 15},
     ]},
    {"ad": "Zeytinyağlı Nane Soslu Kabak", "grup": 2, "mevsim_etiketi": "yaz",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "KABAK", "miktar_gram": 200},
        {"ad": "YOĞURT (TAM)", "miktar_gram": 60},
        {"ad": "KURU NANE", "miktar_gram": 1},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
     ]},
    {"ad": "Antep Usulü Katmer (Kahvaltılık)", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "YUFKA", "miktar_gram": 70},
        {"ad": "KAŞAR PEYNİRİ", "miktar_gram": 50},
        {"ad": "TEREYAĞI", "miktar_gram": 15},
     ]},
    {"ad": "Antep Usulü Zeytinyağlı Nohut", "grup": 2, "mevsim_etiketi": "yaz",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "NOHUT", "miktar_gram": 70},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "LİMON SUYU", "miktar_gram": 10},
     ]},

    # ---- III. Grup (tamamlayıcılar) -- 8 ----
    {"ad": "Sumaklı Soğan Salatası", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "TAZE SOĞAN", "miktar_gram": 60},
        {"ad": "SUMAK", "miktar_gram": 3},
        {"ad": "NAR EKŞİSİ", "miktar_gram": 8},
        {"ad": "MAYDONOZ", "miktar_gram": 5},
     ]},
    {"ad": "Antep Usulü Baklava", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 60,
     "malzemeler": [
        {"ad": "YUFKA", "miktar_gram": 90},
        {"ad": "ANTEP FISTIĞI", "miktar_gram": 30},
        {"ad": "TEREYAĞI", "miktar_gram": 30},
        {"ad": "ŞEKER", "miktar_gram": 40},
        {"ad": "SU", "miktar_gram": 40},
     ]},
    {"ad": "Fıstıklı Katmer (Tatlı, Kaymaklı)", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "YUFKA", "miktar_gram": 60},
        {"ad": "ANTEP FISTIĞI", "miktar_gram": 25},
        {"ad": "ŞEKER", "miktar_gram": 20},
        {"ad": "TEREYAĞI", "miktar_gram": 15},
     ]},
    {"ad": "Antep Fıstıklı Künefe", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "KADAYIF", "miktar_gram": 70},
        {"ad": "KAŞAR PEYNİRİ", "miktar_gram": 60},
        {"ad": "ANTEP FISTIĞI", "miktar_gram": 15},
        {"ad": "ŞEKER", "miktar_gram": 30},
        {"ad": "TEREYAĞI", "miktar_gram": 15},
     ]},
    {"ad": "Kayısı Tatlısı (Cevizli)", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "KURU KAYISI", "miktar_gram": 100},
        {"ad": "CEVİZ (İÇ)", "miktar_gram": 20},
        {"ad": "KREMA (AĞIR)", "miktar_gram": 30},
        {"ad": "ŞEKER", "miktar_gram": 10},
     ]},
    {"ad": "Sumaklı Cacık", "grup": 3, "mevsim_etiketi": "yaz",
     "etiketler": ["yogurt", "cacik", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "YOĞURT (TAM)", "miktar_gram": 180},
        {"ad": "SALATALIK", "miktar_gram": 60},
        {"ad": "SUMAK", "miktar_gram": 2},
        {"ad": "SARIMSAK", "miktar_gram": 3},
     ]},
    {"ad": "Sumaklı Kırmızı Lahana Salatası", "grup": 3, "mevsim_etiketi": "kis",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "KIRMIZI LAHANA", "miktar_gram": 120},
        {"ad": "SUMAK", "miktar_gram": 3},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "LİMON SUYU", "miktar_gram": 8},
     ]},
    {"ad": "Yoğurtlu Bulgur Salatası", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["yogurt", "vejetaryen"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "BULGUR", "miktar_gram": 40},
        {"ad": "YOĞURT (TAM)", "miktar_gram": 100},
        {"ad": "SARIMSAK", "miktar_gram": 3},
        {"ad": "KURU NANE", "miktar_gram": 1},
     ]},
]
