# tarif_verisi.py
#
# Yillik Menu Uretim Motoru - 74 tariflik baslangic kutuphanesi.
# Anayasa v3'e gore: Grup 1 (et/tavuk/balik/etli sebze/kuru baklagil/yumurta),
# Grup 2 (corba/pilav/zeytinyagli/makarna/borek), Grup 3 (salata/tatli/
# komposto/yogurt/cacik/tursu).
#
# Etiket sozlugu (ozel_etiketler) iki turdedir:
#   KURAL ETIKETLERI (uyumsuzluk_kurallari / tamamlayici_eslestirme tablolarinda
#   kullanilir, degistirilemez): zeytinyagli, etli_sebze, etli_zeytinyagli_dolma,
#   dolma, izgara, tursu, kuru_baklagil, salata, balik, pilav_makarna_borek,
#   tatli, sporcu_uygun
#   SINIFLANDIRMA ETIKETLERI (kural motorunu etkilemez, haftalik denge/mevsim
#   filtrelemesi icin): kirmizi_et, beyaz_et, vejetaryen, corba, pilav, borek,
#   komposto, cacik, yumurta
#
# Her tarif: {"ad", "grup" (1/2/3), "mevsim_etiketi", "etiketler", "hazirlik_dakika",
#             "malzemeler": [{"ad": <malzemeler.ad ile birebir>, "miktar_gram": N}]}
# porsiyon_sayisi tum kutuphanede 1 sabittir (yillik menu = kisi basi gunluk plan).

TARIFLER = [
    # ============================================================
    # GRUP 1 -- 30 tarif (I. Grup: et/tavuk/balik/etli sebze/kuru baklagil/yumurta)
    # ============================================================

    # -- Kirmizi et (6) --
    {"ad": "Dana Kuşbaşı Sote", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "DANA BİFTEK", "miktar_gram": 100},
        {"ad": "KURU SOĞAN", "miktar_gram": 40},
        {"ad": "YEŞİL BİBER", "miktar_gram": 30},
        {"ad": "DOMATES", "miktar_gram": 40},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
     ]},
    {"ad": "Izgara Dana Biftek", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["kirmizi_et", "izgara"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "DANA BİFTEK", "miktar_gram": 120},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
        {"ad": "KEKİK", "miktar_gram": 1},
     ]},
    {"ad": "Kuzu Tandır", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["kirmizi_et", "izgara"], "hazirlik_dakika": 120,
     "malzemeler": [
        {"ad": "KUZU TANDIR", "miktar_gram": 120},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
        {"ad": "KEKİK", "miktar_gram": 1},
     ]},
    {"ad": "Sığır Kaburga Haşlama", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 150,
     "malzemeler": [
        {"ad": "SIĞIR KABURGA", "miktar_gram": 110},
        {"ad": "HAVUÇ", "miktar_gram": 50},
        {"ad": "PATATES", "miktar_gram": 80},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
     ]},
    {"ad": "Dana Rosto", "grup": 1, "mevsim_etiketi": "kis",
     "etiketler": ["kirmizi_et"], "hazirlik_dakika": 90,
     "malzemeler": [
        {"ad": "DANA ROSTO", "miktar_gram": 110},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "HAVUÇ", "miktar_gram": 40},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
     ]},
    {"ad": "Kuzu Pirzola Izgara", "grup": 1, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["kirmizi_et", "izgara"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "KUZU PİRZOLA", "miktar_gram": 120},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
        {"ad": "BİBERİYE", "miktar_gram": 1},
     ]},

    # -- Tavuk / beyaz et (6) --
    {"ad": "Fırında Tavuk But", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["beyaz_et"], "hazirlik_dakika": 60,
     "malzemeler": [
        {"ad": "TAVUK BUT", "miktar_gram": 180},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
        {"ad": "KEKİK", "miktar_gram": 1},
     ]},
    {"ad": "Tavuk Şiş", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["beyaz_et", "izgara"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 150},
        {"ad": "YEŞİL BİBER", "miktar_gram": 30},
        {"ad": "DOMATES", "miktar_gram": 30},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 6},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
     ]},
    {"ad": "Tavuk Sote", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["beyaz_et"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 150},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "SARI BİBER", "miktar_gram": 30},
        {"ad": "DOMATES", "miktar_gram": 40},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Tavuk Suyu Haşlama", "grup": 1, "mevsim_etiketi": "kis",
     "etiketler": ["beyaz_et"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "TAVUK BÜTÜN", "miktar_gram": 180},
        {"ad": "HAVUÇ", "miktar_gram": 40},
        {"ad": "KEREVİZ", "miktar_gram": 30},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Kremalı Mantarlı Tavuk", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["beyaz_et"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 150},
        {"ad": "MANTAR", "miktar_gram": 60},
        {"ad": "KREMA (SIVI)", "miktar_gram": 40},
        {"ad": "TEREYAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KARABİBER", "miktar_gram": 1},
     ]},
    {"ad": "Izgara Tavuk Göğsü", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["beyaz_et", "izgara", "sporcu_uygun"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 180},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 6},
        {"ad": "TUZ", "miktar_gram": 3},
        {"ad": "KEKİK", "miktar_gram": 1},
     ]},

    # -- Balik / deniz urunu (6) --
    {"ad": "Fırında Levrek", "grup": 1, "mevsim_etiketi": "kis",
     "etiketler": ["balik"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "LEVREK", "miktar_gram": 180},
        {"ad": "LİMON", "miktar_gram": 20},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Izgara Çipura", "grup": 1, "mevsim_etiketi": "kis",
     "etiketler": ["balik", "izgara"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "ÇİPURA", "miktar_gram": 180},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "LİMON", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Hamsi Tava", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["balik"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "HAMSİ", "miktar_gram": 150},
        {"ad": "MISIR UNU", "miktar_gram": 20},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Somon Izgara", "grup": 1, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["balik", "izgara"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "SOMON", "miktar_gram": 150},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "LİMON", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Karides Güveç", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["balik"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "KARİDES", "miktar_gram": 130},
        {"ad": "DOMATES", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Kalamar Tava", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["balik"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "KALAMAR", "miktar_gram": 150},
        {"ad": "BUĞDAY UNU", "miktar_gram": 20},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 15},
        {"ad": "LİMON", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # -- Etli sebze / dolma (5) --
    {"ad": "Karnıyarık", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["etli_sebze"], "hazirlik_dakika": 60,
     "malzemeler": [
        {"ad": "PATLICAN", "miktar_gram": 200},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 80},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "DOMATES", "miktar_gram": 40},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Etli Biber Dolması", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["etli_sebze", "dolma", "etli_zeytinyagli_dolma"], "hazirlik_dakika": 70,
     "malzemeler": [
        {"ad": "YEŞİL BİBER", "miktar_gram": 200},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 70},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 30},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "DOMATES", "miktar_gram": 30},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Etli Kabak Dolması", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["etli_sebze", "dolma", "etli_zeytinyagli_dolma"], "hazirlik_dakika": 65,
     "malzemeler": [
        {"ad": "KABAK", "miktar_gram": 220},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 70},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 30},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Etli Yaprak Sarma", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["etli_sebze", "dolma", "etli_zeytinyagli_dolma"], "hazirlik_dakika": 90,
     "malzemeler": [
        {"ad": "SALAMURA YAPRAK", "miktar_gram": 120},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 70},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 30},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Patlıcan Musakka", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["etli_sebze"], "hazirlik_dakika": 55,
     "malzemeler": [
        {"ad": "PATLICAN", "miktar_gram": 200},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 70},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "KONSERVE DOMATES", "miktar_gram": 40},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 12},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # -- Kuru baklagil (5) --
    {"ad": "Etli Kuru Fasulye", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["kuru_baklagil"], "hazirlik_dakika": 80,
     "malzemeler": [
        {"ad": "KURU FASULYE", "miktar_gram": 60},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "KONSERVE DOMATES SALÇASI", "miktar_gram": 15},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Etli Nohut Yemeği", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["kuru_baklagil"], "hazirlik_dakika": 70,
     "malzemeler": [
        {"ad": "NOHUT", "miktar_gram": 60},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "KONSERVE DOMATES", "miktar_gram": 30},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Mercimek Köftesi", "grup": 1, "mevsim_etiketi": "sonbahar",
     "etiketler": ["kuru_baklagil", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "KIRMIZI MERCİMEK", "miktar_gram": 50},
        {"ad": "İNCE BULGUR", "miktar_gram": 40},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "MAYDONOZ", "miktar_gram": 10},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Barbunya Pilaki", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["kuru_baklagil", "zeytinyagli", "vejetaryen"], "hazirlik_dakika": 60,
     "malzemeler": [
        {"ad": "BARBUNYA", "miktar_gram": 70},
        {"ad": "HAVUÇ", "miktar_gram": 30},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Nohut Yemeği", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["kuru_baklagil", "zeytinyagli", "vejetaryen"], "hazirlik_dakika": 55,
     "malzemeler": [
        {"ad": "NOHUT", "miktar_gram": 70},
        {"ad": "HAVUÇ", "miktar_gram": 30},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # -- Yumurta (2) --
    {"ad": "Menemen", "grup": 1, "mevsim_etiketi": "yaz",
     "etiketler": ["yumurta", "vejetaryen"], "hazirlik_dakika": 15,
     "malzemeler": [
        {"ad": "TAVUK YUMURTASI", "miktar_gram": 120},
        {"ad": "DOMATES", "miktar_gram": 100},
        {"ad": "YEŞİL BİBER", "miktar_gram": 40},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Sahanda Yumurta (Sucuklu)", "grup": 1, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["yumurta"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "TAVUK YUMURTASI", "miktar_gram": 100},
        {"ad": "SUCUK", "miktar_gram": 40},
        {"ad": "TEREYAĞI", "miktar_gram": 8},
     ]},

    # ============================================================
    # GRUP 2 -- 24 tarif (II. Grup: corba/pilav/zeytinyagli/makarna/borek)
    # ============================================================

    # -- Corba (6) --
    {"ad": "Mercimek Çorbası", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["corba", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "KIRMIZI MERCİMEK", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "HAVUÇ", "miktar_gram": 30},
        {"ad": "TEREYAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Ezogelin Çorbası", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["corba", "vejetaryen"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "KIRMIZI MERCİMEK", "miktar_gram": 40},
        {"ad": "İNCE BULGUR", "miktar_gram": 15},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "KONSERVE DOMATES SALÇASI", "miktar_gram": 10},
        {"ad": "TEREYAĞI", "miktar_gram": 8},
        {"ad": "PUL BİBER", "miktar_gram": 1},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Yayla Çorbası", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["corba", "vejetaryen"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "YOĞURT (TAM)", "miktar_gram": 150},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 20},
        {"ad": "TEREYAĞI", "miktar_gram": 8},
        {"ad": "TAZE NANE", "miktar_gram": 2},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Domates Çorbası", "grup": 2, "mevsim_etiketi": "yaz",
     "etiketler": ["corba", "vejetaryen"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "KONSERVE DOMATES", "miktar_gram": 150},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "KREMA (SIVI)", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Tavuk Suyu Çorbası (Şehriyeli)", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["corba"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "TAVUK SUYU", "miktar_gram": 300},
        {"ad": "ŞEHRİYE", "miktar_gram": 20},
        {"ad": "HAVUÇ", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Sebze Çorbası", "grup": 2, "mevsim_etiketi": "sonbahar",
     "etiketler": ["corba", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "HAVUÇ", "miktar_gram": 40},
        {"ad": "PATATES", "miktar_gram": 40},
        {"ad": "KEREVİZ", "miktar_gram": 30},
        {"ad": "PIRASA", "miktar_gram": 30},
        {"ad": "TEREYAĞI", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # -- Pilav (6) --
    {"ad": "İç Pilav", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 60},
        {"ad": "ÇAM FISTIĞI", "miktar_gram": 15},
        {"ad": "KUŞ ÜZÜMÜ", "miktar_gram": 15},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "TEREYAĞI", "miktar_gram": 15},
        {"ad": "YENİBAHAR", "miktar_gram": 1},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Sade Pirinç Pilavı", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 50},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Bulgur Pilavı", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "BULGUR", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "KONSERVE DOMATES SALÇASI", "miktar_gram": 10},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Şehriyeli Pirinç Pilavı", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 45},
        {"ad": "ŞEHRİYE", "miktar_gram": 10},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Nohutlu Pilav", "grup": 2, "mevsim_etiketi": "sonbahar",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 45},
        {"ad": "NOHUT", "miktar_gram": 30},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Kuşkonmaz Risotto", "grup": 2, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 35,
     "malzemeler": [
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 50},
        {"ad": "KUŞKONMAZ", "miktar_gram": 60},
        {"ad": "PARMESAN", "miktar_gram": 15},
        {"ad": "TEREYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # -- Zeytinyagli (6) --
    {"ad": "Zeytinyağlı Taze Fasulye", "grup": 2, "mevsim_etiketi": "yaz",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "TAZE FASULYE", "miktar_gram": 200},
        {"ad": "KURU SOĞAN", "miktar_gram": 25},
        {"ad": "DOMATES", "miktar_gram": 40},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Pırasa", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "PIRASA", "miktar_gram": 200},
        {"ad": "HAVUÇ", "miktar_gram": 30},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 15},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Enginar", "grup": 2, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "ENGİNAR", "miktar_gram": 150},
        {"ad": "HAVUÇ", "miktar_gram": 30},
        {"ad": "TAZE FASULYE", "miktar_gram": 40},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "LİMON SUYU", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Kereviz", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "KEREVİZ", "miktar_gram": 180},
        {"ad": "HAVUÇ", "miktar_gram": 30},
        {"ad": "PATATES", "miktar_gram": 30},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 15},
        {"ad": "LİMON SUYU", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "İmam Bayıldı", "grup": 2, "mevsim_etiketi": "yaz",
     "etiketler": ["zeytinyagli", "vejetaryen"], "hazirlik_dakika": 50,
     "malzemeler": [
        {"ad": "PATLICAN", "miktar_gram": 200},
        {"ad": "KURU SOĞAN", "miktar_gram": 40},
        {"ad": "DOMATES", "miktar_gram": 50},
        {"ad": "SARIMSAK", "miktar_gram": 5},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Zeytinyağlı Yaprak Sarma", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["zeytinyagli", "dolma", "etli_zeytinyagli_dolma", "vejetaryen"], "hazirlik_dakika": 80,
     "malzemeler": [
        {"ad": "SALAMURA YAPRAK", "miktar_gram": 120},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 40},
        {"ad": "KURU SOĞAN", "miktar_gram": 30},
        {"ad": "ÇAM FISTIĞI", "miktar_gram": 15},
        {"ad": "KUŞ ÜZÜMÜ", "miktar_gram": 10},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 20},
        {"ad": "LİMON SUYU", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # -- Makarna (3) --
    {"ad": "Domates Soslu Makarna", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "MAKARNA", "miktar_gram": 50},
        {"ad": "KONSERVE DOMATES", "miktar_gram": 80},
        {"ad": "SARIMSAK", "miktar_gram": 3},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Fırın Makarna (Kıymalı)", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "MAKARNA", "miktar_gram": 50},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 60},
        {"ad": "KAŞAR PEYNİRİ", "miktar_gram": 20},
        {"ad": "KREMA (SIVI)", "miktar_gram": 30},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Fesleğenli Pesto Makarna", "grup": 2, "mevsim_etiketi": "yaz",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "MAKARNA", "miktar_gram": 50},
        {"ad": "PESTO SOS", "miktar_gram": 30},
        {"ad": "PARMESAN", "miktar_gram": 10},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},

    # -- Borek (4) --
    {"ad": "Su Böreği (Peynirli)", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 60,
     "malzemeler": [
        {"ad": "BUĞDAY UNU", "miktar_gram": 60},
        {"ad": "TAVUK YUMURTASI", "miktar_gram": 40},
        {"ad": "LOR PEYNİRİ", "miktar_gram": 50},
        {"ad": "MAYDONOZ", "miktar_gram": 5},
        {"ad": "TEREYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Sigara Böreği (Peynirli)", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 40,
     "malzemeler": [
        {"ad": "BUĞDAY UNU", "miktar_gram": 40},
        {"ad": "LOR PEYNİRİ", "miktar_gram": 50},
        {"ad": "MAYDONOZ", "miktar_gram": 5},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 20},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},
    {"ad": "Ispanaklı Börek", "grup": 2, "mevsim_etiketi": "kis",
     "etiketler": ["pilav_makarna_borek", "vejetaryen"], "hazirlik_dakika": 50,
     "malzemeler": [
        {"ad": "BUĞDAY UNU", "miktar_gram": 50},
        {"ad": "ISPANAK", "miktar_gram": 100},
        {"ad": "LOR PEYNİRİ", "miktar_gram": 30},
        {"ad": "TEREYAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},
    {"ad": "Kıymalı Börek", "grup": 2, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["pilav_makarna_borek"], "hazirlik_dakika": 55,
     "malzemeler": [
        {"ad": "BUĞDAY UNU", "miktar_gram": 50},
        {"ad": "SIĞIR KIYMA", "miktar_gram": 50},
        {"ad": "KURU SOĞAN", "miktar_gram": 20},
        {"ad": "AYÇİÇEK YAĞI", "miktar_gram": 15},
        {"ad": "TUZ", "miktar_gram": 3},
     ]},

    # ============================================================
    # GRUP 3 -- 20 tarif (III. Grup: salata/tatli/komposto/yogurt/cacik/tursu)
    # ============================================================

    # -- Salata (5) --
    {"ad": "Çoban Salata", "grup": 3, "mevsim_etiketi": "yaz",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "DOMATES", "miktar_gram": 80},
        {"ad": "YEŞİL BİBER", "miktar_gram": 40},
        {"ad": "TAZE SOĞAN", "miktar_gram": 20},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "LİMON SUYU", "miktar_gram": 5},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},
    {"ad": "Mevsim Yeşil Salata", "grup": 3, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "MARUL", "miktar_gram": 100},
        {"ad": "TURP", "miktar_gram": 30},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "LİMON SUYU", "miktar_gram": 5},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},
    {"ad": "Roka Salatası (Parmesanlı)", "grup": 3, "mevsim_etiketi": "sonbahar",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "ROKA", "miktar_gram": 80},
        {"ad": "PARMESAN", "miktar_gram": 15},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 10},
        {"ad": "LİMON SUYU", "miktar_gram": 5},
     ]},
    {"ad": "Kırmızı Lahana Salatası", "grup": 3, "mevsim_etiketi": "kis",
     "etiketler": ["salata", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "KIRMIZI LAHANA", "miktar_gram": 120},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 8},
        {"ad": "LİMON SUYU", "miktar_gram": 8},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},
    {"ad": "Sezar Usulü Tavuklu Salata", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["salata", "sporcu_uygun"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "MARUL", "miktar_gram": 100},
        {"ad": "TAVUK GÖĞÜS", "miktar_gram": 60},
        {"ad": "PARMESAN", "miktar_gram": 10},
        {"ad": "SEZAR SOS", "miktar_gram": 20},
     ]},

    # -- Cacik / yogurt (2) --
    {"ad": "Cacık", "grup": 3, "mevsim_etiketi": "yaz",
     "etiketler": ["yogurt", "cacik", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "YOĞURT (TAM)", "miktar_gram": 180},
        {"ad": "SALATALIK", "miktar_gram": 60},
        {"ad": "SARIMSAK", "miktar_gram": 3},
        {"ad": "ZEYTİNYAĞI", "miktar_gram": 5},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},
    {"ad": "Havuçlu Yoğurtlu Salata", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["yogurt", "vejetaryen"], "hazirlik_dakika": 10,
     "malzemeler": [
        {"ad": "YOĞURT (TAM)", "miktar_gram": 150},
        {"ad": "HAVUÇ", "miktar_gram": 60},
        {"ad": "SARIMSAK", "miktar_gram": 2},
        {"ad": "TUZ", "miktar_gram": 2},
     ]},

    # -- Tursu (2) --
    {"ad": "Karışık Turşu", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tursu", "vejetaryen"], "hazirlik_dakika": 5,
     "malzemeler": [
        {"ad": "KONSERVE TURŞU", "miktar_gram": 100},
     ]},
    {"ad": "Lahana Turşusu", "grup": 3, "mevsim_etiketi": "kis",
     "etiketler": ["tursu", "vejetaryen"], "hazirlik_dakika": 5,
     "malzemeler": [
        {"ad": "LAHANA", "miktar_gram": 100},
        {"ad": "TUZ", "miktar_gram": 5},
        {"ad": "SİRKE", "miktar_gram": 10},
     ]},

    # -- Komposto (3) --
    {"ad": "Kayısı Kompostosu", "grup": 3, "mevsim_etiketi": "yaz",
     "etiketler": ["komposto", "vejetaryen"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "KAYISI", "miktar_gram": 150},
        {"ad": "ŞEKER", "miktar_gram": 20},
        {"ad": "SU", "miktar_gram": 150},
     ]},
    {"ad": "Vişne Kompostosu", "grup": 3, "mevsim_etiketi": "yaz",
     "etiketler": ["komposto", "vejetaryen"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "VİŞNE", "miktar_gram": 150},
        {"ad": "ŞEKER", "miktar_gram": 25},
        {"ad": "SU", "miktar_gram": 150},
     ]},
    {"ad": "Elma Kompostosu", "grup": 3, "mevsim_etiketi": "kis",
     "etiketler": ["komposto", "vejetaryen"], "hazirlik_dakika": 20,
     "malzemeler": [
        {"ad": "ELMA", "miktar_gram": 150},
        {"ad": "TARÇIN", "miktar_gram": 1},
        {"ad": "ŞEKER", "miktar_gram": 20},
        {"ad": "SU", "miktar_gram": 150},
     ]},

    # -- Tatli (8) --
    {"ad": "Sütlaç", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 45,
     "malzemeler": [
        {"ad": "SÜT (TAM YAĞ)", "miktar_gram": 200},
        {"ad": "PİRİNÇ (HAM)", "miktar_gram": 15},
        {"ad": "ŞEKER", "miktar_gram": 20},
        {"ad": "MISIR NİŞASTASI", "miktar_gram": 5},
     ]},
    {"ad": "Kazandibi", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli"], "hazirlik_dakika": 50,
     "malzemeler": [
        {"ad": "SÜT (TAM YAĞ)", "miktar_gram": 200},
        {"ad": "TAVUK GÖĞSÜ (TATLI)", "miktar_gram": 20},
        {"ad": "ŞEKER", "miktar_gram": 25},
        {"ad": "MISIR NİŞASTASI", "miktar_gram": 10},
     ]},
    {"ad": "Revani", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 50,
     "malzemeler": [
        {"ad": "İRMİK", "miktar_gram": 50},
        {"ad": "BUĞDAY UNU", "miktar_gram": 20},
        {"ad": "ŞEKER", "miktar_gram": 60},
        {"ad": "TAVUK YUMURTASI", "miktar_gram": 30},
        {"ad": "SU", "miktar_gram": 60},
     ]},
    {"ad": "Aşure", "grup": 3, "mevsim_etiketi": "kis",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 90,
     "malzemeler": [
        {"ad": "BUĞDAY UNU", "miktar_gram": 20},
        {"ad": "NOHUT", "miktar_gram": 15},
        {"ad": "KURU FASULYE", "miktar_gram": 15},
        {"ad": "KURU KAYISI", "miktar_gram": 15},
        {"ad": "KURU ÜZÜM", "miktar_gram": 15},
        {"ad": "KURU İNCİR", "miktar_gram": 15},
        {"ad": "CEVİZ (İÇ)", "miktar_gram": 10},
        {"ad": "ŞEKER", "miktar_gram": 30},
        {"ad": "SU", "miktar_gram": 200},
     ]},
    {"ad": "Muhallebi", "grup": 3, "mevsim_etiketi": "yil_boyunca",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 30,
     "malzemeler": [
        {"ad": "SÜT (TAM YAĞ)", "miktar_gram": 200},
        {"ad": "MISIR NİŞASTASI", "miktar_gram": 15},
        {"ad": "ŞEKER", "miktar_gram": 20},
     ]},
    {"ad": "Cevizli Kadayıf Tatlısı", "grup": 3, "mevsim_etiketi": "sonbahar",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 60,
     "malzemeler": [
        {"ad": "KADAYIF", "miktar_gram": 60},
        {"ad": "CEVİZ (İÇ)", "miktar_gram": 20},
        {"ad": "TEREYAĞI", "miktar_gram": 20},
        {"ad": "ŞEKER", "miktar_gram": 30},
        {"ad": "SU", "miktar_gram": 40},
     ]},
    {"ad": "Meyveli Panna Cotta", "grup": 3, "mevsim_etiketi": "ilkbahar",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 25,
     "malzemeler": [
        {"ad": "KREMA (AĞIR)", "miktar_gram": 120},
        {"ad": "SÜT (TAM YAĞ)", "miktar_gram": 60},
        {"ad": "JELATİN", "miktar_gram": 3},
        {"ad": "ŞEKER", "miktar_gram": 20},
        {"ad": "ÇİLEK", "miktar_gram": 40},
     ]},
    {"ad": "Mevsim Meyve Tabağı", "grup": 3, "mevsim_etiketi": "yaz",
     "etiketler": ["tatli", "vejetaryen"], "hazirlik_dakika": 5,
     "malzemeler": [
        {"ad": "KARPUZ", "miktar_gram": 100},
        {"ad": "KAVUN", "miktar_gram": 60},
        {"ad": "ÜZÜM", "miktar_gram": 60},
     ]},
]
