select ad, bolge, hazirlik_dakika from receteler
where isletme_id is null
  and ad in (
    'Bursa İskender Kebabı',
    'İnegöl Köfte',
    'Bursa Kestaneli Kaz Dolması',
    'İstanbul Usulü Karnıyarık',
    'Bandırma Mantısı',
    'Marmara Usulü Midye Tava',
    'Kırklareli Rokalı Beyaz Peynir Salatası',
    'Marmara Kestaneli Muhallebi',
    'İzmir Köfte (Fırında)',
    'Çeşme Usulü Ahtapot Güveç',
    'Ege Otlu Peynirli Gözleme',
    'Ege Usulü Isırgan Kavurması (Etli)',
    'Ege Yaylası Kuzu Tandır',
    'Ege Portakallı Zeytinyağlı Kek',
    'Datça Bademli Yeşil Salata',
    'Ege İnciri ile Komposto',
    'Antalya Usulü Nohut Piyazı',
    'Mersin Tantunisi',
    'Adana Kebap',
    'Hatay Usulü İçli Köfte (Etli)',
    'Antalya Şakşuka',
    'Akdeniz Usulü Limonlu Zeytin Ezmesi',
    'Adana Usulü Nar Ekşili Salata',
    'Antalya Usulü Şeftali Kompostosu',
    'Kayseri Mantısı',
    'Ankara Tava (Kuzu Etli)',
    'Konya Etli Ekmek',
    'Nevşehir Testi Kebabı',
    'Kayseri Yağlaması',
    'Kapadokya Kestaneli Komposto',
    'Kayseri Usulü Nohutlu Bulgur Pilavı',
    'Niğde Bademli Un Helvası',
    'Karadeniz Mıhlaması',
    'Karadeniz Kaymaklı Pide',
    'Trabzon Usulü Hamsili Pilav',
    'Rize Usulü Karalahana Çorbası',
    'Giresun Fındıklı Kuru Fasulye',
    'Karadeniz Mısır Ekmeği',
    'Trabzon Usulü Akçaabat Köfte',
    'Karadeniz Dutlu Komposto',
    'Erzurum Cağ Kebabı',
    'Erzincan Tulumlu Kavurma',
    'Van Otlu Peynirli Kahvaltı Böreği',
    'Malatya Kayısılı Kuzu Yahnisi',
    'Elazığ Usulü Kuru Fasulye Kavurması',
    'Kars Usulü Kaz Eti Kavurması',
    'Doğu Anadolu Pekmezli Ceviz Ezmesi',
    'Doğu Anadolu Kayısı ve Ceviz Salatası',
    'Gaziantep Alinazik Kebabı',
    'Şanlıurfa Usulü Çiğ Köfte (Etsiz)',
    'Urfa Usulü Kuzu Kavurma',
    'Mardin Usulü Kaburga Dolması',
    'Diyarbakır Usulü Meftune',
    'Antep Usulü Yuvalama Çorbası',
    'Siirt Usulü Büryan',
    'Antep Fıstıklı Muhallebi'
  )
order by ad;