-- 59_usda_ve_turkpatent_ikinci_parti.sql
--
-- 13 Agustos 2026 (Oturum 11, devam): 24 malzeme daha tamamlandi.
--
-- USDA'DAN (23 malzeme): MAYDANOZ, MAYDANOZ (KURU), ASMA YAPRAĞI,
-- KEBERE, KEÇİBOYNUZU, YENİDÜNYA, KARNABAHAR, KUYRUKYAĞI, MİLFÖY
-- HAMURU, KATMER, BÖREK (2), GÜLLAÇ, HARDALİYE, IHLAMUR, TATLANDIRICI
-- (sodyum siklamat/sakarin), 3 LEBLEBİ, SİMİT, 2 MANTI, BAHARAT
-- KARIŞIMI, KAZANDİBİ (3), KEŞKÜL (3), TAVŞAN ETİ.
--
-- Yine ciddi yanlis eslesmeler bulunup duzeltildi (Boza->enerji
-- icecegi, Simit->sogan halkasi, Leblebi->nohut unu, Kolza tohumu->
-- ekmek meyvesi tohumu, Kuyrukyagi->sigir yagi -- hepsi anahtar kelime
-- dogrulamasiyla duzeltildi). BOZA, KOLZA TOHUMU, BUĞDAY NİŞASTASI
-- icin DOGRU bir USDA eslesmesi bulunamadi, ISLENMEDI.
--
-- TÜRKPATENT'TEN (1 malzeme): MERSİN CEZERYESİ -- Tescil No 44'ten
-- (havuc+seker+ceviz oranlari) hesaplandi, kendi HAVUÇ/ŞEKER/CEVİZ
-- verilerimizden turetildi.
--
-- BULUNAMAYANLAR (USDA'nin hicbir veri setinde yok): YAZ HELVASI,
-- YAPRAK SARMA (dolgu haliyle), TATLANDIRICI (saf sorbitol tozu) --
-- zorlanmadi, bos birakildi.
--
-- Tum UPDATE'ler coalesce() ile SADECE bos olan alanlari dolduruyor,
-- mevcut TürKomp/USDA/hesaplanan verilere dokunmuyor.

update malzemeler set kalori = coalesce(kalori, 36.0), protein = coalesce(protein, 2.97), yag = coalesce(yag, 0.79), karbonhidrat = coalesce(karbonhidrat, 6.33), sodyum_mg = coalesce(sodyum_mg, 56.0), lif_g = coalesce(lif_g, 3.3), seker_g = coalesce(seker_g, 0.85), doymus_yag_g = coalesce(doymus_yag_g, 0.132), vitamin_a_mcg = coalesce(vitamin_a_mcg, 421.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.086), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.098), vitamin_b3_mg = coalesce(vitamin_b3_mg, 1.313), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.4), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.09), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 152.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 133.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.75), vitamin_k_mcg = coalesce(vitamin_k_mcg, 1640.0), kalsiyum_mg = coalesce(kalsiyum_mg, 138.0), demir_mg = coalesce(demir_mg, 6.2), magnezyum_mg = coalesce(magnezyum_mg, 50.0), potasyum_mg = coalesce(potasyum_mg, 554.0), cinko_mg = coalesce(cinko_mg, 1.07), fosfor_mg = coalesce(fosfor_mg, 58.0), bakir_mg = coalesce(bakir_mg, 0.149), manganez_mg = coalesce(manganez_mg, 0.16), selenyum_mcg = coalesce(selenyum_mcg, 0.1) where isletme_id is null and ad = 'MAYDANOZ';

update malzemeler set kalori = coalesce(kalori, 271.0), protein = coalesce(protein, 31.3), yag = coalesce(yag, 5.2), karbonhidrat = coalesce(karbonhidrat, 42.38), sodyum_mg = coalesce(sodyum_mg, 391.0), lif_g = coalesce(lif_g, 32.7), vitamin_b1_mg = coalesce(vitamin_b1_mg, 1.04), vitamin_b2_mg = coalesce(vitamin_b2_mg, 2.26), vitamin_b3_mg = coalesce(vitamin_b3_mg, 10.4), vitamin_b5_mg = coalesce(vitamin_b5_mg, 2.516), vitamin_b6_mg = coalesce(vitamin_b6_mg, 1.375), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 194.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 149.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), kalsiyum_mg = coalesce(kalsiyum_mg, 176.0), demir_mg = coalesce(demir_mg, 53.9), magnezyum_mg = coalesce(magnezyum_mg, 372.0), potasyum_mg = coalesce(potasyum_mg, 6300.0), cinko_mg = coalesce(cinko_mg, 6.11), fosfor_mg = coalesce(fosfor_mg, 548.0), bakir_mg = coalesce(bakir_mg, 0.459), manganez_mg = coalesce(manganez_mg, 1.338), selenyum_mcg = coalesce(selenyum_mcg, 32.3) where isletme_id is null and ad = 'MAYDANOZ (KURU)';

update malzemeler set kalori = coalesce(kalori, 93.0), protein = coalesce(protein, 5.6), yag = coalesce(yag, 2.12), karbonhidrat = coalesce(karbonhidrat, 17.31), sodyum_mg = coalesce(sodyum_mg, 9.0), lif_g = coalesce(lif_g, 11.0), seker_g = coalesce(seker_g, 6.3), doymus_yag_g = coalesce(doymus_yag_g, 0.336), vitamin_a_mcg = coalesce(vitamin_a_mcg, 1376.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.04), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.354), vitamin_b3_mg = coalesce(vitamin_b3_mg, 2.362), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.231), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.4), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 83.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 11.1), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 2.0), vitamin_k_mcg = coalesce(vitamin_k_mcg, 108.6), kalsiyum_mg = coalesce(kalsiyum_mg, 363.0), demir_mg = coalesce(demir_mg, 2.63), magnezyum_mg = coalesce(magnezyum_mg, 95.0), potasyum_mg = coalesce(potasyum_mg, 272.0), cinko_mg = coalesce(cinko_mg, 0.67), fosfor_mg = coalesce(fosfor_mg, 91.0), bakir_mg = coalesce(bakir_mg, 0.415), manganez_mg = coalesce(manganez_mg, 2.855), selenyum_mcg = coalesce(selenyum_mcg, 0.9) where isletme_id is null and ad = 'ASMA YAPRAĞI';

update malzemeler set kalori = coalesce(kalori, 23.0), protein = coalesce(protein, 2.36), yag = coalesce(yag, 0.86), karbonhidrat = coalesce(karbonhidrat, 4.89), sodyum_mg = coalesce(sodyum_mg, 2348.0), lif_g = coalesce(lif_g, 3.2), seker_g = coalesce(seker_g, 0.41), doymus_yag_g = coalesce(doymus_yag_g, 0.233), vitamin_a_mcg = coalesce(vitamin_a_mcg, 7.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.018), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.139), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.652), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.027), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.023), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 23.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 4.3), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.88), vitamin_k_mcg = coalesce(vitamin_k_mcg, 24.6), kalsiyum_mg = coalesce(kalsiyum_mg, 40.0), demir_mg = coalesce(demir_mg, 1.67), magnezyum_mg = coalesce(magnezyum_mg, 33.0), potasyum_mg = coalesce(potasyum_mg, 40.0), cinko_mg = coalesce(cinko_mg, 0.32), fosfor_mg = coalesce(fosfor_mg, 10.0), bakir_mg = coalesce(bakir_mg, 0.374), manganez_mg = coalesce(manganez_mg, 0.078), selenyum_mcg = coalesce(selenyum_mcg, 1.2) where isletme_id is null and ad = 'KEBERE';

update malzemeler set kalori = coalesce(kalori, 222.0), protein = coalesce(protein, 4.62), yag = coalesce(yag, 0.65), karbonhidrat = coalesce(karbonhidrat, 88.88), sodyum_mg = coalesce(sodyum_mg, 35.0), lif_g = coalesce(lif_g, 39.8), seker_g = coalesce(seker_g, 49.08), doymus_yag_g = coalesce(doymus_yag_g, 0.09), vitamin_a_mcg = coalesce(vitamin_a_mcg, 1.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.053), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.461), vitamin_b3_mg = coalesce(vitamin_b3_mg, 1.897), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.047), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.366), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 29.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 0.2), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.63), vitamin_k_mcg = coalesce(vitamin_k_mcg, 0.0), kalsiyum_mg = coalesce(kalsiyum_mg, 348.0), demir_mg = coalesce(demir_mg, 2.94), magnezyum_mg = coalesce(magnezyum_mg, 54.0), potasyum_mg = coalesce(potasyum_mg, 827.0), cinko_mg = coalesce(cinko_mg, 0.92), fosfor_mg = coalesce(fosfor_mg, 79.0), bakir_mg = coalesce(bakir_mg, 0.571), manganez_mg = coalesce(manganez_mg, 0.508), selenyum_mcg = coalesce(selenyum_mcg, 5.3) where isletme_id is null and ad = 'KEÇİBOYNUZU';

update malzemeler set kalori = coalesce(kalori, 47.0), protein = coalesce(protein, 0.43), yag = coalesce(yag, 0.2), karbonhidrat = coalesce(karbonhidrat, 12.14), sodyum_mg = coalesce(sodyum_mg, 1.0), lif_g = coalesce(lif_g, 1.7), doymus_yag_g = coalesce(doymus_yag_g, 0.04), vitamin_a_mcg = coalesce(vitamin_a_mcg, 76.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.019), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.024), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.18), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.1), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 14.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 1.0), kalsiyum_mg = coalesce(kalsiyum_mg, 16.0), demir_mg = coalesce(demir_mg, 0.28), magnezyum_mg = coalesce(magnezyum_mg, 13.0), potasyum_mg = coalesce(potasyum_mg, 266.0), cinko_mg = coalesce(cinko_mg, 0.05), fosfor_mg = coalesce(fosfor_mg, 27.0), bakir_mg = coalesce(bakir_mg, 0.04), manganez_mg = coalesce(manganez_mg, 0.148), selenyum_mcg = coalesce(selenyum_mcg, 0.6) where isletme_id is null and ad = 'YENİDÜNYA';

update malzemeler set protein = coalesce(protein, 1.640625), yag = coalesce(yag, 0.2375), karbonhidrat = coalesce(karbonhidrat, 4.723075), sodyum_mg = coalesce(sodyum_mg, 20.0), lif_g = coalesce(lif_g, 1.948), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 97), vitamin_c_mg = coalesce(vitamin_c_mg, 67.1), kalsiyum_mg = coalesce(kalsiyum_mg, 20.35), demir_mg = coalesce(demir_mg, 0.3338), magnezyum_mg = coalesce(magnezyum_mg, 14.2), potasyum_mg = coalesce(potasyum_mg, 274.4), cinko_mg = coalesce(cinko_mg, 0.2344), fosfor_mg = coalesce(fosfor_mg, 39.69), bakir_mg = coalesce(bakir_mg, 0.02423), manganez_mg = coalesce(manganez_mg, 0.141) where isletme_id is null and ad = 'KARNABAHAR';

update malzemeler set kalori = coalesce(kalori, 538.0), protein = coalesce(protein, 16.9), yag = coalesce(yag, 52.3), karbonhidrat = coalesce(karbonhidrat, 0.0), sodyum_mg = coalesce(sodyum_mg, 58.0), lif_g = coalesce(lif_g, 0.0), seker_g = coalesce(seker_g, 0.0), doymus_yag_g = coalesce(doymus_yag_g, 26.8), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.082), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.23), vitamin_b3_mg = coalesce(vitamin_b3_mg, 4.3), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.52), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.342), vitamin_c_mg = coalesce(vitamin_c_mg, 0.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), kalsiyum_mg = coalesce(kalsiyum_mg, 12.0), demir_mg = coalesce(demir_mg, 1.98), magnezyum_mg = coalesce(magnezyum_mg, 20.0), potasyum_mg = coalesce(potasyum_mg, 207.0), cinko_mg = coalesce(cinko_mg, 2.13), fosfor_mg = coalesce(fosfor_mg, 148.0), bakir_mg = coalesce(bakir_mg, 0.071), manganez_mg = coalesce(manganez_mg, 0.006), selenyum_mcg = coalesce(selenyum_mcg, 5.0) where isletme_id is null and ad = 'KUYRUKYAĞI';

update malzemeler set kalori = coalesce(kalori, 551.0), protein = coalesce(protein, 7.3), yag = coalesce(yag, 38.1), karbonhidrat = coalesce(karbonhidrat, 45.1), sodyum_mg = coalesce(sodyum_mg, 249.0), lif_g = coalesce(lif_g, 1.5), seker_g = coalesce(seker_g, 0.74), doymus_yag_g = coalesce(doymus_yag_g, 9.643), vitamin_a_mcg = coalesce(vitamin_a_mcg, 0.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.398), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.283), vitamin_b3_mg = coalesce(vitamin_b3_mg, 4.168), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.0), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.021), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 78.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.54), vitamin_k_mcg = coalesce(vitamin_k_mcg, 16.1), kalsiyum_mg = coalesce(kalsiyum_mg, 10.0), demir_mg = coalesce(demir_mg, 2.56), magnezyum_mg = coalesce(magnezyum_mg, 16.0), potasyum_mg = coalesce(potasyum_mg, 61.0), cinko_mg = coalesce(cinko_mg, 0.53), fosfor_mg = coalesce(fosfor_mg, 60.0), bakir_mg = coalesce(bakir_mg, 0.114), manganez_mg = coalesce(manganez_mg, 0.488), selenyum_mcg = coalesce(selenyum_mcg, 24.2) where isletme_id is null and ad = 'MİLFÖY HAMURU';

update malzemeler set kalori = coalesce(kalori, 299.0), protein = coalesce(protein, 7.1), yag = coalesce(yag, 6.0), karbonhidrat = coalesce(karbonhidrat, 52.6), sodyum_mg = coalesce(sodyum_mg, 483.0), lif_g = coalesce(lif_g, 1.9), seker_g = coalesce(seker_g, 0.18), doymus_yag_g = coalesce(doymus_yag_g, 1.47), vitamin_a_mcg = coalesce(vitamin_a_mcg, 0.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.541), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.341), vitamin_b3_mg = coalesce(vitamin_b3_mg, 4.073), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.302), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.03), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 88.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 0.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.08), vitamin_k_mcg = coalesce(vitamin_k_mcg, 2.5), kalsiyum_mg = coalesce(kalsiyum_mg, 11.0), demir_mg = coalesce(demir_mg, 3.21), magnezyum_mg = coalesce(magnezyum_mg, 15.0), potasyum_mg = coalesce(potasyum_mg, 74.0), cinko_mg = coalesce(cinko_mg, 0.49), fosfor_mg = coalesce(fosfor_mg, 75.0), bakir_mg = coalesce(bakir_mg, 0.101), manganez_mg = coalesce(manganez_mg, 0.476), selenyum_mcg = coalesce(selenyum_mcg, 23.3) where isletme_id is null and ad = 'KATMER';

update malzemeler set kalori = coalesce(kalori, 299.0), protein = coalesce(protein, 7.1), yag = coalesce(yag, 6.0), karbonhidrat = coalesce(karbonhidrat, 52.6), sodyum_mg = coalesce(sodyum_mg, 483.0), lif_g = coalesce(lif_g, 1.9), seker_g = coalesce(seker_g, 0.18), doymus_yag_g = coalesce(doymus_yag_g, 1.47), vitamin_a_mcg = coalesce(vitamin_a_mcg, 0.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.541), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.341), vitamin_b3_mg = coalesce(vitamin_b3_mg, 4.073), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.302), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.03), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 88.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 0.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.08), vitamin_k_mcg = coalesce(vitamin_k_mcg, 2.5), kalsiyum_mg = coalesce(kalsiyum_mg, 11.0), demir_mg = coalesce(demir_mg, 3.21), magnezyum_mg = coalesce(magnezyum_mg, 15.0), potasyum_mg = coalesce(potasyum_mg, 74.0), cinko_mg = coalesce(cinko_mg, 0.49), fosfor_mg = coalesce(fosfor_mg, 75.0), bakir_mg = coalesce(bakir_mg, 0.101), manganez_mg = coalesce(manganez_mg, 0.476), selenyum_mcg = coalesce(selenyum_mcg, 23.3) where isletme_id is null and ad = 'BÖREK (ISPANAKLI, DONDURULMUŞ)';

update malzemeler set kalori = coalesce(kalori, 299.0), protein = coalesce(protein, 7.1), yag = coalesce(yag, 6.0), karbonhidrat = coalesce(karbonhidrat, 52.6), sodyum_mg = coalesce(sodyum_mg, 483.0), lif_g = coalesce(lif_g, 1.9), seker_g = coalesce(seker_g, 0.18), doymus_yag_g = coalesce(doymus_yag_g, 1.47), vitamin_a_mcg = coalesce(vitamin_a_mcg, 0.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.541), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.341), vitamin_b3_mg = coalesce(vitamin_b3_mg, 4.073), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.302), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.03), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 88.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 0.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.08), vitamin_k_mcg = coalesce(vitamin_k_mcg, 2.5), kalsiyum_mg = coalesce(kalsiyum_mg, 11.0), demir_mg = coalesce(demir_mg, 3.21), magnezyum_mg = coalesce(magnezyum_mg, 15.0), potasyum_mg = coalesce(potasyum_mg, 74.0), cinko_mg = coalesce(cinko_mg, 0.49), fosfor_mg = coalesce(fosfor_mg, 75.0), bakir_mg = coalesce(bakir_mg, 0.101), manganez_mg = coalesce(manganez_mg, 0.476), selenyum_mcg = coalesce(selenyum_mcg, 23.3) where isletme_id is null and ad = 'BÖREK (PEYNİRLİ, DONDURULMUŞ)';

update malzemeler set kalori = coalesce(kalori, 291.0), protein = coalesce(protein, 9.8), yag = coalesce(yag, 1.5), karbonhidrat = coalesce(karbonhidrat, 57.9), sodyum_mg = coalesce(sodyum_mg, 572.0), lif_g = coalesce(lif_g, 1.8), doymus_yag_g = coalesce(doymus_yag_g, 0.263), vitamin_a_mcg = coalesce(vitamin_a_mcg, 4.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.519), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.378), vitamin_b3_mg = coalesce(vitamin_b3_mg, 5.424), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.025), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.03), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 86.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.02), vitamin_c_mg = coalesce(vitamin_c_mg, 0.0), kalsiyum_mg = coalesce(kalsiyum_mg, 47.0), demir_mg = coalesce(demir_mg, 3.36), magnezyum_mg = coalesce(magnezyum_mg, 20.0), potasyum_mg = coalesce(potasyum_mg, 82.0), cinko_mg = coalesce(cinko_mg, 0.71), fosfor_mg = coalesce(fosfor_mg, 81.0), bakir_mg = coalesce(bakir_mg, 0.147), manganez_mg = coalesce(manganez_mg, 0.638), selenyum_mcg = coalesce(selenyum_mcg, 28.2) where isletme_id is null and ad = 'GÜLLAÇ';

update malzemeler set kalori = coalesce(kalori, 57.0), protein = coalesce(protein, 0.0), yag = coalesce(yag, 0.0), karbonhidrat = coalesce(karbonhidrat, 14.55), sodyum_mg = coalesce(sodyum_mg, 9.0), lif_g = coalesce(lif_g, 0.1), seker_g = coalesce(seker_g, 14.11), doymus_yag_g = coalesce(doymus_yag_g, 0.0), vitamin_a_mcg = coalesce(vitamin_a_mcg, 0.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.225), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.354), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.142), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.023), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.035), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 1.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 26.5), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.0), vitamin_k_mcg = coalesce(vitamin_k_mcg, 0.2), kalsiyum_mg = coalesce(kalsiyum_mg, 7.0), demir_mg = coalesce(demir_mg, 0.13), magnezyum_mg = coalesce(magnezyum_mg, 6.0), potasyum_mg = coalesce(potasyum_mg, 33.0), cinko_mg = coalesce(cinko_mg, 0.03), fosfor_mg = coalesce(fosfor_mg, 6.0), bakir_mg = coalesce(bakir_mg, 0.022), manganez_mg = coalesce(manganez_mg, 0.2), selenyum_mcg = coalesce(selenyum_mcg, 0.1) where isletme_id is null and ad = 'HARDALİYE';

update malzemeler set kalori = coalesce(kalori, 2.0), protein = coalesce(protein, 0.12), yag = coalesce(yag, 0.2), karbonhidrat = coalesce(karbonhidrat, 0.0), sodyum_mg = coalesce(sodyum_mg, 27.0), kalsiyum_mg = coalesce(kalsiyum_mg, 5.0), demir_mg = coalesce(demir_mg, 0.03), magnezyum_mg = coalesce(magnezyum_mg, 0.0), potasyum_mg = coalesce(potasyum_mg, 44.0), cinko_mg = coalesce(cinko_mg, 0.05), fosfor_mg = coalesce(fosfor_mg, 0.0), bakir_mg = coalesce(bakir_mg, 0.007), manganez_mg = coalesce(manganez_mg, 0.004) where isletme_id is null and ad = 'IHLAMUR';

update malzemeler set kalori = coalesce(kalori, 360.0), protein = coalesce(protein, 0.94), yag = coalesce(yag, 0.0), karbonhidrat = coalesce(karbonhidrat, 89.11), sodyum_mg = coalesce(sodyum_mg, 428.0), lif_g = coalesce(lif_g, 0.0), seker_g = coalesce(seker_g, 85.19), doymus_yag_g = coalesce(doymus_yag_g, 0.0), vitamin_a_mcg = coalesce(vitamin_a_mcg, 0.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.0), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.0), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.0), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.0), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.0), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 0.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 0.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.0), vitamin_k_mcg = coalesce(vitamin_k_mcg, 0.0), kalsiyum_mg = coalesce(kalsiyum_mg, 0.0), demir_mg = coalesce(demir_mg, 0.04), magnezyum_mg = coalesce(magnezyum_mg, 0.0), potasyum_mg = coalesce(potasyum_mg, 4.0), cinko_mg = coalesce(cinko_mg, 0.01), fosfor_mg = coalesce(fosfor_mg, 0.0), bakir_mg = coalesce(bakir_mg, 0.0), manganez_mg = coalesce(manganez_mg, 0.0), selenyum_mcg = coalesce(selenyum_mcg, 0.0) where isletme_id is null and ad = 'TATLANDIRICI (SODYUM SİKLAMAT, SODYUM SAKARİN BAZLI, TABLET)';

update malzemeler set kalori = coalesce(kalori, 164.0), protein = coalesce(protein, 8.86), yag = coalesce(yag, 2.59), karbonhidrat = coalesce(karbonhidrat, 27.42), sodyum_mg = coalesce(sodyum_mg, 243.0), lif_g = coalesce(lif_g, 7.6), seker_g = coalesce(seker_g, 4.8), doymus_yag_g = coalesce(doymus_yag_g, 0.269), vitamin_a_mcg = coalesce(vitamin_a_mcg, 1.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.116), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.063), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.526), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.286), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.139), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 172.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 1.3), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.35), vitamin_k_mcg = coalesce(vitamin_k_mcg, 4.0), kalsiyum_mg = coalesce(kalsiyum_mg, 49.0), demir_mg = coalesce(demir_mg, 2.89), magnezyum_mg = coalesce(magnezyum_mg, 48.0), potasyum_mg = coalesce(potasyum_mg, 291.0), cinko_mg = coalesce(cinko_mg, 1.53), fosfor_mg = coalesce(fosfor_mg, 168.0), bakir_mg = coalesce(bakir_mg, 0.352), manganez_mg = coalesce(manganez_mg, 1.03), selenyum_mcg = coalesce(selenyum_mcg, 3.7) where isletme_id is null and ad = 'DENİZLİ LEBLEBİSİ';

update malzemeler set kalori = coalesce(kalori, 164.0), protein = coalesce(protein, 8.86), yag = coalesce(yag, 2.59), karbonhidrat = coalesce(karbonhidrat, 27.42), sodyum_mg = coalesce(sodyum_mg, 243.0), lif_g = coalesce(lif_g, 7.6), seker_g = coalesce(seker_g, 4.8), doymus_yag_g = coalesce(doymus_yag_g, 0.269), vitamin_a_mcg = coalesce(vitamin_a_mcg, 1.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.116), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.063), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.526), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.286), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.139), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 172.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 1.3), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.35), vitamin_k_mcg = coalesce(vitamin_k_mcg, 4.0), kalsiyum_mg = coalesce(kalsiyum_mg, 49.0), demir_mg = coalesce(demir_mg, 2.89), magnezyum_mg = coalesce(magnezyum_mg, 48.0), potasyum_mg = coalesce(potasyum_mg, 291.0), cinko_mg = coalesce(cinko_mg, 1.53), fosfor_mg = coalesce(fosfor_mg, 168.0), bakir_mg = coalesce(bakir_mg, 0.352), manganez_mg = coalesce(manganez_mg, 1.03), selenyum_mcg = coalesce(selenyum_mcg, 3.7) where isletme_id is null and ad = 'ÇORUM LEBLEBİSİ';

update malzemeler set kalori = coalesce(kalori, 164.0), protein = coalesce(protein, 8.86), yag = coalesce(yag, 2.59), karbonhidrat = coalesce(karbonhidrat, 27.42), sodyum_mg = coalesce(sodyum_mg, 243.0), lif_g = coalesce(lif_g, 7.6), seker_g = coalesce(seker_g, 4.8), doymus_yag_g = coalesce(doymus_yag_g, 0.269), vitamin_a_mcg = coalesce(vitamin_a_mcg, 1.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.116), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.063), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.526), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.286), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.139), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 172.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 1.3), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.35), vitamin_k_mcg = coalesce(vitamin_k_mcg, 4.0), kalsiyum_mg = coalesce(kalsiyum_mg, 49.0), demir_mg = coalesce(demir_mg, 2.89), magnezyum_mg = coalesce(magnezyum_mg, 48.0), potasyum_mg = coalesce(potasyum_mg, 291.0), cinko_mg = coalesce(cinko_mg, 1.53), fosfor_mg = coalesce(fosfor_mg, 168.0), bakir_mg = coalesce(bakir_mg, 0.352), manganez_mg = coalesce(manganez_mg, 1.03), selenyum_mcg = coalesce(selenyum_mcg, 3.7) where isletme_id is null and ad = 'TAVŞANLI LEBLEBİSİ';

update malzemeler set kalori = coalesce(kalori, 278.0), protein = coalesce(protein, 10.6), yag = coalesce(yag, 2.1), karbonhidrat = coalesce(karbonhidrat, 53.0), sodyum_mg = coalesce(sodyum_mg, 505.0), lif_g = coalesce(lif_g, 2.3), doymus_yag_g = coalesce(doymus_yag_g, 0.421), vitamin_a_mcg = coalesce(vitamin_a_mcg, 33.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.536), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.235), vitamin_b3_mg = coalesce(vitamin_b3_mg, 3.443), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.671), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.087), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 88.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.16), vitamin_c_mg = coalesce(vitamin_c_mg, 0.6), kalsiyum_mg = coalesce(kalsiyum_mg, 13.0), demir_mg = coalesce(demir_mg, 3.98), magnezyum_mg = coalesce(magnezyum_mg, 25.0), potasyum_mg = coalesce(potasyum_mg, 68.0), cinko_mg = coalesce(cinko_mg, 0.77), fosfor_mg = coalesce(fosfor_mg, 84.0), bakir_mg = coalesce(bakir_mg, 0.09), manganez_mg = coalesce(manganez_mg, 0.41), selenyum_mcg = coalesce(selenyum_mcg, 30.6) where isletme_id is null and ad = 'SİMİT';

update malzemeler set kalori = coalesce(kalori, 195.0), protein = coalesce(protein, 5.26), yag = coalesce(yag, 6.14), karbonhidrat = coalesce(karbonhidrat, 29.64), sodyum_mg = coalesce(sodyum_mg, 474.0), lif_g = coalesce(lif_g, 0.9), seker_g = coalesce(seker_g, 1.75), doymus_yag_g = coalesce(doymus_yag_g, 1.316), vitamin_a_mcg = coalesce(vitamin_a_mcg, 3.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.293), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.222), vitamin_b3_mg = coalesce(vitamin_b3_mg, 2.198), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.062), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 64.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.08), vitamin_c_mg = coalesce(vitamin_c_mg, 5.3), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.98), vitamin_k_mcg = coalesce(vitamin_k_mcg, 7.9), kalsiyum_mg = coalesce(kalsiyum_mg, 35.0), demir_mg = coalesce(demir_mg, 1.26), magnezyum_mg = coalesce(magnezyum_mg, 16.0), potasyum_mg = coalesce(potasyum_mg, 107.0), cinko_mg = coalesce(cinko_mg, 0.44), fosfor_mg = coalesce(fosfor_mg, 79.0), bakir_mg = coalesce(bakir_mg, 0.063), selenyum_mcg = coalesce(selenyum_mcg, 13.4) where isletme_id is null and ad = 'MANTI (ÇİĞ, KAYSERİ)';

update malzemeler set kalori = coalesce(kalori, 195.0), protein = coalesce(protein, 5.26), yag = coalesce(yag, 6.14), karbonhidrat = coalesce(karbonhidrat, 29.64), sodyum_mg = coalesce(sodyum_mg, 474.0), lif_g = coalesce(lif_g, 0.9), seker_g = coalesce(seker_g, 1.75), doymus_yag_g = coalesce(doymus_yag_g, 1.316), vitamin_a_mcg = coalesce(vitamin_a_mcg, 3.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.293), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.222), vitamin_b3_mg = coalesce(vitamin_b3_mg, 2.198), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.062), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 64.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.08), vitamin_c_mg = coalesce(vitamin_c_mg, 5.3), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 0.98), vitamin_k_mcg = coalesce(vitamin_k_mcg, 7.9), kalsiyum_mg = coalesce(kalsiyum_mg, 35.0), demir_mg = coalesce(demir_mg, 1.26), magnezyum_mg = coalesce(magnezyum_mg, 16.0), potasyum_mg = coalesce(potasyum_mg, 107.0), cinko_mg = coalesce(cinko_mg, 0.44), fosfor_mg = coalesce(fosfor_mg, 79.0), bakir_mg = coalesce(bakir_mg, 0.063), selenyum_mcg = coalesce(selenyum_mcg, 13.4) where isletme_id is null and ad = 'MANTI (ÇİĞ, SAFRANBOLU)';

update malzemeler set kalori = coalesce(kalori, 307.0), protein = coalesce(protein, 9.59), yag = coalesce(yag, 7.53), karbonhidrat = coalesce(karbonhidrat, 65.59), sodyum_mg = coalesce(sodyum_mg, 27.0), lif_g = coalesce(lif_g, 11.3), seker_g = coalesce(seker_g, 1.8), doymus_yag_g = coalesce(doymus_yag_g, 3.29), vitamin_a_mcg = coalesce(vitamin_a_mcg, 132.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.264), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.191), vitamin_b3_mg = coalesce(vitamin_b3_mg, 2.97), vitamin_b6_mg = coalesce(vitamin_b6_mg, 1.32), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 138.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 12.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 1.32), vitamin_k_mcg = coalesce(vitamin_k_mcg, 805.4), kalsiyum_mg = coalesce(kalsiyum_mg, 996.0), demir_mg = coalesce(demir_mg, 35.3), magnezyum_mg = coalesce(magnezyum_mg, 224.0), potasyum_mg = coalesce(potasyum_mg, 684.0), cinko_mg = coalesce(cinko_mg, 3.14), fosfor_mg = coalesce(fosfor_mg, 171.0), bakir_mg = coalesce(bakir_mg, 0.843), manganez_mg = coalesce(manganez_mg, 6.857), selenyum_mcg = coalesce(selenyum_mcg, 7.2) where isletme_id is null and ad = 'BAHARAT KARIŞIMI';

update malzemeler set glisemik_indeks = coalesce(glisemik_indeks, 36.2075), doymus_yag_g = coalesce(doymus_yag_g, 0.9306), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.0682), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.0857), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.7184), vitamin_b5_mg = coalesce(vitamin_b5_mg, 0.2074), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.184), vitamin_b7_mcg = coalesce(vitamin_b7_mcg, 4.329), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 31.501), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.0), vitamin_c_mg = coalesce(vitamin_c_mg, 4.2628), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.0), bakir_mg = coalesce(bakir_mg, 0.212), manganez_mg = coalesce(manganez_mg, 0.5177) where isletme_id is null and ad = 'MERSİN CEZERYESİ';

-- DOGRULAMA
select count(*) as toplam_malzeme from malzemeler where isletme_id is null;
