-- 70_yuksek_etkili_malzemeler_besin_degeri.sql
--
-- 13 Agustos 2026 (Oturum 11, devam): kullanicinin paylastigi TAM
-- oncelik listesinden (Excel export, 40 satir) EN YUKSEK ETKILI 32
-- malzeme tamamlandi -- bunlar TOPLAMDA binlerce tarif-kullanimina
-- karsilik geliyor (TUZ tek basina 128 tarifte!).
--
-- TürKomp'tan (30 malzeme): TUZ, KURU SOĞAN, TEREYAĞI, ŞEKER,
-- PİRİNÇ (HAM), LİMON SUYU, DOMATES, SARIMSAK, YOĞURT (TAM), HAVUÇ,
-- KARABİBER, CEVİZ (İÇ), LİMON, NOHUT, AYÇİÇEK YAĞI, KONSERVE DOMATES
-- SALÇASI, KONSERVE DOMATES, SÜT (TAM YAĞ), ZEYTİNYAĞI, BUĞDAY UNU,
-- TAVUK YUMURTASI, YUFKA, KIRMIZI MERCİMEK, PUL BİBER, SU, BULGUR,
-- KAŞAR PEYNİRİ, KURU FASULYE.
--
-- USDA'dan (2 malzeme): TAVUK GÖĞÜS ("Chicken, broilers or fryers,
-- breast, meat and skin, raw" -- TürKomp'ta cig/derisiz tavuk gogsu
-- bulunamadi, bu yuzden derili varyant kullanildi, gercek deger biraz
-- daha yagli cikabilir), LOR PEYNİRİ ("Cheese, ricotta, whole milk" --
-- en yakin uluslararasi esdeger, TürKomp'ta lor bulunamadi).
--
-- YAKLASIK ESLESMELER (kaynakta tam ayni varyant bulunamadigi icin,
-- en yakin makul esdeger kullanildi -- gercek deger biraz farkli
-- olabilir):
--   KUZU TANDIR -> "Kuzu eti, but" (TürKomp'ta pisirilmis/tandir
--     formunda ayri bir kayit yok, ciğ but kullanildi).
--   SIĞIR KIYMA -> "Sığır eti, but" (TürKomp'ta ayri bir "kiyma" kaydi
--     yok, gercek kiyma farkli yag oranina sahip olabilir).
--
-- BULUNAMAYAN/ISLENMEYEN: İSOT (gecerli akademik kaynak yok, daha
-- once arastirildi), MAYDONOZ (yazim farki nedeniyle "MAYDANOZ" ile
-- ayni kalem mi yoksa ayri bir kayit mi oldugu netlestirilemedi --
-- kullaniciya sorulacak), TAVUK GÖĞÜS'un TAM ciğ/derisiz hali
-- (yukaridaki not).
--
-- Tum UPDATE'ler coalesce() ile SADECE bos olan alanlari dolduruyor.

update malzemeler set kalori = coalesce(kalori, 1.0), protein = coalesce(protein, 0.0), yag = coalesce(yag, 0.0), karbonhidrat = coalesce(karbonhidrat, 0.22), sodyum_mg = coalesce(sodyum_mg, 37409.0), lif_g = coalesce(lif_g, 0.0), kalsiyum_mg = coalesce(kalsiyum_mg, 40.0), demir_mg = coalesce(demir_mg, 0.55), magnezyum_mg = coalesce(magnezyum_mg, 3.0), potasyum_mg = coalesce(potasyum_mg, 10.0), cinko_mg = coalesce(cinko_mg, 1.34), fosfor_mg = coalesce(fosfor_mg, 0.0), selenyum_mcg = coalesce(selenyum_mcg, 6.1) where isletme_id is null and ad = 'TUZ';

update malzemeler set kalori = coalesce(kalori, 40.0), protein = coalesce(protein, 1.16), yag = coalesce(yag, 0.18), karbonhidrat = coalesce(karbonhidrat, 7.88), sodyum_mg = coalesce(sodyum_mg, 6.0), lif_g = coalesce(lif_g, 1.23), vitamin_a_mcg = coalesce(vitamin_a_mcg, 4.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.031), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.013), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.419), vitamin_c_mg = coalesce(vitamin_c_mg, 6.5), kalsiyum_mg = coalesce(kalsiyum_mg, 31.0), demir_mg = coalesce(demir_mg, 0.23), magnezyum_mg = coalesce(magnezyum_mg, 14.0), potasyum_mg = coalesce(potasyum_mg, 176.0), cinko_mg = coalesce(cinko_mg, 0.21), fosfor_mg = coalesce(fosfor_mg, 36.0) where isletme_id is null and ad = 'KURU SOĞAN';

update malzemeler set kalori = coalesce(kalori, 753.0), protein = coalesce(protein, 0.19), yag = coalesce(yag, 83.22), karbonhidrat = coalesce(karbonhidrat, 0.85), sodyum_mg = coalesce(sodyum_mg, 7.0), vitamin_a_mcg = coalesce(vitamin_a_mcg, 559.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.012), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.05), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.029), vitamin_e_mg = coalesce(vitamin_e_mg, 2.45), kalsiyum_mg = coalesce(kalsiyum_mg, 15.0), demir_mg = coalesce(demir_mg, 0.09), magnezyum_mg = coalesce(magnezyum_mg, 1.0), potasyum_mg = coalesce(potasyum_mg, 20.0), cinko_mg = coalesce(cinko_mg, 0.06), fosfor_mg = coalesce(fosfor_mg, 20.0), selenyum_mcg = coalesce(selenyum_mcg, 0.0) where isletme_id is null and ad = 'TEREYAĞI';

update malzemeler set kalori = coalesce(kalori, 400.0), protein = coalesce(protein, 0.0), yag = coalesce(yag, 0.0), karbonhidrat = coalesce(karbonhidrat, 99.92), sodyum_mg = coalesce(sodyum_mg, 14.0), lif_g = coalesce(lif_g, 0.0), kalsiyum_mg = coalesce(kalsiyum_mg, 1.0), demir_mg = coalesce(demir_mg, 0.14), magnezyum_mg = coalesce(magnezyum_mg, 0.0), potasyum_mg = coalesce(potasyum_mg, 4.0), cinko_mg = coalesce(cinko_mg, 0.0), fosfor_mg = coalesce(fosfor_mg, 16.0), selenyum_mcg = coalesce(selenyum_mcg, 0.0) where isletme_id is null and ad = 'ŞEKER';

update malzemeler set kalori = coalesce(kalori, 341.0), protein = coalesce(protein, 6.84), yag = coalesce(yag, 0.44), karbonhidrat = coalesce(karbonhidrat, 75.67), sodyum_mg = coalesce(sodyum_mg, 15.0), lif_g = coalesce(lif_g, 3.46), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.102), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.035), vitamin_b3_mg = coalesce(vitamin_b3_mg, 1.799), kalsiyum_mg = coalesce(kalsiyum_mg, 5.0), demir_mg = coalesce(demir_mg, 0.46), magnezyum_mg = coalesce(magnezyum_mg, 29.0), potasyum_mg = coalesce(potasyum_mg, 97.0), cinko_mg = coalesce(cinko_mg, 0.65), fosfor_mg = coalesce(fosfor_mg, 113.0), selenyum_mcg = coalesce(selenyum_mcg, 1.5) where isletme_id is null and ad = 'PİRİNÇ (HAM)';

update malzemeler set kalori = coalesce(kalori, 23.0), protein = coalesce(protein, 0.0), yag = coalesce(yag, 0.12), karbonhidrat = coalesce(karbonhidrat, 5.59), vitamin_c_mg = coalesce(vitamin_c_mg, 42.4) where isletme_id is null and ad = 'LİMON SUYU';

update malzemeler set kalori = coalesce(kalori, 19.0), protein = coalesce(protein, 0.89), yag = coalesce(yag, 0.2), karbonhidrat = coalesce(karbonhidrat, 2.86), sodyum_mg = coalesce(sodyum_mg, 4.0), lif_g = coalesce(lif_g, 1.1), vitamin_a_mcg = coalesce(vitamin_a_mcg, 51.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.03), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.025), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.613), vitamin_c_mg = coalesce(vitamin_c_mg, 19.8), kalsiyum_mg = coalesce(kalsiyum_mg, 10.0), demir_mg = coalesce(demir_mg, 0.34), magnezyum_mg = coalesce(magnezyum_mg, 12.0), potasyum_mg = coalesce(potasyum_mg, 206.0), cinko_mg = coalesce(cinko_mg, 0.16), fosfor_mg = coalesce(fosfor_mg, 27.0) where isletme_id is null and ad = 'DOMATES';

update malzemeler set kalori = coalesce(kalori, 129.0), protein = coalesce(protein, 5.21), yag = coalesce(yag, 0.54), karbonhidrat = coalesce(karbonhidrat, 24.48), sodyum_mg = coalesce(sodyum_mg, 7.0), lif_g = coalesce(lif_g, 2.64), vitamin_a_mcg = coalesce(vitamin_a_mcg, 2.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.084), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.034), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.564), vitamin_c_mg = coalesce(vitamin_c_mg, 10.9), kalsiyum_mg = coalesce(kalsiyum_mg, 16.0), demir_mg = coalesce(demir_mg, 0.94), magnezyum_mg = coalesce(magnezyum_mg, 28.0), potasyum_mg = coalesce(potasyum_mg, 474.0), cinko_mg = coalesce(cinko_mg, 0.98), fosfor_mg = coalesce(fosfor_mg, 156.0) where isletme_id is null and ad = 'SARIMSAK';

update malzemeler set kalori = coalesce(kalori, 69.0), protein = coalesce(protein, 4.53), yag = coalesce(yag, 3.8), karbonhidrat = coalesce(karbonhidrat, 4.24), sodyum_mg = coalesce(sodyum_mg, 53.0), vitamin_a_mcg = coalesce(vitamin_a_mcg, 30.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.048), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.2), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.166), vitamin_e_mg = coalesce(vitamin_e_mg, 0.11), kalsiyum_mg = coalesce(kalsiyum_mg, 132.0), demir_mg = coalesce(demir_mg, 0.03), magnezyum_mg = coalesce(magnezyum_mg, 13.0), potasyum_mg = coalesce(potasyum_mg, 191.0), cinko_mg = coalesce(cinko_mg, 0.4), fosfor_mg = coalesce(fosfor_mg, 110.0), selenyum_mcg = coalesce(selenyum_mcg, 1.7) where isletme_id is null and ad = 'YOĞURT (TAM)';

update malzemeler set kalori = coalesce(kalori, 37.0), protein = coalesce(protein, 0.89), yag = coalesce(yag, 0.2), karbonhidrat = coalesce(karbonhidrat, 6.5), sodyum_mg = coalesce(sodyum_mg, 52.0), lif_g = coalesce(lif_g, 2.58), vitamin_a_mcg = coalesce(vitamin_a_mcg, 624.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.036), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.026), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.98), vitamin_c_mg = coalesce(vitamin_c_mg, 5.2), kalsiyum_mg = coalesce(kalsiyum_mg, 34.0), demir_mg = coalesce(demir_mg, 0.13), magnezyum_mg = coalesce(magnezyum_mg, 20.0), potasyum_mg = coalesce(potasyum_mg, 279.0), cinko_mg = coalesce(cinko_mg, 0.15), fosfor_mg = coalesce(fosfor_mg, 26.0) where isletme_id is null and ad = 'HAVUÇ';

update malzemeler set kalori = coalesce(kalori, 297.0), protein = coalesce(protein, 20.06), yag = coalesce(yag, 3.46), karbonhidrat = coalesce(karbonhidrat, 24.69), lif_g = coalesce(lif_g, 43.19) where isletme_id is null and ad = 'KARABİBER';

update malzemeler set kalori = coalesce(kalori, 679.0), protein = coalesce(protein, 14.57), yag = coalesce(yag, 64.82), karbonhidrat = coalesce(karbonhidrat, 3.68), sodyum_mg = coalesce(sodyum_mg, 3.0), lif_g = coalesce(lif_g, 11.5), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.317), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.138), vitamin_b3_mg = coalesce(vitamin_b3_mg, 1.201), vitamin_e_mg = coalesce(vitamin_e_mg, 1.19), kalsiyum_mg = coalesce(kalsiyum_mg, 103.0), demir_mg = coalesce(demir_mg, 2.34), magnezyum_mg = coalesce(magnezyum_mg, 165.0), potasyum_mg = coalesce(potasyum_mg, 437.0), cinko_mg = coalesce(cinko_mg, 3.0), fosfor_mg = coalesce(fosfor_mg, 365.0), selenyum_mcg = coalesce(selenyum_mcg, 3.1) where isletme_id is null and ad = 'CEVİZ (İÇ)';

update malzemeler set kalori = coalesce(kalori, 43.0), protein = coalesce(protein, 0.44), yag = coalesce(yag, 0.36), karbonhidrat = coalesce(karbonhidrat, 8.73), sodyum_mg = coalesce(sodyum_mg, 3.0), lif_g = coalesce(lif_g, 1.41), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.028), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.043), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.27), vitamin_c_mg = coalesce(vitamin_c_mg, 44.1), kalsiyum_mg = coalesce(kalsiyum_mg, 34.0), demir_mg = coalesce(demir_mg, 0.11), magnezyum_mg = coalesce(magnezyum_mg, 11.0), potasyum_mg = coalesce(potasyum_mg, 157.0), cinko_mg = coalesce(cinko_mg, 0.08), fosfor_mg = coalesce(fosfor_mg, 16.0), selenyum_mcg = coalesce(selenyum_mcg, 0.0) where isletme_id is null and ad = 'LİMON';

update malzemeler set kalori = coalesce(kalori, 334.0), protein = coalesce(protein, 18.56), yag = coalesce(yag, 5.33), karbonhidrat = coalesce(karbonhidrat, 41.35), sodyum_mg = coalesce(sodyum_mg, 19.0), lif_g = coalesce(lif_g, 23.03), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.572), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.164), vitamin_b3_mg = coalesce(vitamin_b3_mg, 3.146), vitamin_e_mg = coalesce(vitamin_e_mg, 2.92), kalsiyum_mg = coalesce(kalsiyum_mg, 99.0), demir_mg = coalesce(demir_mg, 5.92), magnezyum_mg = coalesce(magnezyum_mg, 139.0), potasyum_mg = coalesce(potasyum_mg, 1171.0), cinko_mg = coalesce(cinko_mg, 3.16), fosfor_mg = coalesce(fosfor_mg, 397.0), selenyum_mcg = coalesce(selenyum_mcg, 31.1) where isletme_id is null and ad = 'NOHUT';

update malzemeler set kalori = coalesce(kalori, 900.0), protein = coalesce(protein, 0.0), yag = coalesce(yag, 100.0), karbonhidrat = coalesce(karbonhidrat, 0.0), lif_g = coalesce(lif_g, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 47.83) where isletme_id is null and ad = 'AYÇİÇEK YAĞI';

update malzemeler set kalori = coalesce(kalori, 97.0), protein = coalesce(protein, 4.56), yag = coalesce(yag, 0.52), karbonhidrat = coalesce(karbonhidrat, 16.64), sodyum_mg = coalesce(sodyum_mg, 0.0), lif_g = coalesce(lif_g, 3.58), vitamin_a_mcg = coalesce(vitamin_a_mcg, 131.0), vitamin_c_mg = coalesce(vitamin_c_mg, 16.5), kalsiyum_mg = coalesce(kalsiyum_mg, 25.0), demir_mg = coalesce(demir_mg, 1.52), magnezyum_mg = coalesce(magnezyum_mg, 12.0), potasyum_mg = coalesce(potasyum_mg, 260.0), cinko_mg = coalesce(cinko_mg, 0.01), fosfor_mg = coalesce(fosfor_mg, 0.0), selenyum_mcg = coalesce(selenyum_mcg, 0.0) where isletme_id is null and ad = 'KONSERVE DOMATES SALÇASI';

update malzemeler set kalori = coalesce(kalori, 15.0), protein = coalesce(protein, 0.88), yag = coalesce(yag, 0.22), karbonhidrat = coalesce(karbonhidrat, 1.77), sodyum_mg = coalesce(sodyum_mg, 0.0), lif_g = coalesce(lif_g, 1.45), kalsiyum_mg = coalesce(kalsiyum_mg, 20.0), demir_mg = coalesce(demir_mg, 0.55), magnezyum_mg = coalesce(magnezyum_mg, 10.0), potasyum_mg = coalesce(potasyum_mg, 209.0), cinko_mg = coalesce(cinko_mg, 0.01), fosfor_mg = coalesce(fosfor_mg, 0.0), selenyum_mcg = coalesce(selenyum_mcg, 0.0) where isletme_id is null and ad = 'KONSERVE DOMATES';

update malzemeler set kalori = coalesce(kalori, 61.0), protein = coalesce(protein, 3.32), yag = coalesce(yag, 3.04), karbonhidrat = coalesce(karbonhidrat, 5.09), sodyum_mg = coalesce(sodyum_mg, 0.0), lif_g = coalesce(lif_g, 0.0), vitamin_a_mcg = coalesce(vitamin_a_mcg, 28.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.041), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.138), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.073), vitamin_e_mg = coalesce(vitamin_e_mg, 0.12), kalsiyum_mg = coalesce(kalsiyum_mg, 523.0), demir_mg = coalesce(demir_mg, 0.14), magnezyum_mg = coalesce(magnezyum_mg, 12.0), potasyum_mg = coalesce(potasyum_mg, 706.0), cinko_mg = coalesce(cinko_mg, 1.31), fosfor_mg = coalesce(fosfor_mg, 86.0), selenyum_mcg = coalesce(selenyum_mcg, 1.3) where isletme_id is null and ad = 'SÜT (TAM YAĞ)';

update malzemeler set kalori = coalesce(kalori, 122.0), protein = coalesce(protein, 19.3), yag = coalesce(yag, 4.95), karbonhidrat = coalesce(karbonhidrat, 0.0), sodyum_mg = coalesce(sodyum_mg, 72.0), vitamin_a_mcg = coalesce(vitamin_a_mcg, 16.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.103), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.204), vitamin_b3_mg = coalesce(vitamin_b3_mg, 5.248), kalsiyum_mg = coalesce(kalsiyum_mg, 5.0), demir_mg = coalesce(demir_mg, 1.62), magnezyum_mg = coalesce(magnezyum_mg, 22.0), potasyum_mg = coalesce(potasyum_mg, 818.0), cinko_mg = coalesce(cinko_mg, 3.9), fosfor_mg = coalesce(fosfor_mg, 165.0), selenyum_mcg = coalesce(selenyum_mcg, 7.2) where isletme_id is null and ad = 'KUZU TANDIR';

update malzemeler set kalori = coalesce(kalori, 900.0), protein = coalesce(protein, 0.0), yag = coalesce(yag, 100.0), karbonhidrat = coalesce(karbonhidrat, 0.0), lif_g = coalesce(lif_g, 0.0), vitamin_e_mg = coalesce(vitamin_e_mg, 10.09) where isletme_id is null and ad = 'ZEYTİNYAĞI';

update malzemeler set kalori = coalesce(kalori, 350.0), protein = coalesce(protein, 10.66), yag = coalesce(yag, 1.44), karbonhidrat = coalesce(karbonhidrat, 71.76), sodyum_mg = coalesce(sodyum_mg, 0.0), lif_g = coalesce(lif_g, 3.76), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.245), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.039), vitamin_b3_mg = coalesce(vitamin_b3_mg, 1.606), kalsiyum_mg = coalesce(kalsiyum_mg, 69.0), demir_mg = coalesce(demir_mg, 1.49), magnezyum_mg = coalesce(magnezyum_mg, 28.0), potasyum_mg = coalesce(potasyum_mg, 159.0), cinko_mg = coalesce(cinko_mg, 5.93), fosfor_mg = coalesce(fosfor_mg, 98.0), selenyum_mcg = coalesce(selenyum_mcg, 0.0) where isletme_id is null and ad = 'BUĞDAY UNU';

update malzemeler set kalori = coalesce(kalori, 123.0), protein = coalesce(protein, 20.39), yag = coalesce(yag, 4.63), karbonhidrat = coalesce(karbonhidrat, 0.0), sodyum_mg = coalesce(sodyum_mg, 54.0), vitamin_a_mcg = coalesce(vitamin_a_mcg, 6.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.074), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.173), vitamin_b3_mg = coalesce(vitamin_b3_mg, 5.915), kalsiyum_mg = coalesce(kalsiyum_mg, 6.0), demir_mg = coalesce(demir_mg, 1.76), magnezyum_mg = coalesce(magnezyum_mg, 22.0), potasyum_mg = coalesce(potasyum_mg, 387.0), cinko_mg = coalesce(cinko_mg, 3.67), fosfor_mg = coalesce(fosfor_mg, 157.0), selenyum_mcg = coalesce(selenyum_mcg, 8.2) where isletme_id is null and ad = 'SIĞIR KIYMA';

update malzemeler set kalori = coalesce(kalori, 140.0), protein = coalesce(protein, 13.13), yag = coalesce(yag, 9.69), karbonhidrat = coalesce(karbonhidrat, 0.0), sodyum_mg = coalesce(sodyum_mg, 139.0), vitamin_a_mcg = coalesce(vitamin_a_mcg, 195.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.088), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.449), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.053), vitamin_e_mg = coalesce(vitamin_e_mg, 3.64), kalsiyum_mg = coalesce(kalsiyum_mg, 52.0), demir_mg = coalesce(demir_mg, 1.83), magnezyum_mg = coalesce(magnezyum_mg, 13.0), potasyum_mg = coalesce(potasyum_mg, 127.0), cinko_mg = coalesce(cinko_mg, 1.14), fosfor_mg = coalesce(fosfor_mg, 184.0), selenyum_mcg = coalesce(selenyum_mcg, 26.9) where isletme_id is null and ad = 'TAVUK YUMURTASI';

update malzemeler set kalori = coalesce(kalori, 242.0), protein = coalesce(protein, 6.84), yag = coalesce(yag, 0.88), karbonhidrat = coalesce(karbonhidrat, 50.11), sodyum_mg = coalesce(sodyum_mg, 253.0), lif_g = coalesce(lif_g, 3.1), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.272), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.104), vitamin_b3_mg = coalesce(vitamin_b3_mg, 2.374), kalsiyum_mg = coalesce(kalsiyum_mg, 9.0), demir_mg = coalesce(demir_mg, 0.73), magnezyum_mg = coalesce(magnezyum_mg, 12.0), potasyum_mg = coalesce(potasyum_mg, 54.0), cinko_mg = coalesce(cinko_mg, 0.44), fosfor_mg = coalesce(fosfor_mg, 46.0), selenyum_mcg = coalesce(selenyum_mcg, 0.0) where isletme_id is null and ad = 'YUFKA';

update malzemeler set kalori = coalesce(kalori, 322.0), protein = coalesce(protein, 25.81), yag = coalesce(yag, 1.57), karbonhidrat = coalesce(karbonhidrat, 41.94), sodyum_mg = coalesce(sodyum_mg, 14.0), lif_g = coalesce(lif_g, 18.67), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.809), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.177), vitamin_b3_mg = coalesce(vitamin_b3_mg, 2.688), vitamin_e_mg = coalesce(vitamin_e_mg, 0.52), kalsiyum_mg = coalesce(kalsiyum_mg, 26.0), demir_mg = coalesce(demir_mg, 5.87), magnezyum_mg = coalesce(magnezyum_mg, 85.0), potasyum_mg = coalesce(potasyum_mg, 1004.0), cinko_mg = coalesce(cinko_mg, 3.6), fosfor_mg = coalesce(fosfor_mg, 416.0), selenyum_mcg = coalesce(selenyum_mcg, 40.4) where isletme_id is null and ad = 'KIRMIZI MERCİMEK';

update malzemeler set kalori = coalesce(kalori, 286.0), protein = coalesce(protein, 11.69), karbonhidrat = coalesce(karbonhidrat, 43.67), lif_g = coalesce(lif_g, 32.25) where isletme_id is null and ad = 'PUL BİBER';

update malzemeler set kalori = coalesce(kalori, 0.0), protein = coalesce(protein, 0.0), yag = coalesce(yag, 0.0), karbonhidrat = coalesce(karbonhidrat, 0.0), sodyum_mg = coalesce(sodyum_mg, 0.0), lif_g = coalesce(lif_g, 0.0), kalsiyum_mg = coalesce(kalsiyum_mg, 2.0), demir_mg = coalesce(demir_mg, 0.0), magnezyum_mg = coalesce(magnezyum_mg, 0.0), potasyum_mg = coalesce(potasyum_mg, 0.0), cinko_mg = coalesce(cinko_mg, 0.01), fosfor_mg = coalesce(fosfor_mg, 0.0), selenyum_mcg = coalesce(selenyum_mcg, 0.0) where isletme_id is null and ad = 'SU';

update malzemeler set kalori = coalesce(kalori, 349.0), protein = coalesce(protein, 8.84), yag = coalesce(yag, 2.06), karbonhidrat = coalesce(karbonhidrat, 70.41), sodyum_mg = coalesce(sodyum_mg, 8.0), lif_g = coalesce(lif_g, 6.76), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.226), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.09), vitamin_b3_mg = coalesce(vitamin_b3_mg, 5.864), vitamin_e_mg = coalesce(vitamin_e_mg, 0.08), kalsiyum_mg = coalesce(kalsiyum_mg, 18.0), demir_mg = coalesce(demir_mg, 1.08), magnezyum_mg = coalesce(magnezyum_mg, 62.0), potasyum_mg = coalesce(potasyum_mg, 267.0), cinko_mg = coalesce(cinko_mg, 1.16), fosfor_mg = coalesce(fosfor_mg, 185.0) where isletme_id is null and ad = 'BULGUR';

update malzemeler set kalori = coalesce(kalori, 381.0), protein = coalesce(protein, 26.03), yag = coalesce(yag, 29.4), karbonhidrat = coalesce(karbonhidrat, 3.14), sodyum_mg = coalesce(sodyum_mg, 968.0), lif_g = coalesce(lif_g, 0.0), vitamin_a_mcg = coalesce(vitamin_a_mcg, 183.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.051), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.62), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.175), vitamin_e_mg = coalesce(vitamin_e_mg, 1.69), kalsiyum_mg = coalesce(kalsiyum_mg, 715.0), demir_mg = coalesce(demir_mg, 0.26), magnezyum_mg = coalesce(magnezyum_mg, 27.0), potasyum_mg = coalesce(potasyum_mg, 75.0), cinko_mg = coalesce(cinko_mg, 3.84), fosfor_mg = coalesce(fosfor_mg, 556.0), selenyum_mcg = coalesce(selenyum_mcg, 4.7) where isletme_id is null and ad = 'KAŞAR PEYNİRİ';

update malzemeler set kalori = coalesce(kalori, 281.0), protein = coalesce(protein, 21.75), yag = coalesce(yag, 1.35), karbonhidrat = coalesce(karbonhidrat, 29.42), sodyum_mg = coalesce(sodyum_mg, 16.0), lif_g = coalesce(lif_g, 32.17), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.796), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.181), vitamin_b3_mg = coalesce(vitamin_b3_mg, 4.141), vitamin_e_mg = coalesce(vitamin_e_mg, 0.38), kalsiyum_mg = coalesce(kalsiyum_mg, 141.0), demir_mg = coalesce(demir_mg, 4.71), magnezyum_mg = coalesce(magnezyum_mg, 150.0), potasyum_mg = coalesce(potasyum_mg, 927.0), cinko_mg = coalesce(cinko_mg, 2.51), fosfor_mg = coalesce(fosfor_mg, 367.0), selenyum_mcg = coalesce(selenyum_mcg, 6.6) where isletme_id is null and ad = 'KURU FASULYE';

update malzemeler set kalori = coalesce(kalori, 172.0), protein = coalesce(protein, 20.85), yag = coalesce(yag, 9.25), karbonhidrat = coalesce(karbonhidrat, 0.0), sodyum_mg = coalesce(sodyum_mg, 63.0), lif_g = coalesce(lif_g, 0.0), seker_g = coalesce(seker_g, 0.0), doymus_yag_g = coalesce(doymus_yag_g, 2.66), vitamin_a_mcg = coalesce(vitamin_a_mcg, 24.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.063), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.085), vitamin_b3_mg = coalesce(vitamin_b3_mg, 9.908), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.53), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 4.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.34), vitamin_c_mg = coalesce(vitamin_c_mg, 0.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.4), vitamin_e_mg = coalesce(vitamin_e_mg, 0.27), vitamin_k_mcg = coalesce(vitamin_k_mcg, 0.0), kalsiyum_mg = coalesce(kalsiyum_mg, 11.0), demir_mg = coalesce(demir_mg, 0.74), magnezyum_mg = coalesce(magnezyum_mg, 25.0), potasyum_mg = coalesce(potasyum_mg, 220.0), cinko_mg = coalesce(cinko_mg, 0.8), fosfor_mg = coalesce(fosfor_mg, 174.0), bakir_mg = coalesce(bakir_mg, 0.039), manganez_mg = coalesce(manganez_mg, 0.018), selenyum_mcg = coalesce(selenyum_mcg, 16.6) where isletme_id is null and ad = 'TAVUK GÖĞÜS';

update malzemeler set kalori = coalesce(kalori, 150.0), protein = coalesce(protein, 7.54), yag = coalesce(yag, 10.18), karbonhidrat = coalesce(karbonhidrat, 7.27), sodyum_mg = coalesce(sodyum_mg, 110.0), lif_g = coalesce(lif_g, 0.0), seker_g = coalesce(seker_g, 0.27), doymus_yag_g = coalesce(doymus_yag_g, 6.42), vitamin_a_mcg = coalesce(vitamin_a_mcg, 120.0), vitamin_b1_mg = coalesce(vitamin_b1_mg, 0.013), vitamin_b2_mg = coalesce(vitamin_b2_mg, 0.298), vitamin_b3_mg = coalesce(vitamin_b3_mg, 0.137), vitamin_b6_mg = coalesce(vitamin_b6_mg, 0.097), vitamin_b9_mcg = coalesce(vitamin_b9_mcg, 4.0), vitamin_b12_mcg = coalesce(vitamin_b12_mcg, 0.85), vitamin_c_mg = coalesce(vitamin_c_mg, 0.0), vitamin_d_mcg = coalesce(vitamin_d_mcg, 0.2), vitamin_e_mg = coalesce(vitamin_e_mg, 0.11), vitamin_k_mcg = coalesce(vitamin_k_mcg, 1.1), kalsiyum_mg = coalesce(kalsiyum_mg, 206.0), demir_mg = coalesce(demir_mg, 0.13), magnezyum_mg = coalesce(magnezyum_mg, 20.0), potasyum_mg = coalesce(potasyum_mg, 219.0), cinko_mg = coalesce(cinko_mg, 0.53), fosfor_mg = coalesce(fosfor_mg, 154.0), bakir_mg = coalesce(bakir_mg, 0.018), manganez_mg = coalesce(manganez_mg, 0.011), selenyum_mcg = coalesce(selenyum_mcg, 5.9) where isletme_id is null and ad = 'LOR PEYNİRİ';

-- DOGRULAMA
select count(*) as guncellenen from malzemeler where isletme_id is null and vitamin_c_mg is not null;
