-- SAGLAM DENETIM (siralama/collation sorunundan ETKILENMEZ):
-- Parti 1-6'daki (336 deneme) her tarif icin ÜÇ sayiyi karsilastirir:
-- (a) benim BEKLEDIGIM malzeme sayisi, (b) DB'deki GERCEK malzeme
-- sayisi, (c) TAM ESLESEN (ayni malzeme + ayni miktar) cift sayisi.
-- Ucu de esitse tarif TAMAMEN dogru eklenmis demektir. Herhangi biri
-- farkliysa, o tarif ONCEDEN VAR OLAN baska bir kayitla carpismis
-- demektir (adi ayni, icerigi farkli).
with beklenen(ad, malzeme_ad, miktar) as (
  values
    ('Bursa İskender Kebabı', 'DÖNER (ET, PİŞMİŞ, BURSA)', 120),
    ('Bursa İskender Kebabı', 'PİDE', 70),
    ('Bursa İskender Kebabı', 'TEREYAĞI', 12),
    ('Bursa İskender Kebabı', 'YOĞURT (TAM)', 50),
    ('Bursa İskender Kebabı', 'DOMATES', 40),
    ('Bursa İskender Kebabı', 'TUZ', 0.8),
    ('İnegöl Köfte', 'DANA KIYMA', 90),
    ('İnegöl Köfte', 'KURU SOĞAN', 15),
    ('İnegöl Köfte', 'EKMEKLİK UN', 4),
    ('İnegöl Köfte', 'TUZ', 1.2),
    ('İnegöl Köfte', 'KARABİBER', 0.3),
    ('İnegöl Köfte', 'KİMYON', 0.5),
    ('Bursa Kestaneli Kaz Dolması', 'KAZ ETİ (BÜTÜN, DERİLİ)', 180),
    ('Bursa Kestaneli Kaz Dolması', 'PİRİNÇ (HAM)', 30),
    ('Bursa Kestaneli Kaz Dolması', 'KESTANE', 40),
    ('Bursa Kestaneli Kaz Dolması', 'KURU SOĞAN', 15),
    ('Bursa Kestaneli Kaz Dolması', 'KUŞ ÜZÜMÜ', 6),
    ('Bursa Kestaneli Kaz Dolması', 'TUZ', 1.5),
    ('Bursa Kestaneli Kaz Dolması', 'KARABİBER', 0.3),
    ('Bursa Kestaneli Kaz Dolması', 'YENİBAHAR', 0.3),
    ('İstanbul Usulü Karnıyarık', 'PATLICAN', 120),
    ('İstanbul Usulü Karnıyarık', 'DANA KIYMA', 70),
    ('İstanbul Usulü Karnıyarık', 'KURU SOĞAN', 20),
    ('İstanbul Usulü Karnıyarık', 'DOMATES', 40),
    ('İstanbul Usulü Karnıyarık', 'YEŞİL BİBER', 15),
    ('İstanbul Usulü Karnıyarık', 'SARIMSAK', 1.5),
    ('İstanbul Usulü Karnıyarık', 'TUZ', 1.2),
    ('İstanbul Usulü Karnıyarık', 'KARABİBER', 0.3),
    ('İstanbul Usulü Karnıyarık', 'ZEYTİNYAĞI', 6),
    ('Bandırma Mantısı', 'EKMEKLİK UN', 70),
    ('Bandırma Mantısı', 'DANA KIYMA', 50),
    ('Bandırma Mantısı', 'KURU SOĞAN', 15),
    ('Bandırma Mantısı', 'YOĞURT (TAM)', 60),
    ('Bandırma Mantısı', 'SARIMSAK', 2),
    ('Bandırma Mantısı', 'TEREYAĞI', 8),
    ('Bandırma Mantısı', 'PUL BİBER', 0.8),
    ('Bandırma Mantısı', 'KURU NANE', 0.5),
    ('Bandırma Mantısı', 'TUZ', 1.2),
    ('Marmara Usulü Midye Tava', 'MİDYE', 120),
    ('Marmara Usulü Midye Tava', 'EKMEKLİK UN', 25),
    ('Marmara Usulü Midye Tava', 'KARBONAT (YEM. SODA)', 0.5),
    ('Marmara Usulü Midye Tava', 'MISIR YAĞI', 30),
    ('Marmara Usulü Midye Tava', 'CEVİZ (İÇ)', 10),
    ('Marmara Usulü Midye Tava', 'SARIMSAK', 2),
    ('Marmara Usulü Midye Tava', 'EKMEK (BEYAZ)', 8),
    ('Marmara Usulü Midye Tava', 'LİMON SUYU', 3),
    ('Marmara Usulü Midye Tava', 'TUZ', 1),
    ('Kırklareli Rokalı Beyaz Peynir Salatası', 'ROKA', 40),
    ('Kırklareli Rokalı Beyaz Peynir Salatası', 'EDİRNE BEYAZ PEYNİRİ', 30),
    ('Kırklareli Rokalı Beyaz Peynir Salatası', 'CEVİZ (İÇ)', 10),
    ('Kırklareli Rokalı Beyaz Peynir Salatası', 'ZEYTİNYAĞI', 4),
    ('Kırklareli Rokalı Beyaz Peynir Salatası', 'LİMON SUYU', 2.5),
    ('Kırklareli Rokalı Beyaz Peynir Salatası', 'TUZ', 0.5),
    ('Marmara Kestaneli Muhallebi', 'SÜT (TAM YAĞ)', 150),
    ('Marmara Kestaneli Muhallebi', 'KESTANE', 40),
    ('Marmara Kestaneli Muhallebi', 'ŞEKER', 25),
    ('Marmara Kestaneli Muhallebi', 'MISIR NİŞASTASI', 8),
    ('Marmara Kestaneli Muhallebi', 'CEVİZ (İÇ)', 6),
    ('İzmir Köfte (Fırında)', 'DANA KIYMA', 90),
    ('İzmir Köfte (Fırında)', 'PATATES', 50),
    ('İzmir Köfte (Fırında)', 'DOMATES', 40),
    ('İzmir Köfte (Fırında)', 'KURU SOĞAN', 15),
    ('İzmir Köfte (Fırında)', 'EKMEKLİK UN', 4),
    ('İzmir Köfte (Fırında)', 'TUZ', 1.2),
    ('İzmir Köfte (Fırında)', 'KARABİBER', 0.3),
    ('İzmir Köfte (Fırında)', 'ZEYTİNYAĞI', 4),
    ('Çeşme Usulü Ahtapot Güveç', 'AHTAPOT', 100),
    ('Çeşme Usulü Ahtapot Güveç', 'DOMATES', 40),
    ('Çeşme Usulü Ahtapot Güveç', 'KURU SOĞAN', 15),
    ('Çeşme Usulü Ahtapot Güveç', 'YEŞİL BİBER', 15),
    ('Çeşme Usulü Ahtapot Güveç', 'ZEYTİNYAĞI', 5),
    ('Çeşme Usulü Ahtapot Güveç', 'TUZ', 1),
    ('Çeşme Usulü Ahtapot Güveç', 'KARABİBER', 0.3),
    ('Ege Otlu Peynirli Gözleme', 'YUFKA', 60),
    ('Ege Otlu Peynirli Gözleme', 'OTLU PEYNİR', 40),
    ('Ege Otlu Peynirli Gözleme', 'ISPANAK', 30),
    ('Ege Otlu Peynirli Gözleme', 'TEREYAĞI', 6),
    ('Ege Otlu Peynirli Gözleme', 'TUZ', 0.5),
    ('Ege Usulü Isırgan Kavurması (Etli)', 'KUZU ETİ (KOL)', 70),
    ('Ege Usulü Isırgan Kavurması (Etli)', 'ISIRGAN', 50),
    ('Ege Usulü Isırgan Kavurması (Etli)', 'KURU SOĞAN', 15),
    ('Ege Usulü Isırgan Kavurması (Etli)', 'ZEYTİNYAĞI', 4),
    ('Ege Usulü Isırgan Kavurması (Etli)', 'TUZ', 1),
    ('Ege Usulü Isırgan Kavurması (Etli)', 'KARABİBER', 0.3),
    ('Ege Yaylası Kuzu Tandır', 'KUZU TANDIR', 150),
    ('Ege Yaylası Kuzu Tandır', 'KURU SOĞAN', 15),
    ('Ege Yaylası Kuzu Tandır', 'ZEYTİNYAĞI', 4),
    ('Ege Yaylası Kuzu Tandır', 'TUZ', 1.5),
    ('Ege Yaylası Kuzu Tandır', 'KEKİK', 0.5),
    ('Ege Yaylası Kuzu Tandır', 'KARABİBER', 0.3),
    ('Ege Portakallı Zeytinyağlı Kek', 'EKMEKLİK UN', 50),
    ('Ege Portakallı Zeytinyağlı Kek', 'ŞEKER', 35),
    ('Ege Portakallı Zeytinyağlı Kek', 'ZEYTİNYAĞI', 20),
    ('Ege Portakallı Zeytinyağlı Kek', 'PORTAKAL', 30),
    ('Ege Portakallı Zeytinyağlı Kek', 'TAVUK YUMURTASI', 30),
    ('Ege Portakallı Zeytinyağlı Kek', 'KABARTMA TOZU', 1.5),
    ('Datça Bademli Yeşil Salata', 'ROKA', 30),
    ('Datça Bademli Yeşil Salata', 'MARUL', 20),
    ('Datça Bademli Yeşil Salata', 'BADEM', 8),
    ('Datça Bademli Yeşil Salata', 'ZEYTİNYAĞI', 4),
    ('Datça Bademli Yeşil Salata', 'LİMON SUYU', 2.5),
    ('Datça Bademli Yeşil Salata', 'TUZ', 0.5),
    ('Ege İnciri ile Komposto', 'KURU İNCİR', 50),
    ('Ege İnciri ile Komposto', 'ŞEKER', 10),
    ('Ege İnciri ile Komposto', 'SU', 80),
    ('Antalya Usulü Nohut Piyazı', 'NOHUT', 60),
    ('Antalya Usulü Nohut Piyazı', 'KURU SOĞAN', 10),
    ('Antalya Usulü Nohut Piyazı', 'MAYDANOZ', 3),
    ('Antalya Usulü Nohut Piyazı', 'ZEYTİNYAĞI', 4),
    ('Antalya Usulü Nohut Piyazı', 'LİMON SUYU', 2.5),
    ('Antalya Usulü Nohut Piyazı', 'SUMAK', 0.5),
    ('Antalya Usulü Nohut Piyazı', 'TUZ', 0.8),
    ('Mersin Tantunisi', 'DANA BONFİLE', 100),
    ('Mersin Tantunisi', 'MISIR YAĞI', 6),
    ('Mersin Tantunisi', 'KURU SOĞAN', 15),
    ('Mersin Tantunisi', 'YEŞİL BİBER', 15),
    ('Mersin Tantunisi', 'TUZ', 1),
    ('Mersin Tantunisi', 'KARABİBER', 0.3),
    ('Mersin Tantunisi', 'SUMAK', 0.5),
    ('Mersin Tantunisi', 'LAVAŞ', 50),
    ('Adana Kebap', 'KUZU KIYMA', 90),
    ('Adana Kebap', 'KIRMIZI BİBER', 15),
    ('Adana Kebap', 'PUL BİBER', 0.8),
    ('Adana Kebap', 'TUZ', 1.2),
    ('Adana Kebap', 'KARABİBER', 0.3),
    ('Hatay Usulü İçli Köfte (Etli)', 'BULGUR', 50),
    ('Hatay Usulü İçli Köfte (Etli)', 'DANA KIYMA', 80),
    ('Hatay Usulü İçli Köfte (Etli)', 'KURU SOĞAN', 20),
    ('Hatay Usulü İçli Köfte (Etli)', 'CEVİZ (İÇ)', 10),
    ('Hatay Usulü İçli Köfte (Etli)', 'TUZ', 1.2),
    ('Hatay Usulü İçli Köfte (Etli)', 'KARABİBER', 0.3),
    ('Hatay Usulü İçli Köfte (Etli)', 'PUL BİBER', 0.5),
    ('Antalya Şakşuka', 'PATLICAN', 50),
    ('Antalya Şakşuka', 'KABAK', 30),
    ('Antalya Şakşuka', 'YEŞİL BİBER', 15),
    ('Antalya Şakşuka', 'DOMATES', 40),
    ('Antalya Şakşuka', 'SARIMSAK', 1.5),
    ('Antalya Şakşuka', 'YOĞURT (TAM)', 30),
    ('Antalya Şakşuka', 'ZEYTİNYAĞI', 6),
    ('Antalya Şakşuka', 'TUZ', 1),
    ('Akdeniz Usulü Limonlu Zeytin Ezmesi', 'ZEYTİN EZMESİ', 40),
    ('Akdeniz Usulü Limonlu Zeytin Ezmesi', 'ZEYTİNYAĞI', 4),
    ('Akdeniz Usulü Limonlu Zeytin Ezmesi', 'LİMON SUYU', 2),
    ('Akdeniz Usulü Limonlu Zeytin Ezmesi', 'PUL BİBER', 0.5),
    ('Akdeniz Usulü Limonlu Zeytin Ezmesi', 'KURU SOĞAN', 5),
    ('Adana Usulü Nar Ekşili Salata', 'MARUL', 30),
    ('Adana Usulü Nar Ekşili Salata', 'NAR', 30),
    ('Adana Usulü Nar Ekşili Salata', 'CEVİZ (İÇ)', 8),
    ('Adana Usulü Nar Ekşili Salata', 'NAR EKŞİSİ', 3),
    ('Adana Usulü Nar Ekşili Salata', 'ZEYTİNYAĞI', 3),
    ('Adana Usulü Nar Ekşili Salata', 'TUZ', 0.5),
    ('Antalya Usulü Şeftali Kompostosu', 'ŞEFTALİ', 80),
    ('Antalya Usulü Şeftali Kompostosu', 'ŞEKER', 15),
    ('Antalya Usulü Şeftali Kompostosu', 'SU', 70),
    ('Kayseri Mantısı', 'EKMEKLİK UN', 70),
    ('Kayseri Mantısı', 'KUZU KIYMA', 50),
    ('Kayseri Mantısı', 'KURU SOĞAN', 15),
    ('Kayseri Mantısı', 'YOĞURT (TAM)', 60),
    ('Kayseri Mantısı', 'SARIMSAK', 2),
    ('Kayseri Mantısı', 'TEREYAĞI', 8),
    ('Kayseri Mantısı', 'PUL BİBER', 0.8),
    ('Kayseri Mantısı', 'KURU NANE', 0.5),
    ('Kayseri Mantısı', 'TUZ', 1.2),
    ('Ankara Tava (Kuzu Etli)', 'KUZU ETİ (KOL)', 120),
    ('Ankara Tava (Kuzu Etli)', 'PİRİNÇ (HAM)', 30),
    ('Ankara Tava (Kuzu Etli)', 'KURU SOĞAN', 15),
    ('Ankara Tava (Kuzu Etli)', 'TEREYAĞI', 6),
    ('Ankara Tava (Kuzu Etli)', 'TUZ', 1.2),
    ('Ankara Tava (Kuzu Etli)', 'KARABİBER', 0.3),
    ('Konya Etli Ekmek', 'EKMEKLİK UN', 80),
    ('Konya Etli Ekmek', 'KUZU KIYMA', 70),
    ('Konya Etli Ekmek', 'DOMATES', 25),
    ('Konya Etli Ekmek', 'KURU SOĞAN', 15),
    ('Konya Etli Ekmek', 'MAYDANOZ', 2),
    ('Konya Etli Ekmek', 'TUZ', 1),
    ('Konya Etli Ekmek', 'PUL BİBER', 0.5),
    ('Nevşehir Testi Kebabı', 'KUZU ETİ (KOL)', 100),
    ('Nevşehir Testi Kebabı', 'DOMATES', 30),
    ('Nevşehir Testi Kebabı', 'YEŞİL BİBER', 20),
    ('Nevşehir Testi Kebabı', 'KURU SOĞAN', 15),
    ('Nevşehir Testi Kebabı', 'MANTAR', 20),
    ('Nevşehir Testi Kebabı', 'TUZ', 1.2),
    ('Nevşehir Testi Kebabı', 'KARABİBER', 0.3),
    ('Kayseri Yağlaması', 'LAVAŞ', 60),
    ('Kayseri Yağlaması', 'KUZU KIYMA', 50),
    ('Kayseri Yağlaması', 'KURU SOĞAN', 15),
    ('Kayseri Yağlaması', 'TEREYAĞI', 6),
    ('Kayseri Yağlaması', 'PUL BİBER', 0.5),
    ('Kayseri Yağlaması', 'TUZ', 0.8),
    ('Kapadokya Kestaneli Komposto', 'KESTANE', 50),
    ('Kapadokya Kestaneli Komposto', 'ŞEKER', 15),
    ('Kapadokya Kestaneli Komposto', 'SU', 70),
    ('Kayseri Usulü Nohutlu Bulgur Pilavı', 'BULGUR', 60),
    ('Kayseri Usulü Nohutlu Bulgur Pilavı', 'NOHUT', 30),
    ('Kayseri Usulü Nohutlu Bulgur Pilavı', 'KURU SOĞAN', 15),
    ('Kayseri Usulü Nohutlu Bulgur Pilavı', 'TEREYAĞI', 6),
    ('Kayseri Usulü Nohutlu Bulgur Pilavı', 'TAVUK SUYU', 90),
    ('Kayseri Usulü Nohutlu Bulgur Pilavı', 'TUZ', 1),
    ('Niğde Bademli Un Helvası', 'EKMEKLİK UN', 50),
    ('Niğde Bademli Un Helvası', 'TEREYAĞI', 30),
    ('Niğde Bademli Un Helvası', 'ŞEKER', 40),
    ('Niğde Bademli Un Helvası', 'SÜT (TAM YAĞ)', 60),
    ('Niğde Bademli Un Helvası', 'BADEM (İÇ)', 6),
    ('Karadeniz Mıhlaması', 'MISIR UNU', 40),
    ('Karadeniz Mıhlaması', 'KAŞAR PEYNİRİ', 50),
    ('Karadeniz Mıhlaması', 'TEREYAĞI', 15),
    ('Karadeniz Mıhlaması', 'SU', 60),
    ('Karadeniz Mıhlaması', 'TUZ', 0.5),
    ('Karadeniz Kaymaklı Pide', 'EKMEKLİK UN', 70),
    ('Karadeniz Kaymaklı Pide', 'KAŞAR PEYNİRİ', 40),
    ('Karadeniz Kaymaklı Pide', 'TAVUK YUMURTASI', 30),
    ('Karadeniz Kaymaklı Pide', 'TEREYAĞI', 8),
    ('Karadeniz Kaymaklı Pide', 'TUZ', 1),
    ('Trabzon Usulü Hamsili Pilav', 'HAMSİ', 60),
    ('Trabzon Usulü Hamsili Pilav', 'PİRİNÇ (HAM)', 50),
    ('Trabzon Usulü Hamsili Pilav', 'KURU SOĞAN', 15),
    ('Trabzon Usulü Hamsili Pilav', 'TEREYAĞI', 8),
    ('Trabzon Usulü Hamsili Pilav', 'KARABİBER', 0.3),
    ('Trabzon Usulü Hamsili Pilav', 'TUZ', 1),
    ('Rize Usulü Karalahana Çorbası', 'KARALAHANA', 50),
    ('Rize Usulü Karalahana Çorbası', 'MISIR UNU', 10),
    ('Rize Usulü Karalahana Çorbası', 'KURU FASULYE', 15),
    ('Rize Usulü Karalahana Çorbası', 'TEREYAĞI', 4),
    ('Rize Usulü Karalahana Çorbası', 'TUZ', 1),
    ('Giresun Fındıklı Kuru Fasulye', 'KURU FASULYE', 50),
    ('Giresun Fındıklı Kuru Fasulye', 'FINDIK (İÇ)', 10),
    ('Giresun Fındıklı Kuru Fasulye', 'KURU SOĞAN', 15),
    ('Giresun Fındıklı Kuru Fasulye', 'DOMATES', 25),
    ('Giresun Fındıklı Kuru Fasulye', 'ZEYTİNYAĞI', 4),
    ('Giresun Fındıklı Kuru Fasulye', 'TUZ', 1),
    ('Karadeniz Mısır Ekmeği', 'MISIR UNU', 60),
    ('Karadeniz Mısır Ekmeği', 'EKMEKLİK UN', 20),
    ('Karadeniz Mısır Ekmeği', 'YOĞURT (TAM)', 30),
    ('Karadeniz Mısır Ekmeği', 'TAVUK YUMURTASI', 20),
    ('Karadeniz Mısır Ekmeği', 'KABARTMA TOZU', 1.5),
    ('Karadeniz Mısır Ekmeği', 'TUZ', 0.8),
    ('Trabzon Usulü Akçaabat Köfte', 'DANA KIYMA', 90),
    ('Trabzon Usulü Akçaabat Köfte', 'KURU SOĞAN', 10),
    ('Trabzon Usulü Akçaabat Köfte', 'GALETA UNU (PANKO)', 6),
    ('Trabzon Usulü Akçaabat Köfte', 'TUZ', 1.2),
    ('Trabzon Usulü Akçaabat Köfte', 'KARABİBER', 0.3),
    ('Trabzon Usulü Akçaabat Köfte', 'KİMYON', 0.5),
    ('Karadeniz Dutlu Komposto', 'DUT', 50),
    ('Karadeniz Dutlu Komposto', 'ŞEKER', 12),
    ('Karadeniz Dutlu Komposto', 'SU', 60),
    ('Erzurum Cağ Kebabı', 'KOYUN ETİ (BUT)', 150),
    ('Erzurum Cağ Kebabı', 'KURU SOĞAN', 10),
    ('Erzurum Cağ Kebabı', 'TUZ', 1.2),
    ('Erzurum Cağ Kebabı', 'KARABİBER', 0.3),
    ('Erzincan Tulumlu Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Erzincan Tulumlu Kavurma', 'TULUM PEYNİRİ', 15),
    ('Erzincan Tulumlu Kavurma', 'KURU SOĞAN', 10),
    ('Erzincan Tulumlu Kavurma', 'TUZ', 1),
    ('Erzincan Tulumlu Kavurma', 'KARABİBER', 0.3),
    ('Van Otlu Peynirli Kahvaltı Böreği', 'YUFKA', 50),
    ('Van Otlu Peynirli Kahvaltı Böreği', 'OTLU PEYNİR', 40),
    ('Van Otlu Peynirli Kahvaltı Böreği', 'TEREYAĞI', 6),
    ('Van Otlu Peynirli Kahvaltı Böreği', 'TAVUK YUMURTASI', 15),
    ('Van Otlu Peynirli Kahvaltı Böreği', 'TUZ', 0.5),
    ('Malatya Kayısılı Kuzu Yahnisi', 'KUZU ETİ (KOL)', 100),
    ('Malatya Kayısılı Kuzu Yahnisi', 'KURU KAYISI', 30),
    ('Malatya Kayısılı Kuzu Yahnisi', 'KURU SOĞAN', 15),
    ('Malatya Kayısılı Kuzu Yahnisi', 'TUZ', 1),
    ('Malatya Kayısılı Kuzu Yahnisi', 'KARABİBER', 0.3),
    ('Elazığ Usulü Kuru Fasulye Kavurması', 'KURU FASULYE', 50),
    ('Elazığ Usulü Kuru Fasulye Kavurması', 'DANA KIYMA', 40),
    ('Elazığ Usulü Kuru Fasulye Kavurması', 'KURU SOĞAN', 15),
    ('Elazığ Usulü Kuru Fasulye Kavurması', 'DOMATES', 25),
    ('Elazığ Usulü Kuru Fasulye Kavurması', 'TUZ', 1),
    ('Elazığ Usulü Kuru Fasulye Kavurması', 'KARABİBER', 0.3),
    ('Kars Usulü Kaz Eti Kavurması', 'KAZ ETİ (BUT, DERİSİZ, TUZ İLAVELİ)', 120),
    ('Kars Usulü Kaz Eti Kavurması', 'KURU SOĞAN', 15),
    ('Kars Usulü Kaz Eti Kavurması', 'TUZ', 0.6),
    ('Kars Usulü Kaz Eti Kavurması', 'KARABİBER', 0.3),
    ('Doğu Anadolu Pekmezli Ceviz Ezmesi', 'ÜzÜM PEKMEZİ', 50),
    ('Doğu Anadolu Pekmezli Ceviz Ezmesi', 'CEVİZ (İÇ)', 30),
    ('Doğu Anadolu Pekmezli Ceviz Ezmesi', 'MISIR NİŞASTASI', 10),
    ('Doğu Anadolu Kayısı ve Ceviz Salatası', 'KAYISI', 40),
    ('Doğu Anadolu Kayısı ve Ceviz Salatası', 'CEVİZ (İÇ)', 10),
    ('Doğu Anadolu Kayısı ve Ceviz Salatası', 'YOĞURT (TAM)', 30),
    ('Doğu Anadolu Kayısı ve Ceviz Salatası', 'ŞEKER', 3),
    ('Gaziantep Alinazik Kebabı', 'PATLICAN', 80),
    ('Gaziantep Alinazik Kebabı', 'KUZU KIYMA', 60),
    ('Gaziantep Alinazik Kebabı', 'YOĞURT (TAM)', 40),
    ('Gaziantep Alinazik Kebabı', 'SARIMSAK', 2),
    ('Gaziantep Alinazik Kebabı', 'TEREYAĞI', 4),
    ('Gaziantep Alinazik Kebabı', 'TUZ', 1),
    ('Gaziantep Alinazik Kebabı', 'KARABİBER', 0.3),
    ('Şanlıurfa Usulü Çiğ Köfte (Etsiz)', 'BULGUR', 50),
    ('Şanlıurfa Usulü Çiğ Köfte (Etsiz)', 'KONSERVE BİBER SALÇASI', 15),
    ('Şanlıurfa Usulü Çiğ Köfte (Etsiz)', 'CEVİZ (İÇ)', 10),
    ('Şanlıurfa Usulü Çiğ Köfte (Etsiz)', 'SARIMSAK', 1.5),
    ('Şanlıurfa Usulü Çiğ Köfte (Etsiz)', 'NAR EKŞİSİ', 4),
    ('Şanlıurfa Usulü Çiğ Köfte (Etsiz)', 'PUL BİBER', 1),
    ('Şanlıurfa Usulü Çiğ Köfte (Etsiz)', 'TUZ', 1),
    ('Urfa Usulü Kuzu Kavurma', 'KUZU ETİ (KOL)', 100),
    ('Urfa Usulü Kuzu Kavurma', 'KURU SOĞAN', 15),
    ('Urfa Usulü Kuzu Kavurma', 'PUL BİBER', 1),
    ('Urfa Usulü Kuzu Kavurma', 'TUZ', 1),
    ('Urfa Usulü Kuzu Kavurma', 'KARABİBER', 0.3),
    ('Mardin Usulü Kaburga Dolması', 'SIĞIR KABURGA', 150),
    ('Mardin Usulü Kaburga Dolması', 'PİRİNÇ (HAM)', 30),
    ('Mardin Usulü Kaburga Dolması', 'KURU SOĞAN', 10),
    ('Mardin Usulü Kaburga Dolması', 'KİMYON', 0.5),
    ('Mardin Usulü Kaburga Dolması', 'TUZ', 1.2),
    ('Mardin Usulü Kaburga Dolması', 'KARABİBER', 0.3),
    ('Diyarbakır Usulü Meftune', 'KUZU ETİ (KOL)', 80),
    ('Diyarbakır Usulü Meftune', 'PATLICAN', 40),
    ('Diyarbakır Usulü Meftune', 'KABAK', 30),
    ('Diyarbakır Usulü Meftune', 'DOMATES', 30),
    ('Diyarbakır Usulü Meftune', 'KURU SOĞAN', 15),
    ('Diyarbakır Usulü Meftune', 'SARIMSAK', 1.5),
    ('Diyarbakır Usulü Meftune', 'TUZ', 1),
    ('Diyarbakır Usulü Meftune', 'KARABİBER', 0.3),
    ('Antep Usulü Yuvalama Çorbası', 'YOĞURT (TAM)', 60),
    ('Antep Usulü Yuvalama Çorbası', 'PİRİNÇ (HAM)', 15),
    ('Antep Usulü Yuvalama Çorbası', 'DANA KIYMA', 30),
    ('Antep Usulü Yuvalama Çorbası', 'TAVUK SUYU', 80),
    ('Antep Usulü Yuvalama Çorbası', 'TEREYAĞI', 4),
    ('Antep Usulü Yuvalama Çorbası', 'KURU NANE', 0.5),
    ('Antep Usulü Yuvalama Çorbası', 'TUZ', 1),
    ('Siirt Usulü Büryan', 'KUZU ETİ (BUT)', 180),
    ('Siirt Usulü Büryan', 'TUZ', 1.5),
    ('Siirt Usulü Büryan', 'KARABİBER', 0.3),
    ('Antep Fıstıklı Muhallebi', 'SÜT (TAM YAĞ)', 150),
    ('Antep Fıstıklı Muhallebi', 'ANTEP FISTIĞI', 15),
    ('Antep Fıstıklı Muhallebi', 'ŞEKER', 25),
    ('Antep Fıstıklı Muhallebi', 'PİRİNÇ UNU', 8),
    ('Tekirdağ Köftesi', 'DANA KIYMA', 90),
    ('Tekirdağ Köftesi', 'KURU SOĞAN', 10),
    ('Tekirdağ Köftesi', 'EKMEKLİK UN', 4),
    ('Tekirdağ Köftesi', 'KARBONAT (YEM. SODA)', 0.3),
    ('Tekirdağ Köftesi', 'TUZ', 1.2),
    ('Tekirdağ Köftesi', 'KARABİBER', 0.3),
    ('Çanakkale Peynir Helvası', 'LOR PEYNİRİ', 60),
    ('Çanakkale Peynir Helvası', 'EKMEKLİK UN', 30),
    ('Çanakkale Peynir Helvası', 'ŞEKER', 40),
    ('Çanakkale Peynir Helvası', 'TEREYAĞI', 15),
    ('Çanakkale Peynir Helvası', 'SÜT (TAM YAĞ)', 40),
    ('Balıkesir Kaymaklı Kayısı Tatlısı', 'KAYISI', 80),
    ('Balıkesir Kaymaklı Kayısı Tatlısı', 'KAYMAK', 30),
    ('Balıkesir Kaymaklı Kayısı Tatlısı', 'ŞEKER', 15),
    ('İstanbul Usulü Etli Kuru Fasulye', 'KURU FASULYE', 60),
    ('İstanbul Usulü Etli Kuru Fasulye', 'DANA KIYMA', 40),
    ('İstanbul Usulü Etli Kuru Fasulye', 'KURU SOĞAN', 15),
    ('İstanbul Usulü Etli Kuru Fasulye', 'DOMATES', 25),
    ('İstanbul Usulü Etli Kuru Fasulye', 'TUZ', 1),
    ('İstanbul Usulü Etli Kuru Fasulye', 'KARABİBER', 0.3),
    ('Marmara Usulü Kabak Mücveri', 'KABAK', 80),
    ('Marmara Usulü Kabak Mücveri', 'EKMEKLİK UN', 15),
    ('Marmara Usulü Kabak Mücveri', 'TAVUK YUMURTASI', 20),
    ('Marmara Usulü Kabak Mücveri', 'MAYDANOZ', 3),
    ('Marmara Usulü Kabak Mücveri', 'KARABİBER', 0.3),
    ('Marmara Usulü Kabak Mücveri', 'TUZ', 1),
    ('Marmara Usulü Kabak Mücveri', 'MISIR YAĞI', 30),
    ('Bandırma Usulü Tavuk Sote', 'TAVUK BUT', 100),
    ('Bandırma Usulü Tavuk Sote', 'KURU SOĞAN', 15),
    ('Bandırma Usulü Tavuk Sote', 'DOMATES', 30),
    ('Bandırma Usulü Tavuk Sote', 'YEŞİL BİBER', 15),
    ('Bandırma Usulü Tavuk Sote', 'TUZ', 1),
    ('Bandırma Usulü Tavuk Sote', 'KARABİBER', 0.3),
    ('Marmara Usulü Fırında Lüfer', 'LÜFER', 150),
    ('Marmara Usulü Fırında Lüfer', 'ZEYTİNYAĞI', 4),
    ('Marmara Usulü Fırında Lüfer', 'LİMON SUYU', 3),
    ('Marmara Usulü Fırında Lüfer', 'TUZ', 1),
    ('Marmara Usulü Fırında Lüfer', 'KEKİK', 0.3),
    ('Marmara Usulü Vişneli Yoğurt Dondurması', 'YOĞURT (TAM)', 60),
    ('Marmara Usulü Vişneli Yoğurt Dondurması', 'VİŞNE', 30),
    ('Marmara Usulü Vişneli Yoğurt Dondurması', 'ŞEKER', 15),
    ('Kemalpaşa Köftesi', 'DANA KIYMA', 90),
    ('Kemalpaşa Köftesi', 'EKMEKLİK UN', 6),
    ('Kemalpaşa Köftesi', 'KURU SOĞAN', 10),
    ('Kemalpaşa Köftesi', 'TUZ', 1),
    ('Kemalpaşa Köftesi', 'KARABİBER', 0.3),
    ('Aydın İncirli Kuzu Tandır', 'KUZU TANDIR', 150),
    ('Aydın İncirli Kuzu Tandır', 'KURU İNCİR', 20),
    ('Aydın İncirli Kuzu Tandır', 'KURU SOĞAN', 10),
    ('Aydın İncirli Kuzu Tandır', 'TUZ', 1.2),
    ('Aydın İncirli Kuzu Tandır', 'KARABİBER', 0.3),
    ('Muğla Yeşil Erik Salatası', 'ERİK', 40),
    ('Muğla Yeşil Erik Salatası', 'ZEYTİNYAĞI', 3),
    ('Muğla Yeşil Erik Salatası', 'TUZ', 0.8),
    ('Foça Usulü Kalamar Tava', 'KALAMAR', 100),
    ('Foça Usulü Kalamar Tava', 'EKMEKLİK UN', 20),
    ('Foça Usulü Kalamar Tava', 'MISIR YAĞI', 30),
    ('Foça Usulü Kalamar Tava', 'LİMON SUYU', 2.5),
    ('Foça Usulü Kalamar Tava', 'TUZ', 1),
    ('Ege Yeşil Zeytinli Havuç Salatası', 'HAVUÇ', 50),
    ('Ege Yeşil Zeytinli Havuç Salatası', 'YEŞİL ZEYTİN', 15),
    ('Ege Yeşil Zeytinli Havuç Salatası', 'ZEYTİNYAĞI', 3),
    ('Ege Yeşil Zeytinli Havuç Salatası', 'LİMON SUYU', 2),
    ('Ege Yeşil Zeytinli Havuç Salatası', 'TUZ', 0.5),
    ('İzmir Usulü Nohutlu Bamya', 'BAMYA', 60),
    ('İzmir Usulü Nohutlu Bamya', 'NOHUT', 20),
    ('İzmir Usulü Nohutlu Bamya', 'DOMATES', 30),
    ('İzmir Usulü Nohutlu Bamya', 'KURU SOĞAN', 10),
    ('İzmir Usulü Nohutlu Bamya', 'ZEYTİNYAĞI', 4),
    ('İzmir Usulü Nohutlu Bamya', 'ŞEKER', 0.5),
    ('İzmir Usulü Nohutlu Bamya', 'TUZ', 0.8),
    ('Ege Zeytinyağlı Bakla ve Enginar', 'BAKLA', 50),
    ('Ege Zeytinyağlı Bakla ve Enginar', 'ENGİNAR', 40),
    ('Ege Zeytinyağlı Bakla ve Enginar', 'KURU SOĞAN', 10),
    ('Ege Zeytinyağlı Bakla ve Enginar', 'TAZE DEREOTU', 1.5),
    ('Ege Zeytinyağlı Bakla ve Enginar', 'ZEYTİNYAĞI', 4),
    ('Ege Zeytinyağlı Bakla ve Enginar', 'ŞEKER', 0.5),
    ('Ege Zeytinyağlı Bakla ve Enginar', 'TUZ', 0.8),
    ('İzmir Lokması', 'EKMEKLİK UN', 50),
    ('İzmir Lokması', 'KABARTMA TOZU', 1.5),
    ('İzmir Lokması', 'SU', 50),
    ('İzmir Lokması', 'ŞEKER', 40),
    ('İzmir Lokması', 'MISIR YAĞI', 40),
    ('Antalya Usulü Etli Nohut Yemeği', 'KUZU ETİ (KOL)', 80),
    ('Antalya Usulü Etli Nohut Yemeği', 'NOHUT', 30),
    ('Antalya Usulü Etli Nohut Yemeği', 'KURU SOĞAN', 15),
    ('Antalya Usulü Etli Nohut Yemeği', 'DOMATES', 25),
    ('Antalya Usulü Etli Nohut Yemeği', 'TUZ', 1),
    ('Antalya Usulü Etli Nohut Yemeği', 'KARABİBER', 0.3),
    ('Mersin Usulü Nohutlu Bulgur Aşı', 'BULGUR', 50),
    ('Mersin Usulü Nohutlu Bulgur Aşı', 'NOHUT', 25),
    ('Mersin Usulü Nohutlu Bulgur Aşı', 'KURU SOĞAN', 10),
    ('Mersin Usulü Nohutlu Bulgur Aşı', 'DOMATES', 20),
    ('Mersin Usulü Nohutlu Bulgur Aşı', 'ZEYTİNYAĞI', 3),
    ('Mersin Usulü Nohutlu Bulgur Aşı', 'TUZ', 0.8),
    ('Hatay Usulü Tepsi Kebabı', 'KUZU KIYMA', 90),
    ('Hatay Usulü Tepsi Kebabı', 'DOMATES', 25),
    ('Hatay Usulü Tepsi Kebabı', 'YEŞİL BİBER', 15),
    ('Hatay Usulü Tepsi Kebabı', 'KURU SOĞAN', 10),
    ('Hatay Usulü Tepsi Kebabı', 'TUZ', 1),
    ('Hatay Usulü Tepsi Kebabı', 'KARABİBER', 0.3),
    ('Adana Usulü Analı Kızlı Çorba', 'BULGUR', 20),
    ('Adana Usulü Analı Kızlı Çorba', 'DANA KIYMA', 30),
    ('Adana Usulü Analı Kızlı Çorba', 'YOĞURT (TAM)', 40),
    ('Adana Usulü Analı Kızlı Çorba', 'TAVUK SUYU', 80),
    ('Adana Usulü Analı Kızlı Çorba', 'KURU NANE', 0.5),
    ('Adana Usulü Analı Kızlı Çorba', 'TEREYAĞI', 3),
    ('Adana Usulü Analı Kızlı Çorba', 'TUZ', 0.8),
    ('Antalya Yeşil Erik Hoşafı', 'ERİK', 50),
    ('Antalya Yeşil Erik Hoşafı', 'ŞEKER', 15),
    ('Antalya Yeşil Erik Hoşafı', 'SU', 70),
    ('Mersin Usulü Portakallı Zeytin Salatası', 'YEŞİL ZEYTİN', 30),
    ('Mersin Usulü Portakallı Zeytin Salatası', 'PORTAKAL', 30),
    ('Mersin Usulü Portakallı Zeytin Salatası', 'KURU SOĞAN', 5),
    ('Mersin Usulü Portakallı Zeytin Salatası', 'ZEYTİNYAĞI', 3),
    ('Mersin Usulü Portakallı Zeytin Salatası', 'SUMAK', 0.5),
    ('Akdeniz Usulü Enginar Kalpli Salata', 'ENGİNAR KALBİ', 40),
    ('Akdeniz Usulü Enginar Kalpli Salata', 'ROKA', 20),
    ('Akdeniz Usulü Enginar Kalpli Salata', 'ZEYTİNYAĞI', 3),
    ('Akdeniz Usulü Enginar Kalpli Salata', 'LİMON SUYU', 2),
    ('Akdeniz Usulü Enginar Kalpli Salata', 'TUZ', 0.5),
    ('Antalya Usulü Şeftalili Tavuk Sote', 'TAVUK GÖĞÜS', 90),
    ('Antalya Usulü Şeftalili Tavuk Sote', 'ŞEFTALİ', 30),
    ('Antalya Usulü Şeftalili Tavuk Sote', 'KURU SOĞAN', 10),
    ('Antalya Usulü Şeftalili Tavuk Sote', 'ZEYTİNYAĞI', 3),
    ('Antalya Usulü Şeftalili Tavuk Sote', 'TUZ', 0.8),
    ('Antalya Usulü Şeftalili Tavuk Sote', 'KARABİBER', 0.3),
    ('Sivas Usulü Kes Kes', 'KUZU ETİ (KOL)', 90),
    ('Sivas Usulü Kes Kes', 'PATATES', 40),
    ('Sivas Usulü Kes Kes', 'ERİK', 20),
    ('Sivas Usulü Kes Kes', 'KURU SOĞAN', 10),
    ('Sivas Usulü Kes Kes', 'TUZ', 1),
    ('Sivas Usulü Kes Kes', 'KARABİBER', 0.3),
    ('Kırşehir Usulü Nohutlu Yahni', 'KUZU ETİ (KOL)', 80),
    ('Kırşehir Usulü Nohutlu Yahni', 'NOHUT', 30),
    ('Kırşehir Usulü Nohutlu Yahni', 'KURU SOĞAN', 15),
    ('Kırşehir Usulü Nohutlu Yahni', 'TUZ', 1),
    ('Kırşehir Usulü Nohutlu Yahni', 'KARABİBER', 0.3),
    ('Aksaray Usulü Bulgurlu Köfte (Fırında)', 'BULGUR', 30),
    ('Aksaray Usulü Bulgurlu Köfte (Fırında)', 'DANA KIYMA', 70),
    ('Aksaray Usulü Bulgurlu Köfte (Fırında)', 'KURU SOĞAN', 15),
    ('Aksaray Usulü Bulgurlu Köfte (Fırında)', 'MAYDANOZ', 2),
    ('Aksaray Usulü Bulgurlu Köfte (Fırında)', 'TUZ', 1),
    ('Aksaray Usulü Bulgurlu Köfte (Fırında)', 'KARABİBER', 0.3),
    ('Nevşehir Üzümlü Kabak Tatlısı', 'KABAK', 80),
    ('Nevşehir Üzümlü Kabak Tatlısı', 'ŞEKER', 30),
    ('Nevşehir Üzümlü Kabak Tatlısı', 'CEVİZ (İÇ)', 8),
    ('Konya Usulü Mercimekli Ekmek Aşı', 'EKMEK (BEYAZ)', 30),
    ('Konya Usulü Mercimekli Ekmek Aşı', 'KIRMIZI MERCİMEK', 20),
    ('Konya Usulü Mercimekli Ekmek Aşı', 'TAVUK SUYU', 90),
    ('Konya Usulü Mercimekli Ekmek Aşı', 'TEREYAĞI', 4),
    ('Konya Usulü Mercimekli Ekmek Aşı', 'PUL BİBER', 0.5),
    ('Konya Usulü Mercimekli Ekmek Aşı', 'TUZ', 0.8),
    ('Ankara Usulü Zerde', 'PİRİNÇ (HAM)', 20),
    ('Ankara Usulü Zerde', 'ŞEKER', 40),
    ('Ankara Usulü Zerde', 'SAFRAN', 0.1),
    ('Ankara Usulü Zerde', 'SU', 120),
    ('Ankara Usulü Zerde', 'KUŞ ÜZÜMÜ', 5),
    ('Niğde Usulü Zeytinyağlı Nohut', 'NOHUT', 50),
    ('Niğde Usulü Zeytinyağlı Nohut', 'KURU SOĞAN', 15),
    ('Niğde Usulü Zeytinyağlı Nohut', 'DOMATES', 20),
    ('Niğde Usulü Zeytinyağlı Nohut', 'ZEYTİNYAĞI', 4),
    ('Niğde Usulü Zeytinyağlı Nohut', 'ŞEKER', 0.5),
    ('Niğde Usulü Zeytinyağlı Nohut', 'TUZ', 0.8),
    ('Kapadokya Usulü Karışık Kış Turşusu', 'LAHANA', 40),
    ('Kapadokya Usulü Karışık Kış Turşusu', 'HAVUÇ', 20),
    ('Kapadokya Usulü Karışık Kış Turşusu', 'PATLICAN', 20),
    ('Kapadokya Usulü Karışık Kış Turşusu', 'SİRKE', 6),
    ('Kapadokya Usulü Karışık Kış Turşusu', 'TUZ', 4),
    ('Kapadokya Usulü Karışık Kış Turşusu', 'SARIMSAK', 1.5),
    ('Samsun Usulü Kaşarlı Sucuklu Pide', 'EKMEKLİK UN', 70),
    ('Samsun Usulü Kaşarlı Sucuklu Pide', 'KAŞAR PEYNİRİ', 30),
    ('Samsun Usulü Kaşarlı Sucuklu Pide', 'SUCUK', 25),
    ('Samsun Usulü Kaşarlı Sucuklu Pide', 'TAVUK YUMURTASI', 20),
    ('Samsun Usulü Kaşarlı Sucuklu Pide', 'TEREYAĞI', 6),
    ('Samsun Usulü Kaşarlı Sucuklu Pide', 'TUZ', 1),
    ('Ordu Usulü Fındıklı Pilav', 'PİRİNÇ (HAM)', 60),
    ('Ordu Usulü Fındıklı Pilav', 'FINDIK (İÇ)', 10),
    ('Ordu Usulü Fındıklı Pilav', 'TEREYAĞI', 6),
    ('Ordu Usulü Fındıklı Pilav', 'TAVUK SUYU', 90),
    ('Ordu Usulü Fındıklı Pilav', 'TUZ', 1),
    ('Rize Usulü Mantar Kavurması (Etli)', 'KUZU ETİ (KOL)', 70),
    ('Rize Usulü Mantar Kavurması (Etli)', 'MANTAR', 50),
    ('Rize Usulü Mantar Kavurması (Etli)', 'KURU SOĞAN', 15),
    ('Rize Usulü Mantar Kavurması (Etli)', 'TEREYAĞI', 4),
    ('Rize Usulü Mantar Kavurması (Etli)', 'TUZ', 1),
    ('Rize Usulü Mantar Kavurması (Etli)', 'KARABİBER', 0.3),
    ('Giresun Usulü Fasulye Turşusu', 'TAZE FASULYE', 70),
    ('Giresun Usulü Fasulye Turşusu', 'SİRKE', 6),
    ('Giresun Usulü Fasulye Turşusu', 'TUZ', 4),
    ('Giresun Usulü Fasulye Turşusu', 'SARIMSAK', 2),
    ('Trabzon Usulü Karalahana Sarması (Etli)', 'KARALAHANA', 80),
    ('Trabzon Usulü Karalahana Sarması (Etli)', 'PİRİNÇ (HAM)', 25),
    ('Trabzon Usulü Karalahana Sarması (Etli)', 'DANA KIYMA', 50),
    ('Trabzon Usulü Karalahana Sarması (Etli)', 'KURU SOĞAN', 10),
    ('Trabzon Usulü Karalahana Sarması (Etli)', 'TUZ', 1),
    ('Trabzon Usulü Karalahana Sarması (Etli)', 'KARABİBER', 0.3),
    ('Bayburt Usulü Kuru Fasulye Çorbası', 'KURU FASULYE', 40),
    ('Bayburt Usulü Kuru Fasulye Çorbası', 'KURU SOĞAN', 10),
    ('Bayburt Usulü Kuru Fasulye Çorbası', 'TEREYAĞI', 3),
    ('Bayburt Usulü Kuru Fasulye Çorbası', 'TUZ', 0.8),
    ('Karadeniz Usulü Hamsi Buğulama', 'HAMSİ', 120),
    ('Karadeniz Usulü Hamsi Buğulama', 'KURU SOĞAN', 15),
    ('Karadeniz Usulü Hamsi Buğulama', 'MAYDANOZ', 2),
    ('Karadeniz Usulü Hamsi Buğulama', 'ZEYTİNYAĞI', 3),
    ('Karadeniz Usulü Hamsi Buğulama', 'TUZ', 0.8),
    ('Karadeniz Usulü Elmalı Ceviz Tatlısı', 'ELMA', 60),
    ('Karadeniz Usulü Elmalı Ceviz Tatlısı', 'CEVİZ (İÇ)', 15),
    ('Karadeniz Usulü Elmalı Ceviz Tatlısı', 'ŞEKER', 20),
    ('Karadeniz Usulü Elmalı Ceviz Tatlısı', 'TEREYAĞI', 4),
    ('Muş Usulü Kuzu Haşlama', 'KUZU ETİ (BUT)', 120),
    ('Muş Usulü Kuzu Haşlama', 'KURU SOĞAN', 10),
    ('Muş Usulü Kuzu Haşlama', 'TUZ', 1.2),
    ('Muş Usulü Kuzu Haşlama', 'KARABİBER', 0.3),
    ('Ağrı Usulü Lorlu Kavurma (Etsiz)', 'LOR PEYNİRİ', 50),
    ('Ağrı Usulü Lorlu Kavurma (Etsiz)', 'KURU SOĞAN', 10),
    ('Ağrı Usulü Lorlu Kavurma (Etsiz)', 'TEREYAĞI', 4),
    ('Ağrı Usulü Lorlu Kavurma (Etsiz)', 'PUL BİBER', 0.5),
    ('Ağrı Usulü Lorlu Kavurma (Etsiz)', 'CEVİZ (İÇ)', 6),
    ('Ağrı Usulü Lorlu Kavurma (Etsiz)', 'TUZ', 0.5),
    ('Kars Usulü Kaşarlı Kete', 'EKMEKLİK UN', 60),
    ('Kars Usulü Kaşarlı Kete', 'KAŞAR PEYNİRİ', 40),
    ('Kars Usulü Kaşarlı Kete', 'TEREYAĞI', 10),
    ('Kars Usulü Kaşarlı Kete', 'TUZ', 0.8),
    ('Bitlis Usulü Karışık Dolma (Etli)', 'KABAK', 50),
    ('Bitlis Usulü Karışık Dolma (Etli)', 'YEŞİL BİBER', 40),
    ('Bitlis Usulü Karışık Dolma (Etli)', 'PİRİNÇ (HAM)', 25),
    ('Bitlis Usulü Karışık Dolma (Etli)', 'DANA KIYMA', 50),
    ('Bitlis Usulü Karışık Dolma (Etli)', 'KURU SOĞAN', 10),
    ('Bitlis Usulü Karışık Dolma (Etli)', 'TUZ', 1),
    ('Bitlis Usulü Karışık Dolma (Etli)', 'KARABİBER', 0.3),
    ('Iğdır Usulü Kayısılı Pilav', 'PİRİNÇ (HAM)', 50),
    ('Iğdır Usulü Kayısılı Pilav', 'KURU KAYISI', 20),
    ('Iğdır Usulü Kayısılı Pilav', 'TEREYAĞI', 6),
    ('Iğdır Usulü Kayısılı Pilav', 'TAVUK SUYU', 90),
    ('Iğdır Usulü Kayısılı Pilav', 'TUZ', 0.8),
    ('Erzincan Usulü Tulumlu Makarna', 'MAKARNA', 70),
    ('Erzincan Usulü Tulumlu Makarna', 'TULUM PEYNİRİ', 30),
    ('Erzincan Usulü Tulumlu Makarna', 'TEREYAĞI', 10),
    ('Erzincan Usulü Tulumlu Makarna', 'TUZ', 1),
    ('Van Usulü Pazılı Kavurma (Etli)', 'KUZU ETİ (KOL)', 70),
    ('Van Usulü Pazılı Kavurma (Etli)', 'PAZI', 50),
    ('Van Usulü Pazılı Kavurma (Etli)', 'KURU SOĞAN', 15),
    ('Van Usulü Pazılı Kavurma (Etli)', 'TUZ', 1),
    ('Van Usulü Pazılı Kavurma (Etli)', 'KARABİBER', 0.3),
    ('Doğu Anadolu Cevizli Kayısı Kurusu Tatlısı', 'KURU KAYISI', 40),
    ('Doğu Anadolu Cevizli Kayısı Kurusu Tatlısı', 'CEVİZ (İÇ)', 15),
    ('Doğu Anadolu Cevizli Kayısı Kurusu Tatlısı', 'BAL', 10),
    ('Gaziantep Usulü Fıstıklı Kebap', 'KUZU KIYMA', 90),
    ('Gaziantep Usulü Fıstıklı Kebap', 'ANTEP FISTIĞI', 10),
    ('Gaziantep Usulü Fıstıklı Kebap', 'KURU SOĞAN', 10),
    ('Gaziantep Usulü Fıstıklı Kebap', 'TUZ', 1),
    ('Gaziantep Usulü Fıstıklı Kebap', 'KARABİBER', 0.3),
    ('Şanlıurfa Usulü Patlıcan Kebabı', 'PATLICAN', 70),
    ('Şanlıurfa Usulü Patlıcan Kebabı', 'KUZU KIYMA', 70),
    ('Şanlıurfa Usulü Patlıcan Kebabı', 'KURU SOĞAN', 15),
    ('Şanlıurfa Usulü Patlıcan Kebabı', 'DOMATES', 20),
    ('Şanlıurfa Usulü Patlıcan Kebabı', 'TUZ', 1),
    ('Şanlıurfa Usulü Patlıcan Kebabı', 'KARABİBER', 0.3),
    ('Diyarbakır Usulü Cevizli Biber Salatası', 'YEŞİL BİBER', 40),
    ('Diyarbakır Usulü Cevizli Biber Salatası', 'CEVİZ (İÇ)', 10),
    ('Diyarbakır Usulü Cevizli Biber Salatası', 'SARIMSAK', 1.5),
    ('Diyarbakır Usulü Cevizli Biber Salatası', 'ZEYTİNYAĞI', 3),
    ('Diyarbakır Usulü Cevizli Biber Salatası', 'NAR EKŞİSİ', 2),
    ('Diyarbakır Usulü Cevizli Biber Salatası', 'TUZ', 0.8),
    ('Mardin Usulü Susamlı Marul Salatası', 'MARUL', 30),
    ('Mardin Usulü Susamlı Marul Salatası', 'SUSAM', 3),
    ('Mardin Usulü Susamlı Marul Salatası', 'ZEYTİNYAĞI', 3),
    ('Mardin Usulü Susamlı Marul Salatası', 'NAR EKŞİSİ', 2),
    ('Mardin Usulü Susamlı Marul Salatası', 'TUZ', 0.5),
    ('Siirt Usulü Perde Pilavı', 'PİRİNÇ (HAM)', 50),
    ('Siirt Usulü Perde Pilavı', 'TAVUK GÖĞÜS', 50),
    ('Siirt Usulü Perde Pilavı', 'YUFKA', 20),
    ('Siirt Usulü Perde Pilavı', 'KURU SOĞAN', 10),
    ('Siirt Usulü Perde Pilavı', 'TAVUK SUYU', 80),
    ('Siirt Usulü Perde Pilavı', 'ANTEP FISTIĞI', 4),
    ('Siirt Usulü Perde Pilavı', 'TEREYAĞI', 6),
    ('Siirt Usulü Perde Pilavı', 'TUZ', 1),
    ('Batman Usulü Etli Yaprak Sarma', 'SALAMURA YAPRAK', 40),
    ('Batman Usulü Etli Yaprak Sarma', 'PİRİNÇ (HAM)', 20),
    ('Batman Usulü Etli Yaprak Sarma', 'DANA KIYMA', 50),
    ('Batman Usulü Etli Yaprak Sarma', 'KURU SOĞAN', 10),
    ('Batman Usulü Etli Yaprak Sarma', 'LİMON SUYU', 2),
    ('Batman Usulü Etli Yaprak Sarma', 'TUZ', 0.8),
    ('Batman Usulü Etli Yaprak Sarma', 'KARABİBER', 0.3),
    ('Şırnak Usulü Kuzu Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Şırnak Usulü Kuzu Kavurma', 'KURU SOĞAN', 10),
    ('Şırnak Usulü Kuzu Kavurma', 'TUZ', 1),
    ('Şırnak Usulü Kuzu Kavurma', 'KARABİBER', 0.3),
    ('Kilis Usulü Zeytinyağlı Nohutlu Salata', 'NOHUT', 50),
    ('Kilis Usulü Zeytinyağlı Nohutlu Salata', 'DOMATES', 20),
    ('Kilis Usulü Zeytinyağlı Nohutlu Salata', 'YEŞİL BİBER', 15),
    ('Kilis Usulü Zeytinyağlı Nohutlu Salata', 'ZEYTİNYAĞI', 3),
    ('Kilis Usulü Zeytinyağlı Nohutlu Salata', 'SUMAK', 0.5),
    ('Kilis Usulü Zeytinyağlı Nohutlu Salata', 'TUZ', 0.8),
    ('Balıkesir Usulü Keşkek', 'KUZU ETİ (KOL)', 80),
    ('Balıkesir Usulü Keşkek', 'BULGUR', 40),
    ('Balıkesir Usulü Keşkek', 'KURU SOĞAN', 10),
    ('Balıkesir Usulü Keşkek', 'TEREYAĞI', 6),
    ('Balıkesir Usulü Keşkek', 'TUZ', 1.2),
    ('Balıkesir Usulü Keşkek', 'KARABİBER', 0.3),
    ('Çanakkale Usulü Midye Pilavı', 'MİDYE', 80),
    ('Çanakkale Usulü Midye Pilavı', 'PİRİNÇ (HAM)', 40),
    ('Çanakkale Usulü Midye Pilavı', 'KURU SOĞAN', 10),
    ('Çanakkale Usulü Midye Pilavı', 'ZEYTİNYAĞI', 3),
    ('Çanakkale Usulü Midye Pilavı', 'KARABİBER', 0.3),
    ('Çanakkale Usulü Midye Pilavı', 'TUZ', 0.8),
    ('Kırklareli Usulü Zeytinyağlı Barbunya', 'BARBUNYA', 60),
    ('Kırklareli Usulü Zeytinyağlı Barbunya', 'DOMATES', 25),
    ('Kırklareli Usulü Zeytinyağlı Barbunya', 'KURU SOĞAN', 10),
    ('Kırklareli Usulü Zeytinyağlı Barbunya', 'ZEYTİNYAĞI', 4),
    ('Kırklareli Usulü Zeytinyağlı Barbunya', 'ŞEKER', 0.5),
    ('Kırklareli Usulü Zeytinyağlı Barbunya', 'TUZ', 0.8),
    ('Edirne Usulü Tavuklu Erişte', 'MAKARNA', 60),
    ('Edirne Usulü Tavuklu Erişte', 'TAVUK GÖĞÜS', 40),
    ('Edirne Usulü Tavuklu Erişte', 'TEREYAĞI', 6),
    ('Edirne Usulü Tavuklu Erişte', 'KAŞAR PEYNİRİ', 20),
    ('Edirne Usulü Tavuklu Erişte', 'TUZ', 0.8),
    ('Tekirdağ Usulü Zeytinyağlı Karnabahar', 'KARNABAHAR', 70),
    ('Tekirdağ Usulü Zeytinyağlı Karnabahar', 'KURU SOĞAN', 10),
    ('Tekirdağ Usulü Zeytinyağlı Karnabahar', 'ZEYTİNYAĞI', 4),
    ('Tekirdağ Usulü Zeytinyağlı Karnabahar', 'ŞEKER', 0.5),
    ('Tekirdağ Usulü Zeytinyağlı Karnabahar', 'TUZ', 0.8),
    ('Kocaeli Usulü Pilav Üstü Tavuk', 'PİRİNÇ (HAM)', 50),
    ('Kocaeli Usulü Pilav Üstü Tavuk', 'TAVUK BUT', 60),
    ('Kocaeli Usulü Pilav Üstü Tavuk', 'TEREYAĞI', 6),
    ('Kocaeli Usulü Pilav Üstü Tavuk', 'TAVUK SUYU', 80),
    ('Kocaeli Usulü Pilav Üstü Tavuk', 'TUZ', 0.8),
    ('Kocaeli Usulü Pilav Üstü Tavuk', 'KARABİBER', 0.3),
    ('Marmara Usulü Cevizli Ayva Tatlısı', 'AYVA', 70),
    ('Marmara Usulü Cevizli Ayva Tatlısı', 'ŞEKER', 25),
    ('Marmara Usulü Cevizli Ayva Tatlısı', 'CEVİZ (İÇ)', 10),
    ('Marmara Usulü Cevizli Ayva Tatlısı', 'SU', 50),
    ('Marmara Usulü Zeytinli Domates Salatası', 'DOMATES', 50),
    ('Marmara Usulü Zeytinli Domates Salatası', 'YEŞİL ZEYTİN', 15),
    ('Marmara Usulü Zeytinli Domates Salatası', 'KURU SOĞAN', 5),
    ('Marmara Usulü Zeytinli Domates Salatası', 'ZEYTİNYAĞI', 3),
    ('Marmara Usulü Zeytinli Domates Salatası', 'TUZ', 0.5),
    ('Söke Usulü Pirinç Pilavı', 'PİRİNÇ (HAM)', 60),
    ('Söke Usulü Pirinç Pilavı', 'TEREYAĞI', 6),
    ('Söke Usulü Pirinç Pilavı', 'TAVUK SUYU', 90),
    ('Söke Usulü Pirinç Pilavı', 'TUZ', 0.8),
    ('Bodrum Usulü Karidesli Salata', 'KARİDES', 50),
    ('Bodrum Usulü Karidesli Salata', 'MARUL', 20),
    ('Bodrum Usulü Karidesli Salata', 'ZEYTİNYAĞI', 3),
    ('Bodrum Usulü Karidesli Salata', 'LİMON SUYU', 2),
    ('Bodrum Usulü Karidesli Salata', 'TUZ', 0.8),
    ('Milas Usulü Hellim Izgara', 'HELLİM PEYNİRİ', 50),
    ('Milas Usulü Hellim Izgara', 'ZEYTİNYAĞI', 3),
    ('Milas Usulü Hellim Izgara', 'LİMON SUYU', 1.5),
    ('Kuşadası Usulü Izgara Çipura', 'ÇİPURA', 150),
    ('Kuşadası Usulü Izgara Çipura', 'ZEYTİNYAĞI', 3),
    ('Kuşadası Usulü Izgara Çipura', 'LİMON SUYU', 2),
    ('Kuşadası Usulü Izgara Çipura', 'TUZ', 0.8),
    ('Kuşadası Usulü Izgara Çipura', 'KEKİK', 0.3),
    ('Alaçatı Usulü Pazı Kavurması (Zeytinyağlı)', 'PAZI', 70),
    ('Alaçatı Usulü Pazı Kavurması (Zeytinyağlı)', 'KURU SOĞAN', 10),
    ('Alaçatı Usulü Pazı Kavurması (Zeytinyağlı)', 'PİRİNÇ (HAM)', 6),
    ('Alaçatı Usulü Pazı Kavurması (Zeytinyağlı)', 'ZEYTİNYAĞI', 3),
    ('Alaçatı Usulü Pazı Kavurması (Zeytinyağlı)', 'TUZ', 0.8),
    ('Çeşme Usulü Karpuzlu Peynir Tabağı', 'KARPUZ', 60),
    ('Çeşme Usulü Karpuzlu Peynir Tabağı', 'OTLU PEYNİR', 20),
    ('Çeşme Usulü Karpuzlu Peynir Tabağı', 'TAZE NANE', 1),
    ('Bergama Usulü Peynirli Domates Dolması (Etsiz)', 'DOMATES', 70),
    ('Bergama Usulü Peynirli Domates Dolması (Etsiz)', 'LOR PEYNİRİ', 30),
    ('Bergama Usulü Peynirli Domates Dolması (Etsiz)', 'MAYDANOZ', 2),
    ('Bergama Usulü Peynirli Domates Dolması (Etsiz)', 'ZEYTİNYAĞI', 2),
    ('Bergama Usulü Peynirli Domates Dolması (Etsiz)', 'TUZ', 0.5),
    ('İzmir Usulü Portakallı Zeytinyağlı Pancar', 'PANCAR', 60),
    ('İzmir Usulü Portakallı Zeytinyağlı Pancar', 'PORTAKAL', 20),
    ('İzmir Usulü Portakallı Zeytinyağlı Pancar', 'ZEYTİNYAĞI', 3),
    ('İzmir Usulü Portakallı Zeytinyağlı Pancar', 'ŞEKER', 0.5),
    ('İzmir Usulü Portakallı Zeytinyağlı Pancar', 'TUZ', 0.8),
    ('Silifke Usulü Yoğurtlu Köfte', 'DANA KIYMA', 80),
    ('Silifke Usulü Yoğurtlu Köfte', 'YOĞURT (TAM)', 40),
    ('Silifke Usulü Yoğurtlu Köfte', 'TEREYAĞI', 4),
    ('Silifke Usulü Yoğurtlu Köfte', 'DOMATES', 20),
    ('Silifke Usulü Yoğurtlu Köfte', 'TUZ', 1),
    ('Silifke Usulü Yoğurtlu Köfte', 'KARABİBER', 0.3),
    ('Anamur Usulü Portakallı Muz Tatlısı', 'MUZ', 50),
    ('Anamur Usulü Portakallı Muz Tatlısı', 'PORTAKAL', 30),
    ('Anamur Usulü Portakallı Muz Tatlısı', 'BAL', 6),
    ('Kaş Usulü Izgara Karides', 'KARİDES', 100),
    ('Kaş Usulü Izgara Karides', 'ZEYTİNYAĞI', 3),
    ('Kaş Usulü Izgara Karides', 'LİMON SUYU', 2),
    ('Kaş Usulü Izgara Karides', 'SARIMSAK', 1.5),
    ('Kaş Usulü Izgara Karides', 'TUZ', 0.8),
    ('Alanya Usulü Karides Pilavı', 'KARİDES', 50),
    ('Alanya Usulü Karides Pilavı', 'PİRİNÇ (HAM)', 50),
    ('Alanya Usulü Karides Pilavı', 'KURU SOĞAN', 10),
    ('Alanya Usulü Karides Pilavı', 'ZEYTİNYAĞI', 3),
    ('Alanya Usulü Karides Pilavı', 'TUZ', 0.8),
    ('Antalya Usulü Zeytinyağlı Enginar Kalpli Pilav', 'PİRİNÇ (HAM)', 50),
    ('Antalya Usulü Zeytinyağlı Enginar Kalpli Pilav', 'ENGİNAR KALBİ', 30),
    ('Antalya Usulü Zeytinyağlı Enginar Kalpli Pilav', 'KURU SOĞAN', 10),
    ('Antalya Usulü Zeytinyağlı Enginar Kalpli Pilav', 'ZEYTİNYAĞI', 3),
    ('Antalya Usulü Zeytinyağlı Enginar Kalpli Pilav', 'TUZ', 0.8),
    ('Mersin Usulü Tirit', 'KUZU ETİ (KOL)', 90),
    ('Mersin Usulü Tirit', 'EKMEK (BEYAZ)', 30),
    ('Mersin Usulü Tirit', 'KURU SOĞAN', 10),
    ('Mersin Usulü Tirit', 'TUZ', 1),
    ('Mersin Usulü Tirit', 'KARABİBER', 0.3),
    ('Hatay Usulü Kaytaz Böreği', 'YUFKA', 40),
    ('Hatay Usulü Kaytaz Böreği', 'DANA KIYMA', 30),
    ('Hatay Usulü Kaytaz Böreği', 'KURU SOĞAN', 6),
    ('Hatay Usulü Kaytaz Böreği', 'MISIR YAĞI', 30),
    ('Hatay Usulü Kaytaz Böreği', 'TUZ', 0.6),
    ('Adana Usulü Zeytinyağlı Nohutlu Ispanak', 'ISPANAK', 60),
    ('Adana Usulü Zeytinyağlı Nohutlu Ispanak', 'NOHUT', 20),
    ('Adana Usulü Zeytinyağlı Nohutlu Ispanak', 'KURU SOĞAN', 10),
    ('Adana Usulü Zeytinyağlı Nohutlu Ispanak', 'ZEYTİNYAĞI', 3),
    ('Adana Usulü Zeytinyağlı Nohutlu Ispanak', 'TUZ', 0.8),
    ('Yozgat Usulü Çullama', 'TAVUK GÖĞÜS', 80),
    ('Yozgat Usulü Çullama', 'YUFKA', 30),
    ('Yozgat Usulü Çullama', 'YOĞURT (TAM)', 40),
    ('Yozgat Usulü Çullama', 'TEREYAĞI', 6),
    ('Yozgat Usulü Çullama', 'TUZ', 0.8),
    ('Kırıkkale Usulü Yoğurtlu Erişte', 'MAKARNA', 60),
    ('Kırıkkale Usulü Yoğurtlu Erişte', 'YOĞURT (TAM)', 40),
    ('Kırıkkale Usulü Yoğurtlu Erişte', 'TEREYAĞI', 5),
    ('Kırıkkale Usulü Yoğurtlu Erişte', 'PUL BİBER', 0.5),
    ('Kırıkkale Usulü Yoğurtlu Erişte', 'SARIMSAK', 1.5),
    ('Kırıkkale Usulü Yoğurtlu Erişte', 'TUZ', 0.8),
    ('Çankırı Usulü Kuru Fasulye Yahnisi', 'KURU FASULYE', 50),
    ('Çankırı Usulü Kuru Fasulye Yahnisi', 'DANA KIYMA', 40),
    ('Çankırı Usulü Kuru Fasulye Yahnisi', 'KURU SOĞAN', 15),
    ('Çankırı Usulü Kuru Fasulye Yahnisi', 'DOMATES', 20),
    ('Çankırı Usulü Kuru Fasulye Yahnisi', 'TUZ', 1),
    ('Çankırı Usulü Kuru Fasulye Yahnisi', 'KARABİBER', 0.3),
    ('Karaman Usulü Etli Bamya', 'BAMYA', 50),
    ('Karaman Usulü Etli Bamya', 'KUZU ETİ (KOL)', 70),
    ('Karaman Usulü Etli Bamya', 'DOMATES', 25),
    ('Karaman Usulü Etli Bamya', 'KURU SOĞAN', 10),
    ('Karaman Usulü Etli Bamya', 'TUZ', 1),
    ('Karaman Usulü Etli Bamya', 'KARABİBER', 0.3),
    ('Nevşehir Usulü Üzümlü Bulgur Pilavı', 'BULGUR', 50),
    ('Nevşehir Usulü Üzümlü Bulgur Pilavı', 'KURU ÜZÜM', 10),
    ('Nevşehir Usulü Üzümlü Bulgur Pilavı', 'KURU SOĞAN', 10),
    ('Nevşehir Usulü Üzümlü Bulgur Pilavı', 'TEREYAĞI', 5),
    ('Nevşehir Usulü Üzümlü Bulgur Pilavı', 'TAVUK SUYU', 70),
    ('Nevşehir Usulü Üzümlü Bulgur Pilavı', 'TUZ', 0.8),
    ('Kayseri Usulü Cevizli Sucuk (Pekmezli)', 'ÜzÜM PEKMEZİ', 50),
    ('Kayseri Usulü Cevizli Sucuk (Pekmezli)', 'CEVİZ (İÇ)', 30),
    ('Kayseri Usulü Cevizli Sucuk (Pekmezli)', 'EKMEKLİK UN', 6),
    ('Sivas Usulü Kürtün Aşı', 'NOHUT', 30),
    ('Sivas Usulü Kürtün Aşı', 'MAKARNA', 20),
    ('Sivas Usulü Kürtün Aşı', 'TEREYAĞI', 4),
    ('Sivas Usulü Kürtün Aşı', 'PUL BİBER', 0.5),
    ('Sivas Usulü Kürtün Aşı', 'TUZ', 0.8),
    ('Konya Usulü Ballı Kadayıf', 'EKMEK KADAYIFI', 50),
    ('Konya Usulü Ballı Kadayıf', 'KAYMAK', 30),
    ('Konya Usulü Ballı Kadayıf', 'BAL', 20),
    ('Bolu Usulü Kestaneli Tavuk', 'TAVUK BUT', 90),
    ('Bolu Usulü Kestaneli Tavuk', 'KESTANE', 30),
    ('Bolu Usulü Kestaneli Tavuk', 'KURU SOĞAN', 10),
    ('Bolu Usulü Kestaneli Tavuk', 'TEREYAĞI', 4),
    ('Bolu Usulü Kestaneli Tavuk', 'TUZ', 0.8),
    ('Bolu Usulü Kestaneli Tavuk', 'KARABİBER', 0.3),
    ('Zonguldak Usulü Pancar Turşusu', 'PANCAR', 60),
    ('Zonguldak Usulü Pancar Turşusu', 'SİRKE', 6),
    ('Zonguldak Usulü Pancar Turşusu', 'TUZ', 4),
    ('Zonguldak Usulü Pancar Turşusu', 'SARIMSAK', 1.5),
    ('Sinop Usulü Balık Buğulama', 'İSTAVRİT', 100),
    ('Sinop Usulü Balık Buğulama', 'KURU SOĞAN', 10),
    ('Sinop Usulü Balık Buğulama', 'MAYDANOZ', 2),
    ('Sinop Usulü Balık Buğulama', 'ZEYTİNYAĞI', 3),
    ('Sinop Usulü Balık Buğulama', 'TUZ', 0.8),
    ('Amasya Usulü Elma Tatlısı', 'ELMA', 80),
    ('Amasya Usulü Elma Tatlısı', 'ŞEKER', 25),
    ('Amasya Usulü Elma Tatlısı', 'TARÇIN', 0.3),
    ('Tokat Usulü Kebabı (Patatesli, Fırında)', 'KUZU KIYMA', 70),
    ('Tokat Usulü Kebabı (Patatesli, Fırında)', 'PATATES', 50),
    ('Tokat Usulü Kebabı (Patatesli, Fırında)', 'DOMATES', 25),
    ('Tokat Usulü Kebabı (Patatesli, Fırında)', 'KURU SOĞAN', 10),
    ('Tokat Usulü Kebabı (Patatesli, Fırında)', 'TUZ', 1),
    ('Tokat Usulü Kebabı (Patatesli, Fırında)', 'KARABİBER', 0.3),
    ('Artvin Usulü Fasulye Pilaki', 'BARBUNYA', 50),
    ('Artvin Usulü Fasulye Pilaki', 'DOMATES', 20),
    ('Artvin Usulü Fasulye Pilaki', 'KURU SOĞAN', 10),
    ('Artvin Usulü Fasulye Pilaki', 'ZEYTİNYAĞI', 3),
    ('Artvin Usulü Fasulye Pilaki', 'ŞEKER', 0.5),
    ('Artvin Usulü Fasulye Pilaki', 'TUZ', 0.8),
    ('Ordu Usulü Fındıklı Tatlı', 'FINDIK (İÇ)', 40),
    ('Ordu Usulü Fındıklı Tatlı', 'ŞEKER', 20),
    ('Ordu Usulü Fındıklı Tatlı', 'SÜT (TAM YAĞ)', 30),
    ('Karadeniz Usulü Taze Fasulye Yemeği (Etli)', 'TAZE FASULYE', 60),
    ('Karadeniz Usulü Taze Fasulye Yemeği (Etli)', 'DANA KIYMA', 40),
    ('Karadeniz Usulü Taze Fasulye Yemeği (Etli)', 'KURU SOĞAN', 10),
    ('Karadeniz Usulü Taze Fasulye Yemeği (Etli)', 'DOMATES', 20),
    ('Karadeniz Usulü Taze Fasulye Yemeği (Etli)', 'TUZ', 0.8),
    ('Karadeniz Usulü Taze Fasulye Yemeği (Etli)', 'KARABİBER', 0.3),
    ('Erzurum Usulü Su Böreği', 'YUFKA', 50),
    ('Erzurum Usulü Su Böreği', 'KAŞAR PEYNİRİ', 30),
    ('Erzurum Usulü Su Böreği', 'TEREYAĞI', 8),
    ('Erzurum Usulü Su Böreği', 'TAVUK YUMURTASI', 15),
    ('Erzurum Usulü Su Böreği', 'TUZ', 0.8),
    ('Erzincan Usulü Çökelekli Yumurta', 'LOR PEYNİRİ', 30),
    ('Erzincan Usulü Çökelekli Yumurta', 'TAVUK YUMURTASI', 40),
    ('Erzincan Usulü Çökelekli Yumurta', 'TEREYAĞI', 4),
    ('Erzincan Usulü Çökelekli Yumurta', 'TUZ', 0.5),
    ('Van Usulü Otlu Peynirli Salata', 'OTLU PEYNİR', 30),
    ('Van Usulü Otlu Peynirli Salata', 'DOMATES', 30),
    ('Van Usulü Otlu Peynirli Salata', 'ROKA', 15),
    ('Van Usulü Otlu Peynirli Salata', 'ZEYTİNYAĞI', 2),
    ('Muş Usulü Zeytinyağlı Semizotu', 'SEMİZOTU', 50),
    ('Muş Usulü Zeytinyağlı Semizotu', 'PİRİNÇ (HAM)', 6),
    ('Muş Usulü Zeytinyağlı Semizotu', 'KURU SOĞAN', 10),
    ('Muş Usulü Zeytinyağlı Semizotu', 'ZEYTİNYAĞI', 3),
    ('Muş Usulü Zeytinyağlı Semizotu', 'TUZ', 0.8),
    ('Ağrı Usulü Kaz Eti Pilavı', 'KAZ ETİ (BUT, DERİSİZ, TUZ İLAVELİ)', 50),
    ('Ağrı Usulü Kaz Eti Pilavı', 'PİRİNÇ (HAM)', 40),
    ('Ağrı Usulü Kaz Eti Pilavı', 'TEREYAĞI', 5),
    ('Ağrı Usulü Kaz Eti Pilavı', 'TUZ', 0.6),
    ('Kars Usulü Kaşarlı Pilav', 'PİRİNÇ (HAM)', 50),
    ('Kars Usulü Kaşarlı Pilav', 'KAŞAR PEYNİRİ', 20),
    ('Kars Usulü Kaşarlı Pilav', 'TEREYAĞI', 5),
    ('Kars Usulü Kaşarlı Pilav', 'TAVUK SUYU', 70),
    ('Kars Usulü Kaşarlı Pilav', 'TUZ', 0.8),
    ('Bitlis Usulü Nohutlu Etli Çorba', 'NOHUT', 25),
    ('Bitlis Usulü Nohutlu Etli Çorba', 'DANA KIYMA', 30),
    ('Bitlis Usulü Nohutlu Etli Çorba', 'KURU SOĞAN', 10),
    ('Bitlis Usulü Nohutlu Etli Çorba', 'TAVUK SUYU', 80),
    ('Bitlis Usulü Nohutlu Etli Çorba', 'TUZ', 0.8),
    ('Bitlis Usulü Nohutlu Etli Çorba', 'KARABİBER', 0.3),
    ('Iğdır Usulü Kayısılı Komposto', 'KAYISI', 50),
    ('Iğdır Usulü Kayısılı Komposto', 'ŞEKER', 15),
    ('Iğdır Usulü Kayısılı Komposto', 'SU', 70),
    ('Gaziantep Usulü Beyran Çorbası', 'KUZU ETİ (KOL)', 50),
    ('Gaziantep Usulü Beyran Çorbası', 'PİRİNÇ (HAM)', 10),
    ('Gaziantep Usulü Beyran Çorbası', 'SARIMSAK', 2),
    ('Gaziantep Usulü Beyran Çorbası', 'TUZ', 1),
    ('Gaziantep Usulü Beyran Çorbası', 'KARABİBER', 0.3),
    ('Şanlıurfa Usulü Nohutlu Kuzu Güveç', 'KUZU ETİ (KOL)', 80),
    ('Şanlıurfa Usulü Nohutlu Kuzu Güveç', 'NOHUT', 25),
    ('Şanlıurfa Usulü Nohutlu Kuzu Güveç', 'KURU SOĞAN', 10),
    ('Şanlıurfa Usulü Nohutlu Kuzu Güveç', 'DOMATES', 20),
    ('Şanlıurfa Usulü Nohutlu Kuzu Güveç', 'TUZ', 1),
    ('Şanlıurfa Usulü Nohutlu Kuzu Güveç', 'KARABİBER', 0.3),
    ('Diyarbakır Usulü Kaburga Pilavı', 'SIĞIR KABURGA', 70),
    ('Diyarbakır Usulü Kaburga Pilavı', 'PİRİNÇ (HAM)', 40),
    ('Diyarbakır Usulü Kaburga Pilavı', 'KURU SOĞAN', 10),
    ('Diyarbakır Usulü Kaburga Pilavı', 'TUZ', 1),
    ('Diyarbakır Usulü Kaburga Pilavı', 'KARABİBER', 0.3),
    ('Mardin Usulü Zeytinyağlı Nohutlu Bulgur', 'BULGUR', 40),
    ('Mardin Usulü Zeytinyağlı Nohutlu Bulgur', 'NOHUT', 25),
    ('Mardin Usulü Zeytinyağlı Nohutlu Bulgur', 'KURU SOĞAN', 10),
    ('Mardin Usulü Zeytinyağlı Nohutlu Bulgur', 'ZEYTİNYAĞI', 3),
    ('Mardin Usulü Zeytinyağlı Nohutlu Bulgur', 'TUZ', 0.8),
    ('Siirt Usulü Kaburga Kavurma', 'SIĞIR KABURGA', 90),
    ('Siirt Usulü Kaburga Kavurma', 'KURU SOĞAN', 10),
    ('Siirt Usulü Kaburga Kavurma', 'TUZ', 1),
    ('Siirt Usulü Kaburga Kavurma', 'KARABİBER', 0.3),
    ('Batman Usulü Nohutlu Pilav', 'PİRİNÇ (HAM)', 50),
    ('Batman Usulü Nohutlu Pilav', 'NOHUT', 20),
    ('Batman Usulü Nohutlu Pilav', 'TEREYAĞI', 5),
    ('Batman Usulü Nohutlu Pilav', 'TAVUK SUYU', 70),
    ('Batman Usulü Nohutlu Pilav', 'TUZ', 0.8),
    ('Şırnak Usulü Etli Nohutlu Bulgur Pilavı', 'KUZU KIYMA', 50),
    ('Şırnak Usulü Etli Nohutlu Bulgur Pilavı', 'BULGUR', 30),
    ('Şırnak Usulü Etli Nohutlu Bulgur Pilavı', 'NOHUT', 20),
    ('Şırnak Usulü Etli Nohutlu Bulgur Pilavı', 'KURU SOĞAN', 10),
    ('Şırnak Usulü Etli Nohutlu Bulgur Pilavı', 'TUZ', 0.8),
    ('Şırnak Usulü Etli Nohutlu Bulgur Pilavı', 'KARABİBER', 0.3),
    ('Kilis Usulü Nar Ekşili Mercimek Çorbası', 'KIRMIZI MERCİMEK', 30),
    ('Kilis Usulü Nar Ekşili Mercimek Çorbası', 'KURU SOĞAN', 10),
    ('Kilis Usulü Nar Ekşili Mercimek Çorbası', 'NAR EKŞİSİ', 2),
    ('Kilis Usulü Nar Ekşili Mercimek Çorbası', 'TAVUK SUYU', 80),
    ('Kilis Usulü Nar Ekşili Mercimek Çorbası', 'TUZ', 0.8),
    ('Yalova Usulü Zeytinyağlı Kestane', 'KESTANE', 60),
    ('Yalova Usulü Zeytinyağlı Kestane', 'KURU SOĞAN', 10),
    ('Yalova Usulü Zeytinyağlı Kestane', 'ZEYTİNYAĞI', 3),
    ('Yalova Usulü Zeytinyağlı Kestane', 'ŞEKER', 0.5),
    ('Yalova Usulü Zeytinyağlı Kestane', 'TUZ', 0.8),
    ('Bilecik Usulü Etli Nohutlu Bulgur', 'DANA KIYMA', 50),
    ('Bilecik Usulü Etli Nohutlu Bulgur', 'NOHUT', 25),
    ('Bilecik Usulü Etli Nohutlu Bulgur', 'BULGUR', 20),
    ('Bilecik Usulü Etli Nohutlu Bulgur', 'KURU SOĞAN', 10),
    ('Bilecik Usulü Etli Nohutlu Bulgur', 'TUZ', 0.8),
    ('Bilecik Usulü Etli Nohutlu Bulgur', 'KARABİBER', 0.3),
    ('Sakarya Usulü Mısırlı Tavuk Güveç', 'TAVUK BUT', 80),
    ('Sakarya Usulü Mısırlı Tavuk Güveç', 'MISIR', 30),
    ('Sakarya Usulü Mısırlı Tavuk Güveç', 'DOMATES', 20),
    ('Sakarya Usulü Mısırlı Tavuk Güveç', 'KURU SOĞAN', 10),
    ('Sakarya Usulü Mısırlı Tavuk Güveç', 'TUZ', 0.8),
    ('Sakarya Usulü Mısırlı Tavuk Güveç', 'KARABİBER', 0.3),
    ('Çorlu Usulü Kaşarlı Tavuklu Makarna', 'MAKARNA', 60),
    ('Çorlu Usulü Kaşarlı Tavuklu Makarna', 'TAVUK GÖĞÜS', 40),
    ('Çorlu Usulü Kaşarlı Tavuklu Makarna', 'KAŞAR PEYNİRİ', 20),
    ('Çorlu Usulü Kaşarlı Tavuklu Makarna', 'TEREYAĞI', 5),
    ('Çorlu Usulü Kaşarlı Tavuklu Makarna', 'TUZ', 0.8),
    ('Bursa Usulü Cevizli Erik Tatlısı', 'ERİK', 60),
    ('Bursa Usulü Cevizli Erik Tatlısı', 'CEVİZ (İÇ)', 10),
    ('Bursa Usulü Cevizli Erik Tatlısı', 'ŞEKER', 20),
    ('İstanbul Usulü Zeytinyağlı Balkabağı', 'KABAK', 70),
    ('İstanbul Usulü Zeytinyağlı Balkabağı', 'KURU SOĞAN', 10),
    ('İstanbul Usulü Zeytinyağlı Balkabağı', 'ZEYTİNYAĞI', 3),
    ('İstanbul Usulü Zeytinyağlı Balkabağı', 'ŞEKER', 1),
    ('İstanbul Usulü Zeytinyağlı Balkabağı', 'TUZ', 0.8),
    ('Marmara Usulü Nohutlu Tavuk Çorbası', 'TAVUK GÖĞÜS', 30),
    ('Marmara Usulü Nohutlu Tavuk Çorbası', 'NOHUT', 20),
    ('Marmara Usulü Nohutlu Tavuk Çorbası', 'TAVUK SUYU', 90),
    ('Marmara Usulü Nohutlu Tavuk Çorbası', 'TUZ', 0.8),
    ('Marmara Usulü Nohutlu Tavuk Çorbası', 'KARABİBER', 0.3),
    ('Marmara Usulü Armutlu Ceviz Tatlısı', 'ARMUT (KIŞLIK, DEVECİ ÇEŞİDİ)', 60),
    ('Marmara Usulü Armutlu Ceviz Tatlısı', 'CEVİZ (İÇ)', 10),
    ('Marmara Usulü Armutlu Ceviz Tatlısı', 'BAL', 6),
    ('Manisa Usulü Mesir Macunlu Tatlı - basitleştirilmiş', 'BAL', 30),
    ('Manisa Usulü Mesir Macunlu Tatlı - basitleştirilmiş', 'CEVİZ (İÇ)', 15),
    ('Manisa Usulü Mesir Macunlu Tatlı - basitleştirilmiş', 'TARÇIN', 0.3),
    ('Denizli Usulü Keşkek (Tavuklu)', 'TAVUK BUT', 80),
    ('Denizli Usulü Keşkek (Tavuklu)', 'BULGUR', 40),
    ('Denizli Usulü Keşkek (Tavuklu)', 'KURU SOĞAN', 10),
    ('Denizli Usulü Keşkek (Tavuklu)', 'TEREYAĞI', 5),
    ('Denizli Usulü Keşkek (Tavuklu)', 'TUZ', 1),
    ('Denizli Usulü Keşkek (Tavuklu)', 'KARABİBER', 0.3),
    ('Uşak Usulü Zeytinyağlı Nohutlu Havuç', 'HAVUÇ', 50),
    ('Uşak Usulü Zeytinyağlı Nohutlu Havuç', 'NOHUT', 20),
    ('Uşak Usulü Zeytinyağlı Nohutlu Havuç', 'KURU SOĞAN', 10),
    ('Uşak Usulü Zeytinyağlı Nohutlu Havuç', 'ZEYTİNYAĞI', 3),
    ('Uşak Usulü Zeytinyağlı Nohutlu Havuç', 'TUZ', 0.8),
    ('Ayvalık Usulü Zeytinli Ekmek Salatası', 'EKMEK (BEYAZ)', 30),
    ('Ayvalık Usulü Zeytinli Ekmek Salatası', 'YEŞİL ZEYTİN', 15),
    ('Ayvalık Usulü Zeytinli Ekmek Salatası', 'DOMATES', 30),
    ('Ayvalık Usulü Zeytinli Ekmek Salatası', 'ZEYTİNYAĞI', 3),
    ('Ayvalık Usulü Zeytinli Ekmek Salatası', 'TUZ', 0.5),
    ('Urla Usulü Karidesli Zeytinyağlı Enginar', 'ENGİNAR', 40),
    ('Urla Usulü Karidesli Zeytinyağlı Enginar', 'KARİDES', 30),
    ('Urla Usulü Karidesli Zeytinyağlı Enginar', 'KURU SOĞAN', 10),
    ('Urla Usulü Karidesli Zeytinyağlı Enginar', 'ZEYTİNYAĞI', 3),
    ('Urla Usulü Karidesli Zeytinyağlı Enginar', 'TUZ', 0.8),
    ('Tire Usulü Köftesi (Fırında)', 'DANA KIYMA', 90),
    ('Tire Usulü Köftesi (Fırında)', 'PATATES', 40),
    ('Tire Usulü Köftesi (Fırında)', 'DOMATES', 30),
    ('Tire Usulü Köftesi (Fırında)', 'KURU SOĞAN', 10),
    ('Tire Usulü Köftesi (Fırında)', 'TUZ', 1),
    ('Tire Usulü Köftesi (Fırında)', 'KARABİBER', 0.3),
    ('Ödemiş Usulü Patatesli Tavuk Sote', 'TAVUK BUT', 80),
    ('Ödemiş Usulü Patatesli Tavuk Sote', 'PATATES', 40),
    ('Ödemiş Usulü Patatesli Tavuk Sote', 'KURU SOĞAN', 10),
    ('Ödemiş Usulü Patatesli Tavuk Sote', 'ZEYTİNYAĞI', 3),
    ('Ödemiş Usulü Patatesli Tavuk Sote', 'TUZ', 0.8),
    ('Ödemiş Usulü Patatesli Tavuk Sote', 'KARABİBER', 0.3),
    ('Kütahya Usulü Kirazlı Yoğurt', 'YOĞURT (TAM)', 50),
    ('Kütahya Usulü Kirazlı Yoğurt', 'KİRAZ', 40),
    ('Kütahya Usulü Kirazlı Yoğurt', 'ŞEKER', 10),
    ('Isparta Usulü Gül Reçelli Yoğurt Tatlısı', 'YOĞURT (TAM)', 50),
    ('Isparta Usulü Gül Reçelli Yoğurt Tatlısı', 'BAL', 15),
    ('Isparta Usulü Gül Reçelli Yoğurt Tatlısı', 'CEVİZ (İÇ)', 6),
    ('Burdur Usulü Etli Nohutlu Pilav', 'DANA KIYMA', 50),
    ('Burdur Usulü Etli Nohutlu Pilav', 'PİRİNÇ (HAM)', 40),
    ('Burdur Usulü Etli Nohutlu Pilav', 'NOHUT', 15),
    ('Burdur Usulü Etli Nohutlu Pilav', 'KURU SOĞAN', 10),
    ('Burdur Usulü Etli Nohutlu Pilav', 'TUZ', 0.8),
    ('Burdur Usulü Etli Nohutlu Pilav', 'KARABİBER', 0.3),
    ('Osmaniye Usulü Zeytinyağlı Yer Fıstıklı Salata', 'MARUL', 25),
    ('Osmaniye Usulü Zeytinyağlı Yer Fıstıklı Salata', 'FINDIK (İÇ)', 10),
    ('Osmaniye Usulü Zeytinyağlı Yer Fıstıklı Salata', 'ZEYTİNYAĞI', 2.5),
    ('Osmaniye Usulü Zeytinyağlı Yer Fıstıklı Salata', 'LİMON SUYU', 1.5),
    ('Osmaniye Usulü Zeytinyağlı Yer Fıstıklı Salata', 'TUZ', 0.5),
    ('Tarsus Usulü Şalgamlı Köfte - basitleştirilmiş (Şalgam Hariç)', 'KUZU KIYMA', 90),
    ('Tarsus Usulü Şalgamlı Köfte - basitleştirilmiş (Şalgam Hariç)', 'KURU SOĞAN', 10),
    ('Tarsus Usulü Şalgamlı Köfte - basitleştirilmiş (Şalgam Hariç)', 'KİMYON', 0.5),
    ('Tarsus Usulü Şalgamlı Köfte - basitleştirilmiş (Şalgam Hariç)', 'TUZ', 1),
    ('Tarsus Usulü Şalgamlı Köfte - basitleştirilmiş (Şalgam Hariç)', 'KARABİBER', 0.3),
    ('Manavgat Usulü Izgara Levrek', 'LEVREK', 150),
    ('Manavgat Usulü Izgara Levrek', 'ZEYTİNYAĞI', 3),
    ('Manavgat Usulü Izgara Levrek', 'LİMON SUYU', 2),
    ('Manavgat Usulü Izgara Levrek', 'TUZ', 0.8),
    ('Side Usulü Zeytinyağlı Enginar Turşusu', 'ENGİNAR', 50),
    ('Side Usulü Zeytinyağlı Enginar Turşusu', 'SİRKE', 5),
    ('Side Usulü Zeytinyağlı Enginar Turşusu', 'TUZ', 3.5),
    ('Side Usulü Zeytinyağlı Enginar Turşusu', 'SARIMSAK', 1.5),
    ('Kumluca Usulü Zeytinyağlı Domates Yemeği', 'DOMATES', 70),
    ('Kumluca Usulü Zeytinyağlı Domates Yemeği', 'KURU SOĞAN', 10),
    ('Kumluca Usulü Zeytinyağlı Domates Yemeği', 'ZEYTİNYAĞI', 3),
    ('Kumluca Usulü Zeytinyağlı Domates Yemeği', 'ŞEKER', 0.5),
    ('Kumluca Usulü Zeytinyağlı Domates Yemeği', 'TUZ', 0.8),
    ('Antalya Usulü Portakallı Tavuk Sote', 'TAVUK GÖĞÜS', 90),
    ('Antalya Usulü Portakallı Tavuk Sote', 'PORTAKAL', 30),
    ('Antalya Usulü Portakallı Tavuk Sote', 'KURU SOĞAN', 10),
    ('Antalya Usulü Portakallı Tavuk Sote', 'ZEYTİNYAĞI', 3),
    ('Antalya Usulü Portakallı Tavuk Sote', 'TUZ', 0.8),
    ('Antalya Usulü Portakallı Tavuk Sote', 'KARABİBER', 0.3),
    ('Eskişehir Usulü Çibörek (Kızartma)', 'EKMEKLİK UN', 50),
    ('Eskişehir Usulü Çibörek (Kızartma)', 'DANA KIYMA', 50),
    ('Eskişehir Usulü Çibörek (Kızartma)', 'KURU SOĞAN', 10),
    ('Eskişehir Usulü Çibörek (Kızartma)', 'MISIR YAĞI', 30),
    ('Eskişehir Usulü Çibörek (Kızartma)', 'TUZ', 0.8),
    ('Eskişehir Usulü Çibörek (Kızartma)', 'KARABİBER', 0.3),
    ('Kayseri Usulü Etli Ekmek (İnce)', 'EKMEKLİK UN', 70),
    ('Kayseri Usulü Etli Ekmek (İnce)', 'KUZU KIYMA', 60),
    ('Kayseri Usulü Etli Ekmek (İnce)', 'DOMATES', 20),
    ('Kayseri Usulü Etli Ekmek (İnce)', 'KURU SOĞAN', 10),
    ('Kayseri Usulü Etli Ekmek (İnce)', 'TUZ', 0.8),
    ('Kayseri Usulü Etli Ekmek (İnce)', 'PUL BİBER', 0.5),
    ('Ankara Usulü Zeytinyağlı Havuç ve Nohut', 'HAVUÇ', 50),
    ('Ankara Usulü Zeytinyağlı Havuç ve Nohut', 'NOHUT', 25),
    ('Ankara Usulü Zeytinyağlı Havuç ve Nohut', 'KURU SOĞAN', 10),
    ('Ankara Usulü Zeytinyağlı Havuç ve Nohut', 'ZEYTİNYAĞI', 3),
    ('Ankara Usulü Zeytinyağlı Havuç ve Nohut', 'TUZ', 0.8),
    ('Konya Usulü Etli Nohutlu Yahni', 'KUZU ETİ (KOL)', 80),
    ('Konya Usulü Etli Nohutlu Yahni', 'NOHUT', 30),
    ('Konya Usulü Etli Nohutlu Yahni', 'KURU SOĞAN', 15),
    ('Konya Usulü Etli Nohutlu Yahni', 'TUZ', 1),
    ('Konya Usulü Etli Nohutlu Yahni', 'KARABİBER', 0.3),
    ('Nevşehir Usulü Elmalı Kabaklı Tatlı', 'ELMA', 40),
    ('Nevşehir Usulü Elmalı Kabaklı Tatlı', 'KABAK', 40),
    ('Nevşehir Usulü Elmalı Kabaklı Tatlı', 'ŞEKER', 25),
    ('Nevşehir Usulü Elmalı Kabaklı Tatlı', 'CEVİZ (İÇ)', 6),
    ('Sivas Usulü Mantısı (Küçük Boy)', 'EKMEKLİK UN', 70),
    ('Sivas Usulü Mantısı (Küçük Boy)', 'KUZU KIYMA', 50),
    ('Sivas Usulü Mantısı (Küçük Boy)', 'KURU SOĞAN', 15),
    ('Sivas Usulü Mantısı (Küçük Boy)', 'YOĞURT (TAM)', 60),
    ('Sivas Usulü Mantısı (Küçük Boy)', 'SARIMSAK', 2),
    ('Sivas Usulü Mantısı (Küçük Boy)', 'TEREYAĞI', 8),
    ('Sivas Usulü Mantısı (Küçük Boy)', 'TUZ', 1),
    ('Yozgat Usulü Zeytinyağlı Kuru Fasulye', 'KURU FASULYE', 50),
    ('Yozgat Usulü Zeytinyağlı Kuru Fasulye', 'KURU SOĞAN', 10),
    ('Yozgat Usulü Zeytinyağlı Kuru Fasulye', 'DOMATES', 20),
    ('Yozgat Usulü Zeytinyağlı Kuru Fasulye', 'ZEYTİNYAĞI', 3),
    ('Yozgat Usulü Zeytinyağlı Kuru Fasulye', 'TUZ', 0.8),
    ('Kırşehir Usulü Nohutlu Ispanak Çorbası', 'NOHUT', 20),
    ('Kırşehir Usulü Nohutlu Ispanak Çorbası', 'ISPANAK', 30),
    ('Kırşehir Usulü Nohutlu Ispanak Çorbası', 'TAVUK SUYU', 80),
    ('Kırşehir Usulü Nohutlu Ispanak Çorbası', 'TEREYAĞI', 3),
    ('Kırşehir Usulü Nohutlu Ispanak Çorbası', 'TUZ', 0.8),
    ('Gümüşhane Usulü Kuru Fasulye (Etli)', 'KURU FASULYE', 50),
    ('Gümüşhane Usulü Kuru Fasulye (Etli)', 'DANA KIYMA', 40),
    ('Gümüşhane Usulü Kuru Fasulye (Etli)', 'KURU SOĞAN', 15),
    ('Gümüşhane Usulü Kuru Fasulye (Etli)', 'DOMATES', 20),
    ('Gümüşhane Usulü Kuru Fasulye (Etli)', 'TUZ', 0.8),
    ('Gümüşhane Usulü Kuru Fasulye (Etli)', 'KARABİBER', 0.3),
    ('Kastamonu Usulü Tarhana Çorbası', 'TARHANA', 20),
    ('Kastamonu Usulü Tarhana Çorbası', 'TAVUK SUYU', 120),
    ('Kastamonu Usulü Tarhana Çorbası', 'TEREYAĞI', 3),
    ('Kastamonu Usulü Tarhana Çorbası', 'TUZ', 0.6),
    ('Bartın Usulü Pancarlı Pilav', 'PANCAR', 30),
    ('Bartın Usulü Pancarlı Pilav', 'PİRİNÇ (HAM)', 50),
    ('Bartın Usulü Pancarlı Pilav', 'TEREYAĞI', 5),
    ('Bartın Usulü Pancarlı Pilav', 'TAVUK SUYU', 70),
    ('Bartın Usulü Pancarlı Pilav', 'TUZ', 0.8),
    ('Karabük Usulü Etli Lahana Sarması', 'LAHANA', 70),
    ('Karabük Usulü Etli Lahana Sarması', 'PİRİNÇ (HAM)', 25),
    ('Karabük Usulü Etli Lahana Sarması', 'DANA KIYMA', 50),
    ('Karabük Usulü Etli Lahana Sarması', 'KURU SOĞAN', 10),
    ('Karabük Usulü Etli Lahana Sarması', 'TUZ', 0.8),
    ('Karabük Usulü Etli Lahana Sarması', 'KARABİBER', 0.3),
    ('Samsun Usulü Zeytinyağlı Karalahana', 'KARALAHANA', 60),
    ('Samsun Usulü Zeytinyağlı Karalahana', 'PİRİNÇ (HAM)', 6),
    ('Samsun Usulü Zeytinyağlı Karalahana', 'KURU SOĞAN', 10),
    ('Samsun Usulü Zeytinyağlı Karalahana', 'ZEYTİNYAĞI', 3),
    ('Samsun Usulü Zeytinyağlı Karalahana', 'TUZ', 0.8),
    ('Trabzon Usulü Vişne Ekşili Kuzu Yahnisi', 'KUZU ETİ (KOL)', 90),
    ('Trabzon Usulü Vişne Ekşili Kuzu Yahnisi', 'VİŞNE', 20),
    ('Trabzon Usulü Vişne Ekşili Kuzu Yahnisi', 'KURU SOĞAN', 10),
    ('Trabzon Usulü Vişne Ekşili Kuzu Yahnisi', 'TUZ', 0.8),
    ('Trabzon Usulü Vişne Ekşili Kuzu Yahnisi', 'KARABİBER', 0.3),
    ('Giresun Usulü Mısır Ekmekli Peynirli Tabak', 'MISIR UNU', 20),
    ('Giresun Usulü Mısır Ekmekli Peynirli Tabak', 'KAŞAR PEYNİRİ', 30),
    ('Giresun Usulü Mısır Ekmekli Peynirli Tabak', 'TEREYAĞI', 4),
    ('Ordu Usulü Fındıklı Yoğurtlu Havuç Salatası', 'HAVUÇ', 40),
    ('Ordu Usulü Fındıklı Yoğurtlu Havuç Salatası', 'FINDIK (İÇ)', 8),
    ('Ordu Usulü Fındıklı Yoğurtlu Havuç Salatası', 'YOĞURT (TAM)', 30),
    ('Ordu Usulü Fındıklı Yoğurtlu Havuç Salatası', 'SARIMSAK', 1),
    ('Bingöl Usulü Kuzu Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Bingöl Usulü Kuzu Kavurma', 'KURU SOĞAN', 10),
    ('Bingöl Usulü Kuzu Kavurma', 'TUZ', 1),
    ('Bingöl Usulü Kuzu Kavurma', 'KARABİBER', 0.3),
    ('Tunceli Usulü Mırığı (Yoğurtlu Bulgur Aşı)', 'BULGUR', 50),
    ('Tunceli Usulü Mırığı (Yoğurtlu Bulgur Aşı)', 'YOĞURT (TAM)', 40),
    ('Tunceli Usulü Mırığı (Yoğurtlu Bulgur Aşı)', 'TEREYAĞI', 5),
    ('Tunceli Usulü Mırığı (Yoğurtlu Bulgur Aşı)', 'TUZ', 0.8),
    ('Hakkari Usulü Kuzu Etli Nohut Yemeği', 'KUZU ETİ (KOL)', 80),
    ('Hakkari Usulü Kuzu Etli Nohut Yemeği', 'NOHUT', 30),
    ('Hakkari Usulü Kuzu Etli Nohut Yemeği', 'KURU SOĞAN', 10),
    ('Hakkari Usulü Kuzu Etli Nohut Yemeği', 'TUZ', 1),
    ('Hakkari Usulü Kuzu Etli Nohut Yemeği', 'KARABİBER', 0.3),
    ('Ardahan Usulü Kaşarlı Kete', 'EKMEKLİK UN', 60),
    ('Ardahan Usulü Kaşarlı Kete', 'KAŞAR PEYNİRİ', 40),
    ('Ardahan Usulü Kaşarlı Kete', 'TEREYAĞI', 10),
    ('Ardahan Usulü Kaşarlı Kete', 'TUZ', 0.8),
    ('Van Usulü Balı ile Kaymaklı Tatlı', 'BAL', 30),
    ('Van Usulü Balı ile Kaymaklı Tatlı', 'KAYMAK', 30),
    ('Erzurum Usulü Zeytinyağlı Kuru Fasulye', 'KURU FASULYE', 50),
    ('Erzurum Usulü Zeytinyağlı Kuru Fasulye', 'KURU SOĞAN', 10),
    ('Erzurum Usulü Zeytinyağlı Kuru Fasulye', 'DOMATES', 20),
    ('Erzurum Usulü Zeytinyağlı Kuru Fasulye', 'ZEYTİNYAĞI', 3),
    ('Erzurum Usulü Zeytinyağlı Kuru Fasulye', 'TUZ', 0.8),
    ('Malatya Usulü Kayısılı Tavuk Sote', 'TAVUK GÖĞÜS', 90),
    ('Malatya Usulü Kayısılı Tavuk Sote', 'KAYISI', 30),
    ('Malatya Usulü Kayısılı Tavuk Sote', 'KURU SOĞAN', 10),
    ('Malatya Usulü Kayısılı Tavuk Sote', 'TUZ', 0.8),
    ('Malatya Usulü Kayısılı Tavuk Sote', 'KARABİBER', 0.3),
    ('Elazığ Usulü Nohutlu Bulgur Pilavı', 'BULGUR', 50),
    ('Elazığ Usulü Nohutlu Bulgur Pilavı', 'NOHUT', 25),
    ('Elazığ Usulü Nohutlu Bulgur Pilavı', 'TEREYAĞI', 5),
    ('Elazığ Usulü Nohutlu Bulgur Pilavı', 'TAVUK SUYU', 70),
    ('Elazığ Usulü Nohutlu Bulgur Pilavı', 'TUZ', 0.8),
    ('Adıyaman Usulü Etli Nohutlu Bulgur Köftesi', 'BULGUR', 30),
    ('Adıyaman Usulü Etli Nohutlu Bulgur Köftesi', 'DANA KIYMA', 60),
    ('Adıyaman Usulü Etli Nohutlu Bulgur Köftesi', 'NOHUT', 15),
    ('Adıyaman Usulü Etli Nohutlu Bulgur Köftesi', 'KURU SOĞAN', 10),
    ('Adıyaman Usulü Etli Nohutlu Bulgur Köftesi', 'TUZ', 0.8),
    ('Adıyaman Usulü Etli Nohutlu Bulgur Köftesi', 'KARABİBER', 0.3),
    ('Gaziantep Usulü Zeytinyağlı Nohutlu Pırasa', 'PIRASA', 50),
    ('Gaziantep Usulü Zeytinyağlı Nohutlu Pırasa', 'NOHUT', 20),
    ('Gaziantep Usulü Zeytinyağlı Nohutlu Pırasa', 'KURU SOĞAN', 10),
    ('Gaziantep Usulü Zeytinyağlı Nohutlu Pırasa', 'ZEYTİNYAĞI', 3),
    ('Gaziantep Usulü Zeytinyağlı Nohutlu Pırasa', 'TUZ', 0.8),
    ('Şanlıurfa Usulü İçli Köfte (Büyük Boy)', 'BULGUR', 50),
    ('Şanlıurfa Usulü İçli Köfte (Büyük Boy)', 'DANA KIYMA', 80),
    ('Şanlıurfa Usulü İçli Köfte (Büyük Boy)', 'KURU SOĞAN', 20),
    ('Şanlıurfa Usulü İçli Köfte (Büyük Boy)', 'CEVİZ (İÇ)', 10),
    ('Şanlıurfa Usulü İçli Köfte (Büyük Boy)', 'PUL BİBER', 0.5),
    ('Şanlıurfa Usulü İçli Köfte (Büyük Boy)', 'TUZ', 1),
    ('Diyarbakır Usulü Etli Nohutlu Şiveydiz - basitleştirilmiş', 'KUZU ETİ (KOL)', 70),
    ('Diyarbakır Usulü Etli Nohutlu Şiveydiz - basitleştirilmiş', 'TAZE SOĞAN', 30),
    ('Diyarbakır Usulü Etli Nohutlu Şiveydiz - basitleştirilmiş', 'NOHUT', 15),
    ('Diyarbakır Usulü Etli Nohutlu Şiveydiz - basitleştirilmiş', 'TUZ', 0.8),
    ('Diyarbakır Usulü Etli Nohutlu Şiveydiz - basitleştirilmiş', 'KARABİBER', 0.3),
    ('Mardin Usulü Kaburgalı Nohut Çorbası', 'SIĞIR KABURGA', 50),
    ('Mardin Usulü Kaburgalı Nohut Çorbası', 'NOHUT', 25),
    ('Mardin Usulü Kaburgalı Nohut Çorbası', 'KURU SOĞAN', 10),
    ('Mardin Usulü Kaburgalı Nohut Çorbası', 'TUZ', 0.8),
    ('Mardin Usulü Kaburgalı Nohut Çorbası', 'KARABİBER', 0.3),
    ('Siirt Usulü Zeytinyağlı Nohutlu Patlıcan', 'PATLICAN', 50),
    ('Siirt Usulü Zeytinyağlı Nohutlu Patlıcan', 'NOHUT', 20),
    ('Siirt Usulü Zeytinyağlı Nohutlu Patlıcan', 'DOMATES', 25),
    ('Siirt Usulü Zeytinyağlı Nohutlu Patlıcan', 'KURU SOĞAN', 10),
    ('Siirt Usulü Zeytinyağlı Nohutlu Patlıcan', 'ZEYTİNYAĞI', 3),
    ('Siirt Usulü Zeytinyağlı Nohutlu Patlıcan', 'TUZ', 0.8),
    ('Batman Usulü Kaşarlı Kuzu Güveç', 'KUZU ETİ (KOL)', 90),
    ('Batman Usulü Kaşarlı Kuzu Güveç', 'KAŞAR PEYNİRİ', 15),
    ('Batman Usulü Kaşarlı Kuzu Güveç', 'KURU SOĞAN', 10),
    ('Batman Usulü Kaşarlı Kuzu Güveç', 'TUZ', 0.8),
    ('Batman Usulü Kaşarlı Kuzu Güveç', 'KARABİBER', 0.3),
    ('Kilis Usulü Zeytinyağlı Biberli Bulgur', 'BULGUR', 40),
    ('Kilis Usulü Zeytinyağlı Biberli Bulgur', 'YEŞİL BİBER', 30),
    ('Kilis Usulü Zeytinyağlı Biberli Bulgur', 'DOMATES', 25),
    ('Kilis Usulü Zeytinyağlı Biberli Bulgur', 'KURU SOĞAN', 10),
    ('Kilis Usulü Zeytinyağlı Biberli Bulgur', 'ZEYTİNYAĞI', 3),
    ('Kilis Usulü Zeytinyağlı Biberli Bulgur', 'TUZ', 0.8),
    ('İstanbul Usulü Midye Salatası', 'MİDYE', 70),
    ('İstanbul Usulü Midye Salatası', 'MARUL', 20),
    ('İstanbul Usulü Midye Salatası', 'ZEYTİNYAĞI', 3),
    ('İstanbul Usulü Midye Salatası', 'LİMON SUYU', 2),
    ('İstanbul Usulü Midye Salatası', 'TUZ', 0.8),
    ('Bursa Usulü Zeytinyağlı Kereviz', 'KEREVİZ', 60),
    ('Bursa Usulü Zeytinyağlı Kereviz', 'HAVUÇ', 20),
    ('Bursa Usulü Zeytinyağlı Kereviz', 'KURU SOĞAN', 10),
    ('Bursa Usulü Zeytinyağlı Kereviz', 'ZEYTİNYAĞI', 3),
    ('Bursa Usulü Zeytinyağlı Kereviz', 'ŞEKER', 0.5),
    ('Bursa Usulü Zeytinyağlı Kereviz', 'TUZ', 0.8),
    ('Kırklareli Usulü Kavurmalı Yumurta', 'DANA KIYMA', 30),
    ('Kırklareli Usulü Kavurmalı Yumurta', 'TAVUK YUMURTASI', 40),
    ('Kırklareli Usulü Kavurmalı Yumurta', 'TEREYAĞI', 4),
    ('Kırklareli Usulü Kavurmalı Yumurta', 'TUZ', 0.6),
    ('Tekirdağ Usulü Fırın Sütlaç', 'SÜT (TAM YAĞ)', 120),
    ('Tekirdağ Usulü Fırın Sütlaç', 'PİRİNÇ (HAM)', 10),
    ('Tekirdağ Usulü Fırın Sütlaç', 'ŞEKER', 25),
    ('Tekirdağ Usulü Fırın Sütlaç', 'MISIR NİŞASTASI', 4),
    ('Çanakkale Usulü Zeytinyağlı Taze Fasulye', 'TAZE FASULYE', 60),
    ('Çanakkale Usulü Zeytinyağlı Taze Fasulye', 'DOMATES', 20),
    ('Çanakkale Usulü Zeytinyağlı Taze Fasulye', 'KURU SOĞAN', 10),
    ('Çanakkale Usulü Zeytinyağlı Taze Fasulye', 'ZEYTİNYAĞI', 3),
    ('Çanakkale Usulü Zeytinyağlı Taze Fasulye', 'ŞEKER', 0.5),
    ('Çanakkale Usulü Zeytinyağlı Taze Fasulye', 'TUZ', 0.8),
    ('Balıkesir Usulü Zeytinyağlı Enginarlı Bezelye', 'BEZELYE', 40),
    ('Balıkesir Usulü Zeytinyağlı Enginarlı Bezelye', 'ENGİNAR', 30),
    ('Balıkesir Usulü Zeytinyağlı Enginarlı Bezelye', 'KURU SOĞAN', 10),
    ('Balıkesir Usulü Zeytinyağlı Enginarlı Bezelye', 'ZEYTİNYAĞI', 3),
    ('Balıkesir Usulü Zeytinyağlı Enginarlı Bezelye', 'ŞEKER', 0.5),
    ('Balıkesir Usulü Zeytinyağlı Enginarlı Bezelye', 'TUZ', 0.8),
    ('Marmara Usulü İncirli Kaşar Tabağı', 'KURU İNCİR', 30),
    ('Marmara Usulü İncirli Kaşar Tabağı', 'KAŞAR PEYNİRİ', 25),
    ('Marmara Usulü İncirli Kaşar Tabağı', 'CEVİZ (İÇ)', 6),
    ('İstanbul Usulü Limonlu Tavuk Sote', 'TAVUK GÖĞÜS', 90),
    ('İstanbul Usulü Limonlu Tavuk Sote', 'LİMON SUYU', 4),
    ('İstanbul Usulü Limonlu Tavuk Sote', 'SARIMSAK', 1.5),
    ('İstanbul Usulü Limonlu Tavuk Sote', 'ZEYTİNYAĞI', 3),
    ('İstanbul Usulü Limonlu Tavuk Sote', 'TUZ', 0.8),
    ('İstanbul Usulü Limonlu Tavuk Sote', 'KARABİBER', 0.3),
    ('İzmir Usulü Zeytinyağlı Nohutlu Enginar', 'ENGİNAR', 40),
    ('İzmir Usulü Zeytinyağlı Nohutlu Enginar', 'NOHUT', 20),
    ('İzmir Usulü Zeytinyağlı Nohutlu Enginar', 'KURU SOĞAN', 10),
    ('İzmir Usulü Zeytinyağlı Nohutlu Enginar', 'ZEYTİNYAĞI', 3),
    ('İzmir Usulü Zeytinyağlı Nohutlu Enginar', 'TUZ', 0.8),
    ('Muğla Usulü Bal Kaymaklı Kahvaltı Tabağı', 'BAL', 30),
    ('Muğla Usulü Bal Kaymaklı Kahvaltı Tabağı', 'KAYMAK', 30),
    ('Datça Usulü Bademli Zeytinyağlı Salata', 'MARUL', 25),
    ('Datça Usulü Bademli Zeytinyağlı Salata', 'BADEM', 8),
    ('Datça Usulü Bademli Zeytinyağlı Salata', 'ZEYTİNYAĞI', 2.5),
    ('Datça Usulü Bademli Zeytinyağlı Salata', 'LİMON SUYU', 1.5),
    ('Fethiye Usulü Izgara Karides', 'KARİDES', 100),
    ('Fethiye Usulü Izgara Karides', 'ZEYTİNYAĞI', 3),
    ('Fethiye Usulü Izgara Karides', 'SARIMSAK', 1.5),
    ('Fethiye Usulü Izgara Karides', 'LİMON SUYU', 2),
    ('Fethiye Usulü Izgara Karides', 'TUZ', 0.8),
    ('Salihli Usulü Üzümlü Pilav', 'PİRİNÇ (HAM)', 50),
    ('Salihli Usulü Üzümlü Pilav', 'KURU ÜZÜM', 10),
    ('Salihli Usulü Üzümlü Pilav', 'TEREYAĞI', 5),
    ('Salihli Usulü Üzümlü Pilav', 'TAVUK SUYU', 70),
    ('Salihli Usulü Üzümlü Pilav', 'TUZ', 0.8),
    ('Nazilli Usulü Etli Nohutlu Bamya', 'KUZU ETİ (KOL)', 70),
    ('Nazilli Usulü Etli Nohutlu Bamya', 'BAMYA', 40),
    ('Nazilli Usulü Etli Nohutlu Bamya', 'NOHUT', 15),
    ('Nazilli Usulü Etli Nohutlu Bamya', 'KURU SOĞAN', 10),
    ('Nazilli Usulü Etli Nohutlu Bamya', 'TUZ', 0.8),
    ('Nazilli Usulü Etli Nohutlu Bamya', 'KARABİBER', 0.3),
    ('Dikili Usulü Zeytinyağlı Semizotu', 'SEMİZOTU', 50),
    ('Dikili Usulü Zeytinyağlı Semizotu', 'PİRİNÇ (HAM)', 6),
    ('Dikili Usulü Zeytinyağlı Semizotu', 'KURU SOĞAN', 10),
    ('Dikili Usulü Zeytinyağlı Semizotu', 'ZEYTİNYAĞI', 3),
    ('Dikili Usulü Zeytinyağlı Semizotu', 'TUZ', 0.8),
    ('İzmir Usulü Üzümlü Komposto', 'ÜZÜM', 50),
    ('İzmir Usulü Üzümlü Komposto', 'ŞEKER', 10),
    ('İzmir Usulü Üzümlü Komposto', 'SU', 70),
    ('Antalya Usulü Zeytinyağlı Kereviz', 'KEREVİZ', 60),
    ('Antalya Usulü Zeytinyağlı Kereviz', 'HAVUÇ', 20),
    ('Antalya Usulü Zeytinyağlı Kereviz', 'KURU SOĞAN', 10),
    ('Antalya Usulü Zeytinyağlı Kereviz', 'ZEYTİNYAĞI', 3),
    ('Antalya Usulü Zeytinyağlı Kereviz', 'ŞEKER', 0.5),
    ('Antalya Usulü Zeytinyağlı Kereviz', 'TUZ', 0.8),
    ('Mersin Usulü Etli Bamya', 'KUZU ETİ (KOL)', 70),
    ('Mersin Usulü Etli Bamya', 'BAMYA', 50),
    ('Mersin Usulü Etli Bamya', 'DOMATES', 25),
    ('Mersin Usulü Etli Bamya', 'KURU SOĞAN', 10),
    ('Mersin Usulü Etli Bamya', 'TUZ', 0.8),
    ('Mersin Usulü Etli Bamya', 'KARABİBER', 0.3),
    ('Adana Usulü Nohutlu Kavurma', 'DANA KIYMA', 70),
    ('Adana Usulü Nohutlu Kavurma', 'NOHUT', 25),
    ('Adana Usulü Nohutlu Kavurma', 'KURU SOĞAN', 10),
    ('Adana Usulü Nohutlu Kavurma', 'TUZ', 0.8),
    ('Adana Usulü Nohutlu Kavurma', 'KARABİBER', 0.3),
    ('Hatay Usulü Zeytinyağlı Enginar', 'ENGİNAR', 50),
    ('Hatay Usulü Zeytinyağlı Enginar', 'KURU SOĞAN', 10),
    ('Hatay Usulü Zeytinyağlı Enginar', 'ZEYTİNYAĞI', 3),
    ('Hatay Usulü Zeytinyağlı Enginar', 'LİMON SUYU', 1.5),
    ('Hatay Usulü Zeytinyağlı Enginar', 'TUZ', 0.8),
    ('Silifke Usulü Zeytinyağlı Taze Bakla', 'BAKLA', 50),
    ('Silifke Usulü Zeytinyağlı Taze Bakla', 'KURU SOĞAN', 10),
    ('Silifke Usulü Zeytinyağlı Taze Bakla', 'TAZE DEREOTU', 1.5),
    ('Silifke Usulü Zeytinyağlı Taze Bakla', 'ZEYTİNYAĞI', 3),
    ('Silifke Usulü Zeytinyağlı Taze Bakla', 'TUZ', 0.8),
    ('Antalya Usulü Portakallı Muhallebi', 'SÜT (TAM YAĞ)', 100),
    ('Antalya Usulü Portakallı Muhallebi', 'PORTAKAL', 20),
    ('Antalya Usulü Portakallı Muhallebi', 'ŞEKER', 20),
    ('Antalya Usulü Portakallı Muhallebi', 'MISIR NİŞASTASI', 6),
    ('Kahramanmaraş Usulü Etli Nohutlu Bulgur', 'KUZU KIYMA', 60),
    ('Kahramanmaraş Usulü Etli Nohutlu Bulgur', 'BULGUR', 30),
    ('Kahramanmaraş Usulü Etli Nohutlu Bulgur', 'NOHUT', 20),
    ('Kahramanmaraş Usulü Etli Nohutlu Bulgur', 'KURU SOĞAN', 10),
    ('Kahramanmaraş Usulü Etli Nohutlu Bulgur', 'TUZ', 0.8),
    ('Kahramanmaraş Usulü Etli Nohutlu Bulgur', 'KARABİBER', 0.3),
    ('Osmaniye Usulü Zeytinyağlı Taze Fasulye', 'TAZE FASULYE', 60),
    ('Osmaniye Usulü Zeytinyağlı Taze Fasulye', 'DOMATES', 25),
    ('Osmaniye Usulü Zeytinyağlı Taze Fasulye', 'KURU SOĞAN', 10),
    ('Osmaniye Usulü Zeytinyağlı Taze Fasulye', 'ZEYTİNYAĞI', 3),
    ('Osmaniye Usulü Zeytinyağlı Taze Fasulye', 'ŞEKER', 0.5),
    ('Osmaniye Usulü Zeytinyağlı Taze Fasulye', 'TUZ', 0.8),
    ('Ankara Usulü Etli Nohutlu Bulgur Pilavı', 'DANA KIYMA', 50),
    ('Ankara Usulü Etli Nohutlu Bulgur Pilavı', 'BULGUR', 30),
    ('Ankara Usulü Etli Nohutlu Bulgur Pilavı', 'NOHUT', 20),
    ('Ankara Usulü Etli Nohutlu Bulgur Pilavı', 'KURU SOĞAN', 10),
    ('Ankara Usulü Etli Nohutlu Bulgur Pilavı', 'TUZ', 0.8),
    ('Ankara Usulü Etli Nohutlu Bulgur Pilavı', 'KARABİBER', 0.3),
    ('Konya Usulü Zeytinyağlı Pırasa', 'PIRASA', 60),
    ('Konya Usulü Zeytinyağlı Pırasa', 'HAVUÇ', 15),
    ('Konya Usulü Zeytinyağlı Pırasa', 'KURU SOĞAN', 10),
    ('Konya Usulü Zeytinyağlı Pırasa', 'ZEYTİNYAĞI', 3),
    ('Konya Usulü Zeytinyağlı Pırasa', 'ŞEKER', 0.5),
    ('Konya Usulü Zeytinyağlı Pırasa', 'TUZ', 0.8),
    ('Kayseri Usulü Kavurmalı Yumurta', 'DANA KIYMA', 30),
    ('Kayseri Usulü Kavurmalı Yumurta', 'TAVUK YUMURTASI', 40),
    ('Kayseri Usulü Kavurmalı Yumurta', 'TEREYAĞI', 3),
    ('Kayseri Usulü Kavurmalı Yumurta', 'TUZ', 0.6),
    ('Sivas Usulü Zeytinyağlı Nohutlu Kabak', 'KABAK', 50),
    ('Sivas Usulü Zeytinyağlı Nohutlu Kabak', 'NOHUT', 20),
    ('Sivas Usulü Zeytinyağlı Nohutlu Kabak', 'KURU SOĞAN', 10),
    ('Sivas Usulü Zeytinyağlı Nohutlu Kabak', 'ZEYTİNYAĞI', 3),
    ('Sivas Usulü Zeytinyağlı Nohutlu Kabak', 'ŞEKER', 0.5),
    ('Sivas Usulü Zeytinyağlı Nohutlu Kabak', 'TUZ', 0.8),
    ('Niğde Usulü Elmalı Cevizli Tatlı', 'ELMA', 60),
    ('Niğde Usulü Elmalı Cevizli Tatlı', 'CEVİZ (İÇ)', 10),
    ('Niğde Usulü Elmalı Cevizli Tatlı', 'ŞEKER', 20),
    ('Aksaray Usulü Etli Kabak Yemeği', 'DANA KIYMA', 50),
    ('Aksaray Usulü Etli Kabak Yemeği', 'KABAK', 50),
    ('Aksaray Usulü Etli Kabak Yemeği', 'DOMATES', 20),
    ('Aksaray Usulü Etli Kabak Yemeği', 'KURU SOĞAN', 10),
    ('Aksaray Usulü Etli Kabak Yemeği', 'TUZ', 0.8),
    ('Aksaray Usulü Etli Kabak Yemeği', 'KARABİBER', 0.3),
    ('Kırşehir Usulü Zeytinyağlı Enginar', 'ENGİNAR', 50),
    ('Kırşehir Usulü Zeytinyağlı Enginar', 'HAVUÇ', 15),
    ('Kırşehir Usulü Zeytinyağlı Enginar', 'KURU SOĞAN', 10),
    ('Kırşehir Usulü Zeytinyağlı Enginar', 'ZEYTİNYAĞI', 3),
    ('Kırşehir Usulü Zeytinyağlı Enginar', 'TUZ', 0.8),
    ('Çorum Usulü Nohutlu Tavuk Sote', 'TAVUK BUT', 80),
    ('Çorum Usulü Nohutlu Tavuk Sote', 'NOHUT', 20),
    ('Çorum Usulü Nohutlu Tavuk Sote', 'KURU SOĞAN', 10),
    ('Çorum Usulü Nohutlu Tavuk Sote', 'TUZ', 0.8),
    ('Çorum Usulü Nohutlu Tavuk Sote', 'KARABİBER', 0.3),
    ('Trabzon Usulü Zeytinyağlı Kuru Fasulye', 'KURU FASULYE', 50),
    ('Trabzon Usulü Zeytinyağlı Kuru Fasulye', 'KURU SOĞAN', 10),
    ('Trabzon Usulü Zeytinyağlı Kuru Fasulye', 'DOMATES', 20),
    ('Trabzon Usulü Zeytinyağlı Kuru Fasulye', 'ZEYTİNYAĞI', 3),
    ('Trabzon Usulü Zeytinyağlı Kuru Fasulye', 'TUZ', 0.8),
    ('Rize Usulü Mısır Ekmekli Kaymak Tabağı', 'MISIR UNU', 15),
    ('Rize Usulü Mısır Ekmekli Kaymak Tabağı', 'KAYMAK', 25),
    ('Rize Usulü Mısır Ekmekli Kaymak Tabağı', 'BAL', 10),
    ('Samsun Usulü Etli Lahana Yemeği', 'LAHANA', 60),
    ('Samsun Usulü Etli Lahana Yemeği', 'DANA KIYMA', 40),
    ('Samsun Usulü Etli Lahana Yemeği', 'KURU SOĞAN', 10),
    ('Samsun Usulü Etli Lahana Yemeği', 'TUZ', 0.8),
    ('Samsun Usulü Etli Lahana Yemeği', 'KARABİBER', 0.3),
    ('Giresun Usulü Fındıklı Muhallebi', 'SÜT (TAM YAĞ)', 100),
    ('Giresun Usulü Fındıklı Muhallebi', 'FINDIK (İÇ)', 15),
    ('Giresun Usulü Fındıklı Muhallebi', 'ŞEKER', 20),
    ('Giresun Usulü Fındıklı Muhallebi', 'MISIR NİŞASTASI', 5),
    ('Ordu Usulü Zeytinyağlı Taze Fasulye', 'TAZE FASULYE', 60),
    ('Ordu Usulü Zeytinyağlı Taze Fasulye', 'DOMATES', 20),
    ('Ordu Usulü Zeytinyağlı Taze Fasulye', 'KURU SOĞAN', 10),
    ('Ordu Usulü Zeytinyağlı Taze Fasulye', 'ZEYTİNYAĞI', 3),
    ('Ordu Usulü Zeytinyağlı Taze Fasulye', 'ŞEKER', 0.5),
    ('Ordu Usulü Zeytinyağlı Taze Fasulye', 'TUZ', 0.8),
    ('Artvin Usulü Kaşarlı Mısır Ekmeği', 'MISIR UNU', 50),
    ('Artvin Usulü Kaşarlı Mısır Ekmeği', 'EKMEKLİK UN', 15),
    ('Artvin Usulü Kaşarlı Mısır Ekmeği', 'KAŞAR PEYNİRİ', 20),
    ('Artvin Usulü Kaşarlı Mısır Ekmeği', 'TAVUK YUMURTASI', 15),
    ('Artvin Usulü Kaşarlı Mısır Ekmeği', 'TUZ', 0.8),
    ('Bayburt Usulü Etli Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Bayburt Usulü Etli Kavurma', 'KURU SOĞAN', 10),
    ('Bayburt Usulü Etli Kavurma', 'TUZ', 0.8),
    ('Bayburt Usulü Etli Kavurma', 'KARABİBER', 0.3),
    ('Tokat Usulü Zeytinyağlı Nohutlu Pırasa', 'PIRASA', 50),
    ('Tokat Usulü Zeytinyağlı Nohutlu Pırasa', 'NOHUT', 20),
    ('Tokat Usulü Zeytinyağlı Nohutlu Pırasa', 'KURU SOĞAN', 10),
    ('Tokat Usulü Zeytinyağlı Nohutlu Pırasa', 'ZEYTİNYAĞI', 3),
    ('Tokat Usulü Zeytinyağlı Nohutlu Pırasa', 'TUZ', 0.8),
    ('Erzurum Usulü Etli Nohutlu Kavurma', 'KUZU ETİ (KOL)', 80),
    ('Erzurum Usulü Etli Nohutlu Kavurma', 'NOHUT', 25),
    ('Erzurum Usulü Etli Nohutlu Kavurma', 'KURU SOĞAN', 10),
    ('Erzurum Usulü Etli Nohutlu Kavurma', 'TUZ', 0.8),
    ('Erzurum Usulü Etli Nohutlu Kavurma', 'KARABİBER', 0.3),
    ('Van Usulü Balı ile Ceviz Tabağı', 'BAL', 30),
    ('Van Usulü Balı ile Ceviz Tabağı', 'CEVİZ (İÇ)', 20),
    ('Kars Usulü Etli Kavurma', 'KOYUN ETİ (KOL)', 90),
    ('Kars Usulü Etli Kavurma', 'KURU SOĞAN', 10),
    ('Kars Usulü Etli Kavurma', 'TUZ', 0.8),
    ('Kars Usulü Etli Kavurma', 'KARABİBER', 0.3),
    ('Ağrı Usulü Zeytinyağlı Nohut', 'NOHUT', 50),
    ('Ağrı Usulü Zeytinyağlı Nohut', 'KURU SOĞAN', 10),
    ('Ağrı Usulü Zeytinyağlı Nohut', 'DOMATES', 20),
    ('Ağrı Usulü Zeytinyağlı Nohut', 'ZEYTİNYAĞI', 3),
    ('Ağrı Usulü Zeytinyağlı Nohut', 'TUZ', 0.8),
    ('Muş Usulü Etli Pazı Yemeği', 'KUZU ETİ (KOL)', 70),
    ('Muş Usulü Etli Pazı Yemeği', 'PAZI', 50),
    ('Muş Usulü Etli Pazı Yemeği', 'KURU SOĞAN', 10),
    ('Muş Usulü Etli Pazı Yemeği', 'TUZ', 0.8),
    ('Muş Usulü Etli Pazı Yemeği', 'KARABİBER', 0.3),
    ('Malatya Usulü Kayısılı Komposto', 'KAYISI', 50),
    ('Malatya Usulü Kayısılı Komposto', 'ŞEKER', 15),
    ('Malatya Usulü Kayısılı Komposto', 'SU', 70),
    ('Elazığ Usulü Etli Nohutlu Bulgur', 'DANA KIYMA', 50),
    ('Elazığ Usulü Etli Nohutlu Bulgur', 'BULGUR', 25),
    ('Elazığ Usulü Etli Nohutlu Bulgur', 'NOHUT', 20),
    ('Elazığ Usulü Etli Nohutlu Bulgur', 'KURU SOĞAN', 10),
    ('Elazığ Usulü Etli Nohutlu Bulgur', 'TUZ', 0.8),
    ('Elazığ Usulü Etli Nohutlu Bulgur', 'KARABİBER', 0.3),
    ('Bitlis Usulü Zeytinyağlı Semizotu', 'SEMİZOTU', 50),
    ('Bitlis Usulü Zeytinyağlı Semizotu', 'PİRİNÇ (HAM)', 6),
    ('Bitlis Usulü Zeytinyağlı Semizotu', 'KURU SOĞAN', 10),
    ('Bitlis Usulü Zeytinyağlı Semizotu', 'ZEYTİNYAĞI', 3),
    ('Bitlis Usulü Zeytinyağlı Semizotu', 'TUZ', 0.8),
    ('Gaziantep Usulü Etli Nohutlu Kabak', 'KUZU KIYMA', 50),
    ('Gaziantep Usulü Etli Nohutlu Kabak', 'KABAK', 40),
    ('Gaziantep Usulü Etli Nohutlu Kabak', 'DOMATES', 20),
    ('Gaziantep Usulü Etli Nohutlu Kabak', 'KURU SOĞAN', 10),
    ('Gaziantep Usulü Etli Nohutlu Kabak', 'TUZ', 0.8),
    ('Gaziantep Usulü Etli Nohutlu Kabak', 'KARABİBER', 0.3),
    ('Şanlıurfa Usulü Zeytinyağlı Mercimekli Bulgur', 'BULGUR', 40),
    ('Şanlıurfa Usulü Zeytinyağlı Mercimekli Bulgur', 'KIRMIZI MERCİMEK', 20),
    ('Şanlıurfa Usulü Zeytinyağlı Mercimekli Bulgur', 'KURU SOĞAN', 10),
    ('Şanlıurfa Usulü Zeytinyağlı Mercimekli Bulgur', 'ZEYTİNYAĞI', 3),
    ('Şanlıurfa Usulü Zeytinyağlı Mercimekli Bulgur', 'TUZ', 0.8),
    ('Diyarbakır Usulü Etli Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Diyarbakır Usulü Etli Kavurma', 'KURU SOĞAN', 10),
    ('Diyarbakır Usulü Etli Kavurma', 'TUZ', 0.8),
    ('Diyarbakır Usulü Etli Kavurma', 'KARABİBER', 0.3),
    ('Mardin Usulü Zeytinyağlı Biberli Patlıcan', 'PATLICAN', 50),
    ('Mardin Usulü Zeytinyağlı Biberli Patlıcan', 'YEŞİL BİBER', 20),
    ('Mardin Usulü Zeytinyağlı Biberli Patlıcan', 'DOMATES', 25),
    ('Mardin Usulü Zeytinyağlı Biberli Patlıcan', 'KURU SOĞAN', 10),
    ('Mardin Usulü Zeytinyağlı Biberli Patlıcan', 'ZEYTİNYAĞI', 3),
    ('Mardin Usulü Zeytinyağlı Biberli Patlıcan', 'TUZ', 0.8),
    ('Siirt Usulü Fıstıklı Pilav', 'PİRİNÇ (HAM)', 50),
    ('Siirt Usulü Fıstıklı Pilav', 'ANTEP FISTIĞI', 10),
    ('Siirt Usulü Fıstıklı Pilav', 'TEREYAĞI', 5),
    ('Siirt Usulü Fıstıklı Pilav', 'TAVUK SUYU', 70),
    ('Siirt Usulü Fıstıklı Pilav', 'TUZ', 0.8),
    ('Batman Usulü Etli Nohutlu Bulgur', 'KUZU KIYMA', 50),
    ('Batman Usulü Etli Nohutlu Bulgur', 'BULGUR', 25),
    ('Batman Usulü Etli Nohutlu Bulgur', 'NOHUT', 20),
    ('Batman Usulü Etli Nohutlu Bulgur', 'KURU SOĞAN', 10),
    ('Batman Usulü Etli Nohutlu Bulgur', 'TUZ', 0.8),
    ('Batman Usulü Etli Nohutlu Bulgur', 'KARABİBER', 0.3),
    ('Şırnak Usulü Zeytinyağlı Nohutlu Ispanak', 'ISPANAK', 50),
    ('Şırnak Usulü Zeytinyağlı Nohutlu Ispanak', 'NOHUT', 20),
    ('Şırnak Usulü Zeytinyağlı Nohutlu Ispanak', 'KURU SOĞAN', 10),
    ('Şırnak Usulü Zeytinyağlı Nohutlu Ispanak', 'ZEYTİNYAĞI', 3),
    ('Şırnak Usulü Zeytinyağlı Nohutlu Ispanak', 'TUZ', 0.8),
    ('Kilis Usulü Etli Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Kilis Usulü Etli Kavurma', 'KURU SOĞAN', 10),
    ('Kilis Usulü Etli Kavurma', 'PUL BİBER', 0.5),
    ('Kilis Usulü Etli Kavurma', 'TUZ', 0.8),
    ('Kilis Usulü Etli Kavurma', 'KARABİBER', 0.3),
    ('İstanbul Usulü Zeytinyağlı Fırın Patates', 'PATATES', 80),
    ('İstanbul Usulü Zeytinyağlı Fırın Patates', 'ZEYTİNYAĞI', 4),
    ('İstanbul Usulü Zeytinyağlı Fırın Patates', 'KEKİK', 0.3),
    ('İstanbul Usulü Zeytinyağlı Fırın Patates', 'TUZ', 1),
    ('Bursa Usulü Nar Ekşili Kırmızı Lahana Salatası', 'KIRMIZI LAHANA', 50),
    ('Bursa Usulü Nar Ekşili Kırmızı Lahana Salatası', 'NAR EKŞİSİ', 2),
    ('Bursa Usulü Nar Ekşili Kırmızı Lahana Salatası', 'ZEYTİNYAĞI', 2.5),
    ('Bursa Usulü Nar Ekşili Kırmızı Lahana Salatası', 'TUZ', 0.5),
    ('Kocaeli Usulü Zeytinyağlı Kabak Yemeği', 'KABAK', 70),
    ('Kocaeli Usulü Zeytinyağlı Kabak Yemeği', 'KURU SOĞAN', 10),
    ('Kocaeli Usulü Zeytinyağlı Kabak Yemeği', 'DOMATES', 20),
    ('Kocaeli Usulü Zeytinyağlı Kabak Yemeği', 'ZEYTİNYAĞI', 3),
    ('Kocaeli Usulü Zeytinyağlı Kabak Yemeği', 'ŞEKER', 0.5),
    ('Kocaeli Usulü Zeytinyağlı Kabak Yemeği', 'TUZ', 0.8),
    ('Tekirdağ Usulü Kirazlı Komposto', 'KİRAZ', 50),
    ('Tekirdağ Usulü Kirazlı Komposto', 'ŞEKER', 10),
    ('Tekirdağ Usulü Kirazlı Komposto', 'SU', 60),
    ('Çanakkale Usulü Etli Enginar', 'KUZU ETİ (KOL)', 70),
    ('Çanakkale Usulü Etli Enginar', 'ENGİNAR', 40),
    ('Çanakkale Usulü Etli Enginar', 'KURU SOĞAN', 10),
    ('Çanakkale Usulü Etli Enginar', 'TUZ', 0.8),
    ('Çanakkale Usulü Etli Enginar', 'KARABİBER', 0.3),
    ('Balıkesir Usulü Zeytinyağlı Patates', 'PATATES', 70),
    ('Balıkesir Usulü Zeytinyağlı Patates', 'KURU SOĞAN', 10),
    ('Balıkesir Usulü Zeytinyağlı Patates', 'ZEYTİNYAĞI', 3),
    ('Balıkesir Usulü Zeytinyağlı Patates', 'ŞEKER', 0.5),
    ('Balıkesir Usulü Zeytinyağlı Patates', 'TUZ', 0.8),
    ('Marmara Usulü Vişne Ekşili Tavuk Sote', 'TAVUK GÖĞÜS', 90),
    ('Marmara Usulü Vişne Ekşili Tavuk Sote', 'VİŞNE', 20),
    ('Marmara Usulü Vişne Ekşili Tavuk Sote', 'KURU SOĞAN', 10),
    ('Marmara Usulü Vişne Ekşili Tavuk Sote', 'TUZ', 0.8),
    ('Marmara Usulü Vişne Ekşili Tavuk Sote', 'KARABİBER', 0.3),
    ('İstanbul Usulü Zeytinyağlı Bezelye', 'BEZELYE', 50),
    ('İstanbul Usulü Zeytinyağlı Bezelye', 'HAVUÇ', 15),
    ('İstanbul Usulü Zeytinyağlı Bezelye', 'KURU SOĞAN', 10),
    ('İstanbul Usulü Zeytinyağlı Bezelye', 'ZEYTİNYAĞI', 3),
    ('İstanbul Usulü Zeytinyağlı Bezelye', 'ŞEKER', 0.5),
    ('İstanbul Usulü Zeytinyağlı Bezelye', 'TUZ', 0.8),
    ('İzmir Usulü Etli Bamya', 'KUZU ETİ (KOL)', 70),
    ('İzmir Usulü Etli Bamya', 'BAMYA', 50),
    ('İzmir Usulü Etli Bamya', 'DOMATES', 25),
    ('İzmir Usulü Etli Bamya', 'KURU SOĞAN', 10),
    ('İzmir Usulü Etli Bamya', 'TUZ', 0.8),
    ('İzmir Usulü Etli Bamya', 'KARABİBER', 0.3),
    ('Muğla Usulü Zeytinyağlı Kereviz', 'KEREVİZ', 60),
    ('Muğla Usulü Zeytinyağlı Kereviz', 'HAVUÇ', 15),
    ('Muğla Usulü Zeytinyağlı Kereviz', 'KURU SOĞAN', 10),
    ('Muğla Usulü Zeytinyağlı Kereviz', 'ZEYTİNYAĞI', 3),
    ('Muğla Usulü Zeytinyağlı Kereviz', 'ŞEKER', 0.5),
    ('Muğla Usulü Zeytinyağlı Kereviz', 'TUZ', 0.8),
    ('Aydın Usulü İncirli Tavuk Sote', 'TAVUK GÖĞÜS', 90),
    ('Aydın Usulü İncirli Tavuk Sote', 'KURU İNCİR', 20),
    ('Aydın Usulü İncirli Tavuk Sote', 'KURU SOĞAN', 10),
    ('Aydın Usulü İncirli Tavuk Sote', 'TUZ', 0.8),
    ('Aydın Usulü İncirli Tavuk Sote', 'KARABİBER', 0.3),
    ('Denizli Usulü Etli Nohutlu Kavurma', 'DANA KIYMA', 70),
    ('Denizli Usulü Etli Nohutlu Kavurma', 'NOHUT', 25),
    ('Denizli Usulü Etli Nohutlu Kavurma', 'KURU SOĞAN', 10),
    ('Denizli Usulü Etli Nohutlu Kavurma', 'TUZ', 0.8),
    ('Denizli Usulü Etli Nohutlu Kavurma', 'KARABİBER', 0.3),
    ('Bodrum Usulü Izgara Levrek', 'LEVREK', 150),
    ('Bodrum Usulü Izgara Levrek', 'ZEYTİNYAĞI', 3),
    ('Bodrum Usulü Izgara Levrek', 'LİMON SUYU', 2),
    ('Bodrum Usulü Izgara Levrek', 'KEKİK', 0.3),
    ('Bodrum Usulü Izgara Levrek', 'TUZ', 0.8),
    ('Foça Usulü Ahtapotlu Zeytinyağlı Salata', 'AHTAPOT', 50),
    ('Foça Usulü Ahtapotlu Zeytinyağlı Salata', 'ZEYTİNYAĞI', 2.5),
    ('Foça Usulü Ahtapotlu Zeytinyağlı Salata', 'LİMON SUYU', 2),
    ('Foça Usulü Ahtapotlu Zeytinyağlı Salata', 'MAYDANOZ', 1.5),
    ('Foça Usulü Ahtapotlu Zeytinyağlı Salata', 'TUZ', 0.8),
    ('Söke Usulü Zeytinyağlı Nohutlu Havuç', 'HAVUÇ', 50),
    ('Söke Usulü Zeytinyağlı Nohutlu Havuç', 'NOHUT', 20),
    ('Söke Usulü Zeytinyağlı Nohutlu Havuç', 'KURU SOĞAN', 10),
    ('Söke Usulü Zeytinyağlı Nohutlu Havuç', 'ZEYTİNYAĞI', 3),
    ('Söke Usulü Zeytinyağlı Nohutlu Havuç', 'TUZ', 0.8),
    ('Ege Usulü Ayvalı Ceviz Tatlısı', 'AYVA', 60),
    ('Ege Usulü Ayvalı Ceviz Tatlısı', 'CEVİZ (İÇ)', 10),
    ('Ege Usulü Ayvalı Ceviz Tatlısı', 'ŞEKER', 25),
    ('Antalya Usulü Etli Kabak', 'DANA KIYMA', 50),
    ('Antalya Usulü Etli Kabak', 'KABAK', 50),
    ('Antalya Usulü Etli Kabak', 'DOMATES', 20),
    ('Antalya Usulü Etli Kabak', 'KURU SOĞAN', 10),
    ('Antalya Usulü Etli Kabak', 'TUZ', 0.8),
    ('Antalya Usulü Etli Kabak', 'KARABİBER', 0.3),
    ('Mersin Usulü Zeytinyağlı Nohutlu Havuç', 'HAVUÇ', 50),
    ('Mersin Usulü Zeytinyağlı Nohutlu Havuç', 'NOHUT', 20),
    ('Mersin Usulü Zeytinyağlı Nohutlu Havuç', 'KURU SOĞAN', 10),
    ('Mersin Usulü Zeytinyağlı Nohutlu Havuç', 'ZEYTİNYAĞI', 3),
    ('Mersin Usulü Zeytinyağlı Nohutlu Havuç', 'TUZ', 0.8),
    ('Adana Usulü Izgara Tavuk Kanat', 'TAVUK KANAT', 120),
    ('Adana Usulü Izgara Tavuk Kanat', 'PUL BİBER', 0.8),
    ('Adana Usulü Izgara Tavuk Kanat', 'SARIMSAK', 1.5),
    ('Adana Usulü Izgara Tavuk Kanat', 'ZEYTİNYAĞI', 4),
    ('Adana Usulü Izgara Tavuk Kanat', 'TUZ', 0.8),
    ('Hatay Usulü Nar Ekşili Etli Bamya', 'KUZU ETİ (KOL)', 70),
    ('Hatay Usulü Nar Ekşili Etli Bamya', 'BAMYA', 50),
    ('Hatay Usulü Nar Ekşili Etli Bamya', 'NAR EKŞİSİ', 2),
    ('Hatay Usulü Nar Ekşili Etli Bamya', 'KURU SOĞAN', 10),
    ('Hatay Usulü Nar Ekşili Etli Bamya', 'TUZ', 0.8),
    ('Hatay Usulü Nar Ekşili Etli Bamya', 'KARABİBER', 0.3),
    ('Kaş Usulü Zeytinyağlı Ahtapot Salatası', 'AHTAPOT', 60),
    ('Kaş Usulü Zeytinyağlı Ahtapot Salatası', 'ZEYTİNYAĞI', 3),
    ('Kaş Usulü Zeytinyağlı Ahtapot Salatası', 'LİMON SUYU', 2),
    ('Kaş Usulü Zeytinyağlı Ahtapot Salatası', 'TUZ', 0.8),
    ('Alanya Usulü Portakallı Zeytinyağlı Havuç', 'HAVUÇ', 50),
    ('Alanya Usulü Portakallı Zeytinyağlı Havuç', 'PORTAKAL', 20),
    ('Alanya Usulü Portakallı Zeytinyağlı Havuç', 'ZEYTİNYAĞI', 3),
    ('Alanya Usulü Portakallı Zeytinyağlı Havuç', 'ŞEKER', 0.5),
    ('Alanya Usulü Portakallı Zeytinyağlı Havuç', 'TUZ', 0.8),
    ('Silifke Usulü Etli Nohutlu Yahni', 'KUZU ETİ (KOL)', 80),
    ('Silifke Usulü Etli Nohutlu Yahni', 'NOHUT', 30),
    ('Silifke Usulü Etli Nohutlu Yahni', 'KURU SOĞAN', 10),
    ('Silifke Usulü Etli Nohutlu Yahni', 'TUZ', 0.8),
    ('Silifke Usulü Etli Nohutlu Yahni', 'KARABİBER', 0.3),
    ('Kahramanmaraş Usulü Zeytinyağlı Patlıcan', 'PATLICAN', 60),
    ('Kahramanmaraş Usulü Zeytinyağlı Patlıcan', 'DOMATES', 25),
    ('Kahramanmaraş Usulü Zeytinyağlı Patlıcan', 'KURU SOĞAN', 10),
    ('Kahramanmaraş Usulü Zeytinyağlı Patlıcan', 'ZEYTİNYAĞI', 3),
    ('Kahramanmaraş Usulü Zeytinyağlı Patlıcan', 'TUZ', 0.8),
    ('Ankara Usulü Zeytinyağlı Pırasa', 'PIRASA', 60),
    ('Ankara Usulü Zeytinyağlı Pırasa', 'HAVUÇ', 15),
    ('Ankara Usulü Zeytinyağlı Pırasa', 'KURU SOĞAN', 10),
    ('Ankara Usulü Zeytinyağlı Pırasa', 'ZEYTİNYAĞI', 3),
    ('Ankara Usulü Zeytinyağlı Pırasa', 'ŞEKER', 0.5),
    ('Ankara Usulü Zeytinyağlı Pırasa', 'TUZ', 0.8),
    ('Konya Usulü Etli Kabak Yemeği', 'DANA KIYMA', 50),
    ('Konya Usulü Etli Kabak Yemeği', 'KABAK', 50),
    ('Konya Usulü Etli Kabak Yemeği', 'DOMATES', 20),
    ('Konya Usulü Etli Kabak Yemeği', 'KURU SOĞAN', 10),
    ('Konya Usulü Etli Kabak Yemeği', 'TUZ', 0.8),
    ('Konya Usulü Etli Kabak Yemeği', 'KARABİBER', 0.3),
    ('Kayseri Usulü Elmalı Pekmezli Tatlı', 'ELMA', 60),
    ('Kayseri Usulü Elmalı Pekmezli Tatlı', 'ÜzÜM PEKMEZİ', 15),
    ('Kayseri Usulü Elmalı Pekmezli Tatlı', 'CEVİZ (İÇ)', 8),
    ('Sivas Usulü Zeytinyağlı Nohutlu Havuç', 'HAVUÇ', 50),
    ('Sivas Usulü Zeytinyağlı Nohutlu Havuç', 'NOHUT', 20),
    ('Sivas Usulü Zeytinyağlı Nohutlu Havuç', 'KURU SOĞAN', 10),
    ('Sivas Usulü Zeytinyağlı Nohutlu Havuç', 'ZEYTİNYAĞI', 3),
    ('Sivas Usulü Zeytinyağlı Nohutlu Havuç', 'TUZ', 0.8),
    ('Yozgat Usulü Etli Bulgur Pilavı', 'DANA KIYMA', 50),
    ('Yozgat Usulü Etli Bulgur Pilavı', 'BULGUR', 40),
    ('Yozgat Usulü Etli Bulgur Pilavı', 'KURU SOĞAN', 10),
    ('Yozgat Usulü Etli Bulgur Pilavı', 'TUZ', 0.8),
    ('Yozgat Usulü Etli Bulgur Pilavı', 'KARABİBER', 0.3),
    ('Niğde Usulü Zeytinyağlı Kereviz', 'KEREVİZ', 60),
    ('Niğde Usulü Zeytinyağlı Kereviz', 'HAVUÇ', 15),
    ('Niğde Usulü Zeytinyağlı Kereviz', 'KURU SOĞAN', 10),
    ('Niğde Usulü Zeytinyağlı Kereviz', 'ZEYTİNYAĞI', 3),
    ('Niğde Usulü Zeytinyağlı Kereviz', 'ŞEKER', 0.5),
    ('Niğde Usulü Zeytinyağlı Kereviz', 'TUZ', 0.8),
    ('Karaman Usulü Kayısılı Tavuk Güveç', 'TAVUK BUT', 80),
    ('Karaman Usulü Kayısılı Tavuk Güveç', 'KAYISI', 20),
    ('Karaman Usulü Kayısılı Tavuk Güveç', 'KURU SOĞAN', 10),
    ('Karaman Usulü Kayısılı Tavuk Güveç', 'DOMATES', 20),
    ('Karaman Usulü Kayısılı Tavuk Güveç', 'TUZ', 0.8),
    ('Karaman Usulü Kayısılı Tavuk Güveç', 'KARABİBER', 0.3),
    ('Kırıkkale Usulü Zeytinyağlı Nohutlu Bamya', 'BAMYA', 50),
    ('Kırıkkale Usulü Zeytinyağlı Nohutlu Bamya', 'NOHUT', 20),
    ('Kırıkkale Usulü Zeytinyağlı Nohutlu Bamya', 'DOMATES', 20),
    ('Kırıkkale Usulü Zeytinyağlı Nohutlu Bamya', 'KURU SOĞAN', 10),
    ('Kırıkkale Usulü Zeytinyağlı Nohutlu Bamya', 'ZEYTİNYAĞI', 3),
    ('Kırıkkale Usulü Zeytinyağlı Nohutlu Bamya', 'TUZ', 0.8),
    ('Trabzon Usulü Etli Karalahana', 'DANA KIYMA', 50),
    ('Trabzon Usulü Etli Karalahana', 'KARALAHANA', 50),
    ('Trabzon Usulü Etli Karalahana', 'KURU SOĞAN', 10),
    ('Trabzon Usulü Etli Karalahana', 'TUZ', 0.8),
    ('Trabzon Usulü Etli Karalahana', 'KARABİBER', 0.3),
    ('Rize Usulü Zeytinyağlı Pırasa', 'PIRASA', 60),
    ('Rize Usulü Zeytinyağlı Pırasa', 'HAVUÇ', 15),
    ('Rize Usulü Zeytinyağlı Pırasa', 'KURU SOĞAN', 10),
    ('Rize Usulü Zeytinyağlı Pırasa', 'ZEYTİNYAĞI', 3),
    ('Rize Usulü Zeytinyağlı Pırasa', 'ŞEKER', 0.5),
    ('Rize Usulü Zeytinyağlı Pırasa', 'TUZ', 0.8),
    ('Samsun Usulü Elmalı Tatlı', 'ELMA', 70),
    ('Samsun Usulü Elmalı Tatlı', 'ŞEKER', 25),
    ('Samsun Usulü Elmalı Tatlı', 'TARÇIN', 0.3),
    ('Giresun Usulü Etli Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Giresun Usulü Etli Kavurma', 'KURU SOĞAN', 10),
    ('Giresun Usulü Etli Kavurma', 'TUZ', 0.8),
    ('Giresun Usulü Etli Kavurma', 'KARABİBER', 0.3),
    ('Ordu Usulü Zeytinyağlı Kereviz', 'KEREVİZ', 60),
    ('Ordu Usulü Zeytinyağlı Kereviz', 'HAVUÇ', 15),
    ('Ordu Usulü Zeytinyağlı Kereviz', 'KURU SOĞAN', 10),
    ('Ordu Usulü Zeytinyağlı Kereviz', 'ZEYTİNYAĞI', 3),
    ('Ordu Usulü Zeytinyağlı Kereviz', 'ŞEKER', 0.5),
    ('Ordu Usulü Zeytinyağlı Kereviz', 'TUZ', 0.8),
    ('Artvin Usulü Cevizli Bal Tatlısı', 'BAL', 30),
    ('Artvin Usulü Cevizli Bal Tatlısı', 'CEVİZ (İÇ)', 20),
    ('Bayburt Usulü Zeytinyağlı Nohut', 'NOHUT', 50),
    ('Bayburt Usulü Zeytinyağlı Nohut', 'KURU SOĞAN', 10),
    ('Bayburt Usulü Zeytinyağlı Nohut', 'DOMATES', 20),
    ('Bayburt Usulü Zeytinyağlı Nohut', 'ZEYTİNYAĞI', 3),
    ('Bayburt Usulü Zeytinyağlı Nohut', 'TUZ', 0.8),
    ('Tokat Usulü Etli Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Tokat Usulü Etli Kavurma', 'KURU SOĞAN', 10),
    ('Tokat Usulü Etli Kavurma', 'TUZ', 0.8),
    ('Tokat Usulü Etli Kavurma', 'KARABİBER', 0.3),
    ('Erzurum Usulü Zeytinyağlı Pırasa', 'PIRASA', 60),
    ('Erzurum Usulü Zeytinyağlı Pırasa', 'HAVUÇ', 15),
    ('Erzurum Usulü Zeytinyağlı Pırasa', 'KURU SOĞAN', 10),
    ('Erzurum Usulü Zeytinyağlı Pırasa', 'ZEYTİNYAĞI', 3),
    ('Erzurum Usulü Zeytinyağlı Pırasa', 'ŞEKER', 0.5),
    ('Erzurum Usulü Zeytinyağlı Pırasa', 'TUZ', 0.8),
    ('Van Usulü Etli Nohutlu Kavurma', 'KUZU ETİ (KOL)', 80),
    ('Van Usulü Etli Nohutlu Kavurma', 'NOHUT', 25),
    ('Van Usulü Etli Nohutlu Kavurma', 'KURU SOĞAN', 10),
    ('Van Usulü Etli Nohutlu Kavurma', 'TUZ', 0.8),
    ('Van Usulü Etli Nohutlu Kavurma', 'KARABİBER', 0.3),
    ('Kars Usulü Elmalı Ceviz Tatlısı', 'ELMA', 60),
    ('Kars Usulü Elmalı Ceviz Tatlısı', 'CEVİZ (İÇ)', 10),
    ('Kars Usulü Elmalı Ceviz Tatlısı', 'ŞEKER', 20),
    ('Ağrı Usulü Etli Kavurma', 'KOYUN ETİ (KOL)', 90),
    ('Ağrı Usulü Etli Kavurma', 'KURU SOĞAN', 10),
    ('Ağrı Usulü Etli Kavurma', 'TUZ', 0.8),
    ('Ağrı Usulü Etli Kavurma', 'KARABİBER', 0.3),
    ('Muş Usulü Zeytinyağlı Nohut', 'NOHUT', 50),
    ('Muş Usulü Zeytinyağlı Nohut', 'KURU SOĞAN', 10),
    ('Muş Usulü Zeytinyağlı Nohut', 'DOMATES', 20),
    ('Muş Usulü Zeytinyağlı Nohut', 'ZEYTİNYAĞI', 3),
    ('Muş Usulü Zeytinyağlı Nohut', 'TUZ', 0.8),
    ('Malatya Usulü Etli Kayısılı Bamya', 'KUZU ETİ (KOL)', 70),
    ('Malatya Usulü Etli Kayısılı Bamya', 'BAMYA', 40),
    ('Malatya Usulü Etli Kayısılı Bamya', 'KURU KAYISI', 15),
    ('Malatya Usulü Etli Kayısılı Bamya', 'KURU SOĞAN', 10),
    ('Malatya Usulü Etli Kayısılı Bamya', 'TUZ', 0.8),
    ('Malatya Usulü Etli Kayısılı Bamya', 'KARABİBER', 0.3),
    ('Elazığ Usulü Zeytinyağlı Pırasa', 'PIRASA', 60),
    ('Elazığ Usulü Zeytinyağlı Pırasa', 'HAVUÇ', 15),
    ('Elazığ Usulü Zeytinyağlı Pırasa', 'KURU SOĞAN', 10),
    ('Elazığ Usulü Zeytinyağlı Pırasa', 'ZEYTİNYAĞI', 3),
    ('Elazığ Usulü Zeytinyağlı Pırasa', 'ŞEKER', 0.5),
    ('Elazığ Usulü Zeytinyağlı Pırasa', 'TUZ', 0.8),
    ('Bitlis Usulü Etli Nohutlu Kavurma', 'DANA KIYMA', 50),
    ('Bitlis Usulü Etli Nohutlu Kavurma', 'NOHUT', 25),
    ('Bitlis Usulü Etli Nohutlu Kavurma', 'KURU SOĞAN', 10),
    ('Bitlis Usulü Etli Nohutlu Kavurma', 'TUZ', 0.8),
    ('Bitlis Usulü Etli Nohutlu Kavurma', 'KARABİBER', 0.3),
    ('Gaziantep Usulü Nar Ekşili Etli Patlıcan', 'KUZU KIYMA', 50),
    ('Gaziantep Usulü Nar Ekşili Etli Patlıcan', 'PATLICAN', 50),
    ('Gaziantep Usulü Nar Ekşili Etli Patlıcan', 'NAR EKŞİSİ', 2),
    ('Gaziantep Usulü Nar Ekşili Etli Patlıcan', 'KURU SOĞAN', 10),
    ('Gaziantep Usulü Nar Ekşili Etli Patlıcan', 'TUZ', 0.8),
    ('Gaziantep Usulü Nar Ekşili Etli Patlıcan', 'KARABİBER', 0.3),
    ('Şanlıurfa Usulü Etli Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Şanlıurfa Usulü Etli Kavurma', 'KURU SOĞAN', 10),
    ('Şanlıurfa Usulü Etli Kavurma', 'PUL BİBER', 0.5),
    ('Şanlıurfa Usulü Etli Kavurma', 'TUZ', 0.8),
    ('Şanlıurfa Usulü Etli Kavurma', 'KARABİBER', 0.3),
    ('Diyarbakır Usulü Zeytinyağlı Nohutlu Havuç', 'HAVUÇ', 50),
    ('Diyarbakır Usulü Zeytinyağlı Nohutlu Havuç', 'NOHUT', 20),
    ('Diyarbakır Usulü Zeytinyağlı Nohutlu Havuç', 'KURU SOĞAN', 10),
    ('Diyarbakır Usulü Zeytinyağlı Nohutlu Havuç', 'ZEYTİNYAĞI', 3),
    ('Diyarbakır Usulü Zeytinyağlı Nohutlu Havuç', 'TUZ', 0.8),
    ('Mardin Usulü Etli Bulgur Pilavı', 'KUZU KIYMA', 50),
    ('Mardin Usulü Etli Bulgur Pilavı', 'BULGUR', 40),
    ('Mardin Usulü Etli Bulgur Pilavı', 'KURU SOĞAN', 10),
    ('Mardin Usulü Etli Bulgur Pilavı', 'TUZ', 0.8),
    ('Mardin Usulü Etli Bulgur Pilavı', 'KARABİBER', 0.3),
    ('Siirt Usulü Zeytinyağlı Nohutlu Bamya', 'BAMYA', 50),
    ('Siirt Usulü Zeytinyağlı Nohutlu Bamya', 'NOHUT', 20),
    ('Siirt Usulü Zeytinyağlı Nohutlu Bamya', 'DOMATES', 20),
    ('Siirt Usulü Zeytinyağlı Nohutlu Bamya', 'KURU SOĞAN', 10),
    ('Siirt Usulü Zeytinyağlı Nohutlu Bamya', 'ZEYTİNYAĞI', 3),
    ('Siirt Usulü Zeytinyağlı Nohutlu Bamya', 'TUZ', 0.8),
    ('Batman Usulü Etli Kavurma', 'KUZU ETİ (KOL)', 90),
    ('Batman Usulü Etli Kavurma', 'KURU SOĞAN', 10),
    ('Batman Usulü Etli Kavurma', 'TUZ', 0.8),
    ('Batman Usulü Etli Kavurma', 'KARABİBER', 0.3),
    ('Şırnak Usulü Zeytinyağlı Patlıcan', 'PATLICAN', 60),
    ('Şırnak Usulü Zeytinyağlı Patlıcan', 'DOMATES', 25),
    ('Şırnak Usulü Zeytinyağlı Patlıcan', 'KURU SOĞAN', 10),
    ('Şırnak Usulü Zeytinyağlı Patlıcan', 'ZEYTİNYAĞI', 3),
    ('Şırnak Usulü Zeytinyağlı Patlıcan', 'TUZ', 0.8),
    ('Kilis Usulü Nar Ekşili Zeytinyağlı Bulgur', 'BULGUR', 40),
    ('Kilis Usulü Nar Ekşili Zeytinyağlı Bulgur', 'NAR EKŞİSİ', 2),
    ('Kilis Usulü Nar Ekşili Zeytinyağlı Bulgur', 'DOMATES', 25),
    ('Kilis Usulü Nar Ekşili Zeytinyağlı Bulgur', 'KURU SOĞAN', 10),
    ('Kilis Usulü Nar Ekşili Zeytinyağlı Bulgur', 'ZEYTİNYAĞI', 3),
    ('Kilis Usulü Nar Ekşili Zeytinyağlı Bulgur', 'TUZ', 0.8)
)
select b.ad,
    (select count(*) from beklenen x where x.ad = b.ad) as beklenen_sayisi,
    (select count(*) from recete_malzemeleri rm
       join receteler r on r.id = rm.recete_id
      where r.ad = b.ad and r.isletme_id is null) as db_sayisi,
    (select count(*) from beklenen x
       join receteler r on r.ad = x.ad and r.isletme_id is null
       join recete_malzemeleri rm on rm.recete_id = r.id
       join malzemeler m on m.id = rm.malzeme_id
      where x.ad = b.ad and m.ad = x.malzeme_ad and rm.miktar_gram = x.miktar) as tam_eslesen
from (select distinct ad from beklenen) b
where not (
    (select count(*) from beklenen x where x.ad = b.ad) =
    (select count(*) from recete_malzemeleri rm join receteler r on r.id = rm.recete_id where r.ad = b.ad and r.isletme_id is null)
    and
    (select count(*) from beklenen x where x.ad = b.ad) =
    (select count(*) from beklenen x
       join receteler r on r.ad = x.ad and r.isletme_id is null
       join recete_malzemeleri rm on rm.recete_id = r.id
       join malzemeler m on m.id = rm.malzeme_id
      where x.ad = b.ad and m.ad = x.malzeme_ad and rm.miktar_gram = x.miktar)
)
order by b.ad;