-- KAPSAMLI DENETIM: Parti 1-5'teki 278 tarifin GERCEK malzeme
-- ICERIGINI (sadece sayisini degil) beklenenle karsilastirir. Bir
-- satir donerse, o tarif ONCEDEN VAR OLAN farkli bir tarifle ayni
-- isimde carpisip atlanmis demektir (malzeme SAYISI tesadufen ayni
-- oldugu icin onceki sayim-bazli kontrol bunu KACIRMISTI).
with beklenen(ad, beklenen_imza) as (
  values
    ('Bursa İskender Kebabı', 'DOMATES:40|DÖNER (ET, PİŞMİŞ, BURSA):120|PİDE:70|TEREYAĞI:12|TUZ:0.8|YOĞURT (TAM):50'),
    ('İnegöl Köfte', 'DANA KIYMA:90|EKMEKLİK UN:4|KARABİBER:0.3|KURU SOĞAN:15|KİMYON:0.5|TUZ:1.2'),
    ('Bursa Kestaneli Kaz Dolması', 'KARABİBER:0.3|KAZ ETİ (BÜTÜN, DERİLİ):180|KESTANE:40|KURU SOĞAN:15|KUŞ ÜZÜMÜ:6|PİRİNÇ (HAM):30|TUZ:1.5|YENİBAHAR:0.3'),
    ('İstanbul Usulü Karnıyarık', 'DANA KIYMA:70|DOMATES:40|KARABİBER:0.3|KURU SOĞAN:20|PATLICAN:120|SARIMSAK:1.5|TUZ:1.2|YEŞİL BİBER:15|ZEYTİNYAĞI:6'),
    ('Bandırma Mantısı', 'DANA KIYMA:50|EKMEKLİK UN:70|KURU NANE:0.5|KURU SOĞAN:15|PUL BİBER:0.8|SARIMSAK:2|TEREYAĞI:8|TUZ:1.2|YOĞURT (TAM):60'),
    ('Marmara Usulü Midye Tava', 'CEVİZ (İÇ):10|EKMEK (BEYAZ):8|EKMEKLİK UN:25|KARBONAT (YEM. SODA):0.5|LİMON SUYU:3|MISIR YAĞI:30|MİDYE:120|SARIMSAK:2|TUZ:1'),
    ('Kırklareli Rokalı Beyaz Peynir Salatası', 'CEVİZ (İÇ):10|EDİRNE BEYAZ PEYNİRİ:30|LİMON SUYU:2.5|ROKA:40|TUZ:0.5|ZEYTİNYAĞI:4'),
    ('Marmara Kestaneli Muhallebi', 'CEVİZ (İÇ):6|KESTANE:40|MISIR NİŞASTASI:8|SÜT (TAM YAĞ):150|ŞEKER:25'),
    ('İzmir Köfte (Fırında)', 'DANA KIYMA:90|DOMATES:40|EKMEKLİK UN:4|KARABİBER:0.3|KURU SOĞAN:15|PATATES:50|TUZ:1.2|ZEYTİNYAĞI:4'),
    ('Çeşme Usulü Ahtapot Güveç', 'AHTAPOT:100|DOMATES:40|KARABİBER:0.3|KURU SOĞAN:15|TUZ:1|YEŞİL BİBER:15|ZEYTİNYAĞI:5'),
    ('Ege Otlu Peynirli Gözleme', 'ISPANAK:30|OTLU PEYNİR:40|TEREYAĞI:6|TUZ:0.5|YUFKA:60'),
    ('Ege Usulü Isırgan Kavurması (Etli)', 'ISIRGAN:50|KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):70|TUZ:1|ZEYTİNYAĞI:4'),
    ('Ege Yaylası Kuzu Tandır', 'KARABİBER:0.3|KEKİK:0.5|KURU SOĞAN:15|KUZU TANDIR:150|TUZ:1.5|ZEYTİNYAĞI:4'),
    ('Ege Portakallı Zeytinyağlı Kek', 'EKMEKLİK UN:50|KABARTMA TOZU:1.5|PORTAKAL:30|TAVUK YUMURTASI:30|ZEYTİNYAĞI:20|ŞEKER:35'),
    ('Datça Bademli Yeşil Salata', 'BADEM:8|LİMON SUYU:2.5|MARUL:20|ROKA:30|TUZ:0.5|ZEYTİNYAĞI:4'),
    ('Ege İnciri ile Komposto', 'KURU İNCİR:50|SU:80|ŞEKER:10'),
    ('Antalya Usulü Nohut Piyazı', 'KURU SOĞAN:10|LİMON SUYU:2.5|MAYDANOZ:3|NOHUT:60|SUMAK:0.5|TUZ:0.8|ZEYTİNYAĞI:4'),
    ('Mersin Tantunisi', 'DANA BONFİLE:100|KARABİBER:0.3|KURU SOĞAN:15|LAVAŞ:50|MISIR YAĞI:6|SUMAK:0.5|TUZ:1|YEŞİL BİBER:15'),
    ('Adana Kebap', 'KARABİBER:0.3|KIRMIZI BİBER:15|KUZU KIYMA:90|PUL BİBER:0.8|TUZ:1.2'),
    ('Hatay Usulü İçli Köfte (Etli)', 'BULGUR:50|CEVİZ (İÇ):10|DANA KIYMA:80|KARABİBER:0.3|KURU SOĞAN:20|PUL BİBER:0.5|TUZ:1.2'),
    ('Antalya Şakşuka', 'DOMATES:40|KABAK:30|PATLICAN:50|SARIMSAK:1.5|TUZ:1|YEŞİL BİBER:15|YOĞURT (TAM):30|ZEYTİNYAĞI:6'),
    ('Akdeniz Usulü Limonlu Zeytin Ezmesi', 'KURU SOĞAN:5|LİMON SUYU:2|PUL BİBER:0.5|ZEYTİN EZMESİ:40|ZEYTİNYAĞI:4'),
    ('Adana Usulü Nar Ekşili Salata', 'CEVİZ (İÇ):8|MARUL:30|NAR EKŞİSİ:3|NAR:30|TUZ:0.5|ZEYTİNYAĞI:3'),
    ('Antalya Usulü Şeftali Kompostosu', 'SU:70|ŞEFTALİ:80|ŞEKER:15'),
    ('Kayseri Mantısı', 'EKMEKLİK UN:70|KURU NANE:0.5|KURU SOĞAN:15|KUZU KIYMA:50|PUL BİBER:0.8|SARIMSAK:2|TEREYAĞI:8|TUZ:1.2|YOĞURT (TAM):60'),
    ('Ankara Tava (Kuzu Etli)', 'KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):120|PİRİNÇ (HAM):30|TEREYAĞI:6|TUZ:1.2'),
    ('Konya Etli Ekmek', 'DOMATES:25|EKMEKLİK UN:80|KURU SOĞAN:15|KUZU KIYMA:70|MAYDANOZ:2|PUL BİBER:0.5|TUZ:1'),
    ('Nevşehir Testi Kebabı', 'DOMATES:30|KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):100|MANTAR:20|TUZ:1.2|YEŞİL BİBER:20'),
    ('Kayseri Yağlaması', 'KURU SOĞAN:15|KUZU KIYMA:50|LAVAŞ:60|PUL BİBER:0.5|TEREYAĞI:6|TUZ:0.8'),
    ('Kapadokya Kestaneli Komposto', 'KESTANE:50|SU:70|ŞEKER:15'),
    ('Kayseri Usulü Nohutlu Bulgur Pilavı', 'BULGUR:60|KURU SOĞAN:15|NOHUT:30|TAVUK SUYU:90|TEREYAĞI:6|TUZ:1'),
    ('Niğde Bademli Un Helvası', 'BADEM (İÇ):6|EKMEKLİK UN:50|SÜT (TAM YAĞ):60|TEREYAĞI:30|ŞEKER:40'),
    ('Karadeniz Mıhlaması', 'KAŞAR PEYNİRİ:50|MISIR UNU:40|SU:60|TEREYAĞI:15|TUZ:0.5'),
    ('Karadeniz Kaymaklı Pide', 'EKMEKLİK UN:70|KAŞAR PEYNİRİ:40|TAVUK YUMURTASI:30|TEREYAĞI:8|TUZ:1'),
    ('Trabzon Usulü Hamsili Pilav', 'HAMSİ:60|KARABİBER:0.3|KURU SOĞAN:15|PİRİNÇ (HAM):50|TEREYAĞI:8|TUZ:1'),
    ('Rize Usulü Karalahana Çorbası', 'KARALAHANA:50|KURU FASULYE:15|MISIR UNU:10|TEREYAĞI:4|TUZ:1'),
    ('Giresun Fındıklı Kuru Fasulye', 'DOMATES:25|FINDIK (İÇ):10|KURU FASULYE:50|KURU SOĞAN:15|TUZ:1|ZEYTİNYAĞI:4'),
    ('Karadeniz Mısır Ekmeği', 'EKMEKLİK UN:20|KABARTMA TOZU:1.5|MISIR UNU:60|TAVUK YUMURTASI:20|TUZ:0.8|YOĞURT (TAM):30'),
    ('Trabzon Usulü Akçaabat Köfte', 'DANA KIYMA:90|GALETA UNU (PANKO):6|KARABİBER:0.3|KURU SOĞAN:10|KİMYON:0.5|TUZ:1.2'),
    ('Karadeniz Dutlu Komposto', 'DUT:50|SU:60|ŞEKER:12'),
    ('Erzurum Cağ Kebabı', 'KARABİBER:0.3|KOYUN ETİ (BUT):150|KURU SOĞAN:10|TUZ:1.2'),
    ('Erzincan Tulumlu Kavurma', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):90|TULUM PEYNİRİ:15|TUZ:1'),
    ('Van Otlu Peynirli Kahvaltı Böreği', 'OTLU PEYNİR:40|TAVUK YUMURTASI:15|TEREYAĞI:6|TUZ:0.5|YUFKA:50'),
    ('Malatya Kayısılı Kuzu Yahnisi', 'KARABİBER:0.3|KURU KAYISI:30|KURU SOĞAN:15|KUZU ETİ (KOL):100|TUZ:1'),
    ('Elazığ Usulü Kuru Fasulye Kavurması', 'DANA KIYMA:40|DOMATES:25|KARABİBER:0.3|KURU FASULYE:50|KURU SOĞAN:15|TUZ:1'),
    ('Kars Usulü Kaz Eti Kavurması', 'KARABİBER:0.3|KAZ ETİ (BUT, DERİSİZ, TUZ İLAVELİ):120|KURU SOĞAN:15|TUZ:0.6'),
    ('Doğu Anadolu Pekmezli Ceviz Ezmesi', 'CEVİZ (İÇ):30|MISIR NİŞASTASI:10|ÜzÜM PEKMEZİ:50'),
    ('Doğu Anadolu Kayısı ve Ceviz Salatası', 'CEVİZ (İÇ):10|KAYISI:40|YOĞURT (TAM):30|ŞEKER:3'),
    ('Gaziantep Alinazik Kebabı', 'KARABİBER:0.3|KUZU KIYMA:60|PATLICAN:80|SARIMSAK:2|TEREYAĞI:4|TUZ:1|YOĞURT (TAM):40'),
    ('Şanlıurfa Usulü Çiğ Köfte (Etsiz)', 'BULGUR:50|CEVİZ (İÇ):10|KONSERVE BİBER SALÇASI:15|NAR EKŞİSİ:4|PUL BİBER:1|SARIMSAK:1.5|TUZ:1'),
    ('Urfa Usulü Kuzu Kavurma', 'KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):100|PUL BİBER:1|TUZ:1'),
    ('Mardin Usulü Kaburga Dolması', 'KARABİBER:0.3|KURU SOĞAN:10|KİMYON:0.5|PİRİNÇ (HAM):30|SIĞIR KABURGA:150|TUZ:1.2'),
    ('Diyarbakır Usulü Meftune', 'DOMATES:30|KABAK:30|KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):80|PATLICAN:40|SARIMSAK:1.5|TUZ:1'),
    ('Antep Usulü Yuvalama Çorbası', 'DANA KIYMA:30|KURU NANE:0.5|PİRİNÇ (HAM):15|TAVUK SUYU:80|TEREYAĞI:4|TUZ:1|YOĞURT (TAM):60'),
    ('Siirt Usulü Büryan', 'KARABİBER:0.3|KUZU ETİ (BUT):180|TUZ:1.5'),
    ('Antep Fıstıklı Muhallebi', 'ANTEP FISTIĞI:15|PİRİNÇ UNU:8|SÜT (TAM YAĞ):150|ŞEKER:25'),
    ('Tekirdağ Köftesi', 'DANA KIYMA:90|EKMEKLİK UN:4|KARABİBER:0.3|KARBONAT (YEM. SODA):0.3|KURU SOĞAN:10|TUZ:1.2'),
    ('Çanakkale Peynir Helvası', 'EKMEKLİK UN:30|LOR PEYNİRİ:60|SÜT (TAM YAĞ):40|TEREYAĞI:15|ŞEKER:40'),
    ('Balıkesir Kaymaklı Kayısı Tatlısı', 'KAYISI:80|KAYMAK:30|ŞEKER:15'),
    ('İstanbul Usulü Etli Kuru Fasulye', 'DANA KIYMA:40|DOMATES:25|KARABİBER:0.3|KURU FASULYE:60|KURU SOĞAN:15|TUZ:1'),
    ('Marmara Usulü Kabak Mücveri', 'EKMEKLİK UN:15|KABAK:80|KARABİBER:0.3|MAYDANOZ:3|MISIR YAĞI:30|TAVUK YUMURTASI:20|TUZ:1'),
    ('Bandırma Usulü Tavuk Sote', 'DOMATES:30|KARABİBER:0.3|KURU SOĞAN:15|TAVUK BUT:100|TUZ:1|YEŞİL BİBER:15'),
    ('Marmara Usulü Fırında Lüfer', 'KEKİK:0.3|LÜFER:150|LİMON SUYU:3|TUZ:1|ZEYTİNYAĞI:4'),
    ('Marmara Usulü Vişneli Yoğurt Dondurması', 'VİŞNE:30|YOĞURT (TAM):60|ŞEKER:15'),
    ('Kemalpaşa Köftesi', 'DANA KIYMA:90|EKMEKLİK UN:6|KARABİBER:0.3|KURU SOĞAN:10|TUZ:1'),
    ('Aydın İncirli Kuzu Tandır', 'KARABİBER:0.3|KURU SOĞAN:10|KURU İNCİR:20|KUZU TANDIR:150|TUZ:1.2'),
    ('Muğla Yeşil Erik Salatası', 'ERİK:40|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Foça Usulü Kalamar Tava', 'EKMEKLİK UN:20|KALAMAR:100|LİMON SUYU:2.5|MISIR YAĞI:30|TUZ:1'),
    ('Ege Yeşil Zeytinli Havuç Salatası', 'HAVUÇ:50|LİMON SUYU:2|TUZ:0.5|YEŞİL ZEYTİN:15|ZEYTİNYAĞI:3'),
    ('İzmir Usulü Nohutlu Bamya', 'BAMYA:60|DOMATES:30|KURU SOĞAN:10|NOHUT:20|TUZ:0.8|ZEYTİNYAĞI:4|ŞEKER:0.5'),
    ('Ege Zeytinyağlı Bakla ve Enginar', 'BAKLA:50|ENGİNAR:40|KURU SOĞAN:10|TAZE DEREOTU:1.5|TUZ:0.8|ZEYTİNYAĞI:4|ŞEKER:0.5'),
    ('İzmir Lokması', 'EKMEKLİK UN:50|KABARTMA TOZU:1.5|MISIR YAĞI:40|SU:50|ŞEKER:40'),
    ('Antalya Usulü Etli Nohut Yemeği', 'DOMATES:25|KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):80|NOHUT:30|TUZ:1'),
    ('Mersin Usulü Nohutlu Bulgur Aşı', 'BULGUR:50|DOMATES:20|KURU SOĞAN:10|NOHUT:25|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Hatay Usulü Tepsi Kebabı', 'DOMATES:25|KARABİBER:0.3|KURU SOĞAN:10|KUZU KIYMA:90|TUZ:1|YEŞİL BİBER:15'),
    ('Adana Usulü Analı Kızlı Çorba', 'BULGUR:20|DANA KIYMA:30|KURU NANE:0.5|TAVUK SUYU:80|TEREYAĞI:3|TUZ:0.8|YOĞURT (TAM):40'),
    ('Antalya Yeşil Erik Hoşafı', 'ERİK:50|SU:70|ŞEKER:15'),
    ('Mersin Usulü Portakallı Zeytin Salatası', 'KURU SOĞAN:5|PORTAKAL:30|SUMAK:0.5|YEŞİL ZEYTİN:30|ZEYTİNYAĞI:3'),
    ('Akdeniz Usulü Enginar Kalpli Salata', 'ENGİNAR KALBİ:40|LİMON SUYU:2|ROKA:20|TUZ:0.5|ZEYTİNYAĞI:3'),
    ('Antalya Usulü Şeftalili Tavuk Sote', 'KARABİBER:0.3|KURU SOĞAN:10|TAVUK GÖĞÜS:90|TUZ:0.8|ZEYTİNYAĞI:3|ŞEFTALİ:30'),
    ('Sivas Usulü Kes Kes', 'ERİK:20|KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):90|PATATES:40|TUZ:1'),
    ('Kırşehir Usulü Nohutlu Yahni', 'KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):80|NOHUT:30|TUZ:1'),
    ('Aksaray Usulü Bulgurlu Köfte (Fırında)', 'BULGUR:30|DANA KIYMA:70|KARABİBER:0.3|KURU SOĞAN:15|MAYDANOZ:2|TUZ:1'),
    ('Nevşehir Üzümlü Kabak Tatlısı', 'CEVİZ (İÇ):8|KABAK:80|ŞEKER:30'),
    ('Konya Usulü Mercimekli Ekmek Aşı', 'EKMEK (BEYAZ):30|KIRMIZI MERCİMEK:20|PUL BİBER:0.5|TAVUK SUYU:90|TEREYAĞI:4|TUZ:0.8'),
    ('Ankara Usulü Zerde', 'KUŞ ÜZÜMÜ:5|PİRİNÇ (HAM):20|SAFRAN:0.1|SU:120|ŞEKER:40'),
    ('Niğde Usulü Zeytinyağlı Nohut', 'DOMATES:20|KURU SOĞAN:15|NOHUT:50|TUZ:0.8|ZEYTİNYAĞI:4|ŞEKER:0.5'),
    ('Kapadokya Usulü Karışık Kış Turşusu', 'HAVUÇ:20|LAHANA:40|PATLICAN:20|SARIMSAK:1.5|SİRKE:6|TUZ:4'),
    ('Samsun Usulü Kaşarlı Sucuklu Pide', 'EKMEKLİK UN:70|KAŞAR PEYNİRİ:30|SUCUK:25|TAVUK YUMURTASI:20|TEREYAĞI:6|TUZ:1'),
    ('Ordu Usulü Fındıklı Pilav', 'FINDIK (İÇ):10|PİRİNÇ (HAM):60|TAVUK SUYU:90|TEREYAĞI:6|TUZ:1'),
    ('Rize Usulü Mantar Kavurması (Etli)', 'KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):70|MANTAR:50|TEREYAĞI:4|TUZ:1'),
    ('Giresun Usulü Fasulye Turşusu', 'SARIMSAK:2|SİRKE:6|TAZE FASULYE:70|TUZ:4'),
    ('Trabzon Usulü Karalahana Sarması (Etli)', 'DANA KIYMA:50|KARABİBER:0.3|KARALAHANA:80|KURU SOĞAN:10|PİRİNÇ (HAM):25|TUZ:1'),
    ('Bayburt Usulü Kuru Fasulye Çorbası', 'KURU FASULYE:40|KURU SOĞAN:10|TEREYAĞI:3|TUZ:0.8'),
    ('Karadeniz Usulü Hamsi Buğulama', 'HAMSİ:120|KURU SOĞAN:15|MAYDANOZ:2|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Karadeniz Usulü Elmalı Ceviz Tatlısı', 'CEVİZ (İÇ):15|ELMA:60|TEREYAĞI:4|ŞEKER:20'),
    ('Muş Usulü Kuzu Haşlama', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (BUT):120|TUZ:1.2'),
    ('Ağrı Usulü Lorlu Kavurma (Etsiz)', 'CEVİZ (İÇ):6|KURU SOĞAN:10|LOR PEYNİRİ:50|PUL BİBER:0.5|TEREYAĞI:4|TUZ:0.5'),
    ('Kars Usulü Kaşarlı Kete', 'EKMEKLİK UN:60|KAŞAR PEYNİRİ:40|TEREYAĞI:10|TUZ:0.8'),
    ('Bitlis Usulü Karışık Dolma (Etli)', 'DANA KIYMA:50|KABAK:50|KARABİBER:0.3|KURU SOĞAN:10|PİRİNÇ (HAM):25|TUZ:1|YEŞİL BİBER:40'),
    ('Iğdır Usulü Kayısılı Pilav', 'KURU KAYISI:20|PİRİNÇ (HAM):50|TAVUK SUYU:90|TEREYAĞI:6|TUZ:0.8'),
    ('Erzincan Usulü Tulumlu Makarna', 'MAKARNA:70|TEREYAĞI:10|TULUM PEYNİRİ:30|TUZ:1'),
    ('Van Usulü Pazılı Kavurma (Etli)', 'KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):70|PAZI:50|TUZ:1'),
    ('Doğu Anadolu Cevizli Kayısı Kurusu Tatlısı', 'BAL:10|CEVİZ (İÇ):15|KURU KAYISI:40'),
    ('Gaziantep Usulü Fıstıklı Kebap', 'ANTEP FISTIĞI:10|KARABİBER:0.3|KURU SOĞAN:10|KUZU KIYMA:90|TUZ:1'),
    ('Şanlıurfa Usulü Patlıcan Kebabı', 'DOMATES:20|KARABİBER:0.3|KURU SOĞAN:15|KUZU KIYMA:70|PATLICAN:70|TUZ:1'),
    ('Diyarbakır Usulü Cevizli Biber Salatası', 'CEVİZ (İÇ):10|NAR EKŞİSİ:2|SARIMSAK:1.5|TUZ:0.8|YEŞİL BİBER:40|ZEYTİNYAĞI:3'),
    ('Mardin Usulü Susamlı Marul Salatası', 'MARUL:30|NAR EKŞİSİ:2|SUSAM:3|TUZ:0.5|ZEYTİNYAĞI:3'),
    ('Siirt Usulü Perde Pilavı', 'ANTEP FISTIĞI:4|KURU SOĞAN:10|PİRİNÇ (HAM):50|TAVUK GÖĞÜS:50|TAVUK SUYU:80|TEREYAĞI:6|TUZ:1|YUFKA:20'),
    ('Batman Usulü Etli Yaprak Sarma', 'DANA KIYMA:50|KARABİBER:0.3|KURU SOĞAN:10|LİMON SUYU:2|PİRİNÇ (HAM):20|SALAMURA YAPRAK:40|TUZ:0.8'),
    ('Şırnak Usulü Kuzu Kavurma', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):90|TUZ:1'),
    ('Kilis Usulü Zeytinyağlı Nohutlu Salata', 'DOMATES:20|NOHUT:50|SUMAK:0.5|TUZ:0.8|YEŞİL BİBER:15|ZEYTİNYAĞI:3'),
    ('Balıkesir Usulü Keşkek', 'BULGUR:40|KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):80|TEREYAĞI:6|TUZ:1.2'),
    ('Çanakkale Usulü Midye Pilavı', 'KARABİBER:0.3|KURU SOĞAN:10|MİDYE:80|PİRİNÇ (HAM):40|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Kırklareli Usulü Zeytinyağlı Barbunya', 'BARBUNYA:60|DOMATES:25|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:4|ŞEKER:0.5'),
    ('Edirne Usulü Tavuklu Erişte', 'KAŞAR PEYNİRİ:20|MAKARNA:60|TAVUK GÖĞÜS:40|TEREYAĞI:6|TUZ:0.8'),
    ('Tekirdağ Usulü Zeytinyağlı Karnabahar', 'KARNABAHAR:70|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:4|ŞEKER:0.5'),
    ('Kocaeli Usulü Pilav Üstü Tavuk', 'KARABİBER:0.3|PİRİNÇ (HAM):50|TAVUK BUT:60|TAVUK SUYU:80|TEREYAĞI:6|TUZ:0.8'),
    ('Marmara Usulü Cevizli Ayva Tatlısı', 'AYVA:70|CEVİZ (İÇ):10|SU:50|ŞEKER:25'),
    ('Marmara Usulü Zeytinli Domates Salatası', 'DOMATES:50|KURU SOĞAN:5|TUZ:0.5|YEŞİL ZEYTİN:15|ZEYTİNYAĞI:3'),
    ('Söke Usulü Pirinç Pilavı', 'PİRİNÇ (HAM):60|TAVUK SUYU:90|TEREYAĞI:6|TUZ:0.8'),
    ('Bodrum Usulü Karidesli Salata', 'KARİDES:50|LİMON SUYU:2|MARUL:20|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Milas Usulü Hellim Izgara', 'HELLİM PEYNİRİ:50|LİMON SUYU:1.5|ZEYTİNYAĞI:3'),
    ('Kuşadası Usulü Izgara Çipura', 'KEKİK:0.3|LİMON SUYU:2|TUZ:0.8|ZEYTİNYAĞI:3|ÇİPURA:150'),
    ('Alaçatı Usulü Pazı Kavurması (Zeytinyağlı)', 'KURU SOĞAN:10|PAZI:70|PİRİNÇ (HAM):6|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Çeşme Usulü Karpuzlu Peynir Tabağı', 'KARPUZ:60|OTLU PEYNİR:20|TAZE NANE:1'),
    ('Bergama Usulü Peynirli Domates Dolması (Etsiz)', 'DOMATES:70|LOR PEYNİRİ:30|MAYDANOZ:2|TUZ:0.5|ZEYTİNYAĞI:2'),
    ('İzmir Usulü Portakallı Zeytinyağlı Pancar', 'PANCAR:60|PORTAKAL:20|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Silifke Usulü Yoğurtlu Köfte', 'DANA KIYMA:80|DOMATES:20|KARABİBER:0.3|TEREYAĞI:4|TUZ:1|YOĞURT (TAM):40'),
    ('Anamur Usulü Portakallı Muz Tatlısı', 'BAL:6|MUZ:50|PORTAKAL:30'),
    ('Kaş Usulü Izgara Karides', 'KARİDES:100|LİMON SUYU:2|SARIMSAK:1.5|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Alanya Usulü Karides Pilavı', 'KARİDES:50|KURU SOĞAN:10|PİRİNÇ (HAM):50|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Antalya Usulü Zeytinyağlı Enginar Kalpli Pilav', 'ENGİNAR KALBİ:30|KURU SOĞAN:10|PİRİNÇ (HAM):50|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Mersin Usulü Tirit', 'EKMEK (BEYAZ):30|KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):90|TUZ:1'),
    ('Hatay Usulü Kaytaz Böreği', 'DANA KIYMA:30|KURU SOĞAN:6|MISIR YAĞI:30|TUZ:0.6|YUFKA:40'),
    ('Adana Usulü Zeytinyağlı Nohutlu Ispanak', 'ISPANAK:60|KURU SOĞAN:10|NOHUT:20|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Yozgat Usulü Çullama', 'TAVUK GÖĞÜS:80|TEREYAĞI:6|TUZ:0.8|YOĞURT (TAM):40|YUFKA:30'),
    ('Kırıkkale Usulü Yoğurtlu Erişte', 'MAKARNA:60|PUL BİBER:0.5|SARIMSAK:1.5|TEREYAĞI:5|TUZ:0.8|YOĞURT (TAM):40'),
    ('Çankırı Usulü Kuru Fasulye Yahnisi', 'DANA KIYMA:40|DOMATES:20|KARABİBER:0.3|KURU FASULYE:50|KURU SOĞAN:15|TUZ:1'),
    ('Karaman Usulü Etli Bamya', 'BAMYA:50|DOMATES:25|KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):70|TUZ:1'),
    ('Nevşehir Usulü Üzümlü Bulgur Pilavı', 'BULGUR:50|KURU SOĞAN:10|KURU ÜZÜM:10|TAVUK SUYU:70|TEREYAĞI:5|TUZ:0.8'),
    ('Kayseri Usulü Cevizli Sucuk (Pekmezli)', 'CEVİZ (İÇ):30|EKMEKLİK UN:6|ÜzÜM PEKMEZİ:50'),
    ('Sivas Usulü Kürtün Aşı', 'MAKARNA:20|NOHUT:30|PUL BİBER:0.5|TEREYAĞI:4|TUZ:0.8'),
    ('Konya Usulü Ballı Kadayıf', 'BAL:20|EKMEK KADAYIFI:50|KAYMAK:30'),
    ('Bolu Usulü Kestaneli Tavuk', 'KARABİBER:0.3|KESTANE:30|KURU SOĞAN:10|TAVUK BUT:90|TEREYAĞI:4|TUZ:0.8'),
    ('Zonguldak Usulü Pancar Turşusu', 'PANCAR:60|SARIMSAK:1.5|SİRKE:6|TUZ:4'),
    ('Sinop Usulü Balık Buğulama', 'KURU SOĞAN:10|MAYDANOZ:2|TUZ:0.8|ZEYTİNYAĞI:3|İSTAVRİT:100'),
    ('Amasya Usulü Elma Tatlısı', 'ELMA:80|TARÇIN:0.3|ŞEKER:25'),
    ('Tokat Usulü Kebabı (Patatesli, Fırında)', 'DOMATES:25|KARABİBER:0.3|KURU SOĞAN:10|KUZU KIYMA:70|PATATES:50|TUZ:1'),
    ('Artvin Usulü Fasulye Pilaki', 'BARBUNYA:50|DOMATES:20|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Ordu Usulü Fındıklı Tatlı', 'FINDIK (İÇ):40|SÜT (TAM YAĞ):30|ŞEKER:20'),
    ('Karadeniz Usulü Taze Fasulye Yemeği (Etli)', 'DANA KIYMA:40|DOMATES:20|KARABİBER:0.3|KURU SOĞAN:10|TAZE FASULYE:60|TUZ:0.8'),
    ('Erzurum Usulü Su Böreği', 'KAŞAR PEYNİRİ:30|TAVUK YUMURTASI:15|TEREYAĞI:8|TUZ:0.8|YUFKA:50'),
    ('Erzincan Usulü Çökelekli Yumurta', 'LOR PEYNİRİ:30|TAVUK YUMURTASI:40|TEREYAĞI:4|TUZ:0.5'),
    ('Van Usulü Otlu Peynirli Salata', 'DOMATES:30|OTLU PEYNİR:30|ROKA:15|ZEYTİNYAĞI:2'),
    ('Muş Usulü Zeytinyağlı Semizotu', 'KURU SOĞAN:10|PİRİNÇ (HAM):6|SEMİZOTU:50|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Ağrı Usulü Kaz Eti Pilavı', 'KAZ ETİ (BUT, DERİSİZ, TUZ İLAVELİ):50|PİRİNÇ (HAM):40|TEREYAĞI:5|TUZ:0.6'),
    ('Kars Usulü Kaşarlı Pilav', 'KAŞAR PEYNİRİ:20|PİRİNÇ (HAM):50|TAVUK SUYU:70|TEREYAĞI:5|TUZ:0.8'),
    ('Bitlis Usulü Nohutlu Etli Çorba', 'DANA KIYMA:30|KARABİBER:0.3|KURU SOĞAN:10|NOHUT:25|TAVUK SUYU:80|TUZ:0.8'),
    ('Iğdır Usulü Kayısılı Komposto', 'KAYISI:50|SU:70|ŞEKER:15'),
    ('Gaziantep Usulü Beyran Çorbası', 'KARABİBER:0.3|KUZU ETİ (KOL):50|PİRİNÇ (HAM):10|SARIMSAK:2|TUZ:1'),
    ('Şanlıurfa Usulü Nohutlu Kuzu Güveç', 'DOMATES:20|KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):80|NOHUT:25|TUZ:1'),
    ('Diyarbakır Usulü Kaburga Pilavı', 'KARABİBER:0.3|KURU SOĞAN:10|PİRİNÇ (HAM):40|SIĞIR KABURGA:70|TUZ:1'),
    ('Mardin Usulü Zeytinyağlı Nohutlu Bulgur', 'BULGUR:40|KURU SOĞAN:10|NOHUT:25|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Siirt Usulü Kaburga Kavurma', 'KARABİBER:0.3|KURU SOĞAN:10|SIĞIR KABURGA:90|TUZ:1'),
    ('Batman Usulü Nohutlu Pilav', 'NOHUT:20|PİRİNÇ (HAM):50|TAVUK SUYU:70|TEREYAĞI:5|TUZ:0.8'),
    ('Şırnak Usulü Etli Nohutlu Bulgur Pilavı', 'BULGUR:30|KARABİBER:0.3|KURU SOĞAN:10|KUZU KIYMA:50|NOHUT:20|TUZ:0.8'),
    ('Kilis Usulü Nar Ekşili Mercimek Çorbası', 'KIRMIZI MERCİMEK:30|KURU SOĞAN:10|NAR EKŞİSİ:2|TAVUK SUYU:80|TUZ:0.8'),
    ('Yalova Usulü Zeytinyağlı Kestane', 'KESTANE:60|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Bilecik Usulü Etli Nohutlu Bulgur', 'BULGUR:20|DANA KIYMA:50|KARABİBER:0.3|KURU SOĞAN:10|NOHUT:25|TUZ:0.8'),
    ('Sakarya Usulü Mısırlı Tavuk Güveç', 'DOMATES:20|KARABİBER:0.3|KURU SOĞAN:10|MISIR:30|TAVUK BUT:80|TUZ:0.8'),
    ('Çorlu Usulü Kaşarlı Tavuklu Makarna', 'KAŞAR PEYNİRİ:20|MAKARNA:60|TAVUK GÖĞÜS:40|TEREYAĞI:5|TUZ:0.8'),
    ('Bursa Usulü Cevizli Erik Tatlısı', 'CEVİZ (İÇ):10|ERİK:60|ŞEKER:20'),
    ('İstanbul Usulü Zeytinyağlı Balkabağı', 'KABAK:70|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:1'),
    ('Marmara Usulü Nohutlu Tavuk Çorbası', 'KARABİBER:0.3|NOHUT:20|TAVUK GÖĞÜS:30|TAVUK SUYU:90|TUZ:0.8'),
    ('Marmara Usulü Armutlu Ceviz Tatlısı', 'ARMUT (KIŞLIK, DEVECİ ÇEŞİDİ):60|BAL:6|CEVİZ (İÇ):10'),
    ('Manisa Usulü Mesir Macunlu Tatlı - basitleştirilmiş', 'BAL:30|CEVİZ (İÇ):15|TARÇIN:0.3'),
    ('Denizli Usulü Keşkek (Tavuklu)', 'BULGUR:40|KARABİBER:0.3|KURU SOĞAN:10|TAVUK BUT:80|TEREYAĞI:5|TUZ:1'),
    ('Uşak Usulü Zeytinyağlı Nohutlu Havuç', 'HAVUÇ:50|KURU SOĞAN:10|NOHUT:20|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Ayvalık Usulü Zeytinli Ekmek Salatası', 'DOMATES:30|EKMEK (BEYAZ):30|TUZ:0.5|YEŞİL ZEYTİN:15|ZEYTİNYAĞI:3'),
    ('Urla Usulü Karidesli Zeytinyağlı Enginar', 'ENGİNAR:40|KARİDES:30|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Tire Usulü Köftesi (Fırında)', 'DANA KIYMA:90|DOMATES:30|KARABİBER:0.3|KURU SOĞAN:10|PATATES:40|TUZ:1'),
    ('Ödemiş Usulü Patatesli Tavuk Sote', 'KARABİBER:0.3|KURU SOĞAN:10|PATATES:40|TAVUK BUT:80|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Kütahya Usulü Kirazlı Yoğurt', 'KİRAZ:40|YOĞURT (TAM):50|ŞEKER:10'),
    ('Isparta Usulü Gül Reçelli Yoğurt Tatlısı', 'BAL:15|CEVİZ (İÇ):6|YOĞURT (TAM):50'),
    ('Burdur Usulü Etli Nohutlu Pilav', 'DANA KIYMA:50|KARABİBER:0.3|KURU SOĞAN:10|NOHUT:15|PİRİNÇ (HAM):40|TUZ:0.8'),
    ('Osmaniye Usulü Zeytinyağlı Yer Fıstıklı Salata', 'FINDIK (İÇ):10|LİMON SUYU:1.5|MARUL:25|TUZ:0.5|ZEYTİNYAĞI:2.5'),
    ('Tarsus Usulü Şalgamlı Köfte - basitleştirilmiş (Şalgam Hariç)', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU KIYMA:90|KİMYON:0.5|TUZ:1'),
    ('Manavgat Usulü Izgara Levrek', 'LEVREK:150|LİMON SUYU:2|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Side Usulü Zeytinyağlı Enginar Turşusu', 'ENGİNAR:50|SARIMSAK:1.5|SİRKE:5|TUZ:3.5'),
    ('Kumluca Usulü Zeytinyağlı Domates Yemeği', 'DOMATES:70|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Antalya Usulü Portakallı Tavuk Sote', 'KARABİBER:0.3|KURU SOĞAN:10|PORTAKAL:30|TAVUK GÖĞÜS:90|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Eskişehir Usulü Çibörek (Kızartma)', 'DANA KIYMA:50|EKMEKLİK UN:50|KARABİBER:0.3|KURU SOĞAN:10|MISIR YAĞI:30|TUZ:0.8'),
    ('Kayseri Usulü Etli Ekmek (İnce)', 'DOMATES:20|EKMEKLİK UN:70|KURU SOĞAN:10|KUZU KIYMA:60|PUL BİBER:0.5|TUZ:0.8'),
    ('Ankara Usulü Zeytinyağlı Havuç ve Nohut', 'HAVUÇ:50|KURU SOĞAN:10|NOHUT:25|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Konya Usulü Etli Nohutlu Yahni', 'KARABİBER:0.3|KURU SOĞAN:15|KUZU ETİ (KOL):80|NOHUT:30|TUZ:1'),
    ('Nevşehir Usulü Elmalı Kabaklı Tatlı', 'CEVİZ (İÇ):6|ELMA:40|KABAK:40|ŞEKER:25'),
    ('Sivas Usulü Mantısı (Küçük Boy)', 'EKMEKLİK UN:70|KURU SOĞAN:15|KUZU KIYMA:50|SARIMSAK:2|TEREYAĞI:8|TUZ:1|YOĞURT (TAM):60'),
    ('Yozgat Usulü Zeytinyağlı Kuru Fasulye', 'DOMATES:20|KURU FASULYE:50|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Kırşehir Usulü Nohutlu Ispanak Çorbası', 'ISPANAK:30|NOHUT:20|TAVUK SUYU:80|TEREYAĞI:3|TUZ:0.8'),
    ('Gümüşhane Usulü Kuru Fasulye (Etli)', 'DANA KIYMA:40|DOMATES:20|KARABİBER:0.3|KURU FASULYE:50|KURU SOĞAN:15|TUZ:0.8'),
    ('Kastamonu Usulü Tarhana Çorbası', 'TARHANA:20|TAVUK SUYU:120|TEREYAĞI:3|TUZ:0.6'),
    ('Bartın Usulü Pancarlı Pilav', 'PANCAR:30|PİRİNÇ (HAM):50|TAVUK SUYU:70|TEREYAĞI:5|TUZ:0.8'),
    ('Karabük Usulü Etli Lahana Sarması', 'DANA KIYMA:50|KARABİBER:0.3|KURU SOĞAN:10|LAHANA:70|PİRİNÇ (HAM):25|TUZ:0.8'),
    ('Samsun Usulü Zeytinyağlı Karalahana', 'KARALAHANA:60|KURU SOĞAN:10|PİRİNÇ (HAM):6|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Trabzon Usulü Vişne Ekşili Kuzu Yahnisi', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):90|TUZ:0.8|VİŞNE:20'),
    ('Giresun Usulü Mısır Ekmekli Peynirli Tabak', 'KAŞAR PEYNİRİ:30|MISIR UNU:20|TEREYAĞI:4'),
    ('Ordu Usulü Fındıklı Yoğurtlu Havuç Salatası', 'FINDIK (İÇ):8|HAVUÇ:40|SARIMSAK:1|YOĞURT (TAM):30'),
    ('Bingöl Usulü Kuzu Kavurma', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):90|TUZ:1'),
    ('Tunceli Usulü Mırığı (Yoğurtlu Bulgur Aşı)', 'BULGUR:50|TEREYAĞI:5|TUZ:0.8|YOĞURT (TAM):40'),
    ('Hakkari Usulü Kuzu Etli Nohut Yemeği', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):80|NOHUT:30|TUZ:1'),
    ('Ardahan Usulü Kaşarlı Kete', 'EKMEKLİK UN:60|KAŞAR PEYNİRİ:40|TEREYAĞI:10|TUZ:0.8'),
    ('Van Usulü Balı ile Kaymaklı Tatlı', 'BAL:30|KAYMAK:30'),
    ('Erzurum Usulü Zeytinyağlı Kuru Fasulye', 'DOMATES:20|KURU FASULYE:50|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Malatya Usulü Kayısılı Tavuk Sote', 'KARABİBER:0.3|KAYISI:30|KURU SOĞAN:10|TAVUK GÖĞÜS:90|TUZ:0.8'),
    ('Elazığ Usulü Nohutlu Bulgur Pilavı', 'BULGUR:50|NOHUT:25|TAVUK SUYU:70|TEREYAĞI:5|TUZ:0.8'),
    ('Adıyaman Usulü Etli Nohutlu Bulgur Köftesi', 'BULGUR:30|DANA KIYMA:60|KARABİBER:0.3|KURU SOĞAN:10|NOHUT:15|TUZ:0.8'),
    ('Gaziantep Usulü Zeytinyağlı Nohutlu Pırasa', 'KURU SOĞAN:10|NOHUT:20|PIRASA:50|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Şanlıurfa Usulü İçli Köfte (Büyük Boy)', 'BULGUR:50|CEVİZ (İÇ):10|DANA KIYMA:80|KURU SOĞAN:20|PUL BİBER:0.5|TUZ:1'),
    ('Diyarbakır Usulü Etli Nohutlu Şiveydiz - basitleştirilmiş', 'KARABİBER:0.3|KUZU ETİ (KOL):70|NOHUT:15|TAZE SOĞAN:30|TUZ:0.8'),
    ('Mardin Usulü Kaburgalı Nohut Çorbası', 'KARABİBER:0.3|KURU SOĞAN:10|NOHUT:25|SIĞIR KABURGA:50|TUZ:0.8'),
    ('Siirt Usulü Zeytinyağlı Nohutlu Patlıcan', 'DOMATES:25|KURU SOĞAN:10|NOHUT:20|PATLICAN:50|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Batman Usulü Kaşarlı Kuzu Güveç', 'KARABİBER:0.3|KAŞAR PEYNİRİ:15|KURU SOĞAN:10|KUZU ETİ (KOL):90|TUZ:0.8'),
    ('Kilis Usulü Zeytinyağlı Biberli Bulgur', 'BULGUR:40|DOMATES:25|KURU SOĞAN:10|TUZ:0.8|YEŞİL BİBER:30|ZEYTİNYAĞI:3'),
    ('İstanbul Usulü Midye Salatası', 'LİMON SUYU:2|MARUL:20|MİDYE:70|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Bursa Usulü Zeytinyağlı Kereviz', 'HAVUÇ:20|KEREVİZ:60|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Kırklareli Usulü Kavurmalı Yumurta', 'DANA KIYMA:30|TAVUK YUMURTASI:40|TEREYAĞI:4|TUZ:0.6'),
    ('Tekirdağ Usulü Fırın Sütlaç', 'MISIR NİŞASTASI:4|PİRİNÇ (HAM):10|SÜT (TAM YAĞ):120|ŞEKER:25'),
    ('Çanakkale Usulü Zeytinyağlı Taze Fasulye', 'DOMATES:20|KURU SOĞAN:10|TAZE FASULYE:60|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Balıkesir Usulü Zeytinyağlı Enginarlı Bezelye', 'BEZELYE:40|ENGİNAR:30|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Marmara Usulü İncirli Kaşar Tabağı', 'CEVİZ (İÇ):6|KAŞAR PEYNİRİ:25|KURU İNCİR:30'),
    ('İstanbul Usulü Limonlu Tavuk Sote', 'KARABİBER:0.3|LİMON SUYU:4|SARIMSAK:1.5|TAVUK GÖĞÜS:90|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('İzmir Usulü Zeytinyağlı Nohutlu Enginar', 'ENGİNAR:40|KURU SOĞAN:10|NOHUT:20|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Muğla Usulü Bal Kaymaklı Kahvaltı Tabağı', 'BAL:30|KAYMAK:30'),
    ('Datça Usulü Bademli Zeytinyağlı Salata', 'BADEM:8|LİMON SUYU:1.5|MARUL:25|ZEYTİNYAĞI:2.5'),
    ('Fethiye Usulü Izgara Karides', 'KARİDES:100|LİMON SUYU:2|SARIMSAK:1.5|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Salihli Usulü Üzümlü Pilav', 'KURU ÜZÜM:10|PİRİNÇ (HAM):50|TAVUK SUYU:70|TEREYAĞI:5|TUZ:0.8'),
    ('Nazilli Usulü Etli Nohutlu Bamya', 'BAMYA:40|KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):70|NOHUT:15|TUZ:0.8'),
    ('Dikili Usulü Zeytinyağlı Semizotu', 'KURU SOĞAN:10|PİRİNÇ (HAM):6|SEMİZOTU:50|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('İzmir Usulü Üzümlü Komposto', 'SU:70|ÜZÜM:50|ŞEKER:10'),
    ('Antalya Usulü Zeytinyağlı Kereviz', 'HAVUÇ:20|KEREVİZ:60|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Mersin Usulü Etli Bamya', 'BAMYA:50|DOMATES:25|KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):70|TUZ:0.8'),
    ('Adana Usulü Nohutlu Kavurma', 'DANA KIYMA:70|KARABİBER:0.3|KURU SOĞAN:10|NOHUT:25|TUZ:0.8'),
    ('Hatay Usulü Zeytinyağlı Enginar', 'ENGİNAR:50|KURU SOĞAN:10|LİMON SUYU:1.5|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Silifke Usulü Zeytinyağlı Taze Bakla', 'BAKLA:50|KURU SOĞAN:10|TAZE DEREOTU:1.5|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Antalya Usulü Portakallı Muhallebi', 'MISIR NİŞASTASI:6|PORTAKAL:20|SÜT (TAM YAĞ):100|ŞEKER:20'),
    ('Kahramanmaraş Usulü Etli Nohutlu Bulgur', 'BULGUR:30|KARABİBER:0.3|KURU SOĞAN:10|KUZU KIYMA:60|NOHUT:20|TUZ:0.8'),
    ('Osmaniye Usulü Zeytinyağlı Taze Fasulye', 'DOMATES:25|KURU SOĞAN:10|TAZE FASULYE:60|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Ankara Usulü Etli Nohutlu Bulgur Pilavı', 'BULGUR:30|DANA KIYMA:50|KARABİBER:0.3|KURU SOĞAN:10|NOHUT:20|TUZ:0.8'),
    ('Konya Usulü Zeytinyağlı Pırasa', 'HAVUÇ:15|KURU SOĞAN:10|PIRASA:60|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Kayseri Usulü Kavurmalı Yumurta', 'DANA KIYMA:30|TAVUK YUMURTASI:40|TEREYAĞI:3|TUZ:0.6'),
    ('Sivas Usulü Zeytinyağlı Nohutlu Kabak', 'KABAK:50|KURU SOĞAN:10|NOHUT:20|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Niğde Usulü Elmalı Cevizli Tatlı', 'CEVİZ (İÇ):10|ELMA:60|ŞEKER:20'),
    ('Aksaray Usulü Etli Kabak Yemeği', 'DANA KIYMA:50|DOMATES:20|KABAK:50|KARABİBER:0.3|KURU SOĞAN:10|TUZ:0.8'),
    ('Kırşehir Usulü Zeytinyağlı Enginar', 'ENGİNAR:50|HAVUÇ:15|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Çorum Usulü Nohutlu Tavuk Sote', 'KARABİBER:0.3|KURU SOĞAN:10|NOHUT:20|TAVUK BUT:80|TUZ:0.8'),
    ('Trabzon Usulü Zeytinyağlı Kuru Fasulye', 'DOMATES:20|KURU FASULYE:50|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Rize Usulü Mısır Ekmekli Kaymak Tabağı', 'BAL:10|KAYMAK:25|MISIR UNU:15'),
    ('Samsun Usulü Etli Lahana Yemeği', 'DANA KIYMA:40|KARABİBER:0.3|KURU SOĞAN:10|LAHANA:60|TUZ:0.8'),
    ('Giresun Usulü Fındıklı Muhallebi', 'FINDIK (İÇ):15|MISIR NİŞASTASI:5|SÜT (TAM YAĞ):100|ŞEKER:20'),
    ('Ordu Usulü Zeytinyağlı Taze Fasulye', 'DOMATES:20|KURU SOĞAN:10|TAZE FASULYE:60|TUZ:0.8|ZEYTİNYAĞI:3|ŞEKER:0.5'),
    ('Artvin Usulü Kaşarlı Mısır Ekmeği', 'EKMEKLİK UN:15|KAŞAR PEYNİRİ:20|MISIR UNU:50|TAVUK YUMURTASI:15|TUZ:0.8'),
    ('Bayburt Usulü Etli Kavurma', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):90|TUZ:0.8'),
    ('Tokat Usulü Zeytinyağlı Nohutlu Pırasa', 'KURU SOĞAN:10|NOHUT:20|PIRASA:50|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Erzurum Usulü Etli Nohutlu Kavurma', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):80|NOHUT:25|TUZ:0.8'),
    ('Van Usulü Balı ile Ceviz Tabağı', 'BAL:30|CEVİZ (İÇ):20'),
    ('Kars Usulü Etli Kavurma', 'KARABİBER:0.3|KOYUN ETİ (KOL):90|KURU SOĞAN:10|TUZ:0.8'),
    ('Ağrı Usulü Zeytinyağlı Nohut', 'DOMATES:20|KURU SOĞAN:10|NOHUT:50|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Muş Usulü Etli Pazı Yemeği', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):70|PAZI:50|TUZ:0.8'),
    ('Malatya Usulü Kayısılı Komposto', 'KAYISI:50|SU:70|ŞEKER:15'),
    ('Elazığ Usulü Etli Nohutlu Bulgur', 'BULGUR:25|DANA KIYMA:50|KARABİBER:0.3|KURU SOĞAN:10|NOHUT:20|TUZ:0.8'),
    ('Bitlis Usulü Zeytinyağlı Semizotu', 'KURU SOĞAN:10|PİRİNÇ (HAM):6|SEMİZOTU:50|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Gaziantep Usulü Etli Nohutlu Kabak', 'DOMATES:20|KABAK:40|KARABİBER:0.3|KURU SOĞAN:10|KUZU KIYMA:50|TUZ:0.8'),
    ('Şanlıurfa Usulü Zeytinyağlı Mercimekli Bulgur', 'BULGUR:40|KIRMIZI MERCİMEK:20|KURU SOĞAN:10|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Diyarbakır Usulü Etli Kavurma', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):90|TUZ:0.8'),
    ('Mardin Usulü Zeytinyağlı Biberli Patlıcan', 'DOMATES:25|KURU SOĞAN:10|PATLICAN:50|TUZ:0.8|YEŞİL BİBER:20|ZEYTİNYAĞI:3'),
    ('Siirt Usulü Fıstıklı Pilav', 'ANTEP FISTIĞI:10|PİRİNÇ (HAM):50|TAVUK SUYU:70|TEREYAĞI:5|TUZ:0.8'),
    ('Batman Usulü Etli Nohutlu Bulgur', 'BULGUR:25|KARABİBER:0.3|KURU SOĞAN:10|KUZU KIYMA:50|NOHUT:20|TUZ:0.8'),
    ('Şırnak Usulü Zeytinyağlı Nohutlu Ispanak', 'ISPANAK:50|KURU SOĞAN:10|NOHUT:20|TUZ:0.8|ZEYTİNYAĞI:3'),
    ('Kilis Usulü Etli Kavurma', 'KARABİBER:0.3|KURU SOĞAN:10|KUZU ETİ (KOL):90|PUL BİBER:0.5|TUZ:0.8')
)
select b.ad, b.beklenen_imza,
       (select string_agg(m.ad || ':' || rm.miktar_gram, '|' order by m.ad || ':' || rm.miktar_gram)
          from recete_malzemeleri rm join malzemeler m on m.id = rm.malzeme_id
         where rm.recete_id = r.id) as gercek_imza
from beklenen b
join receteler r on r.ad = b.ad and r.isletme_id is null
where b.beklenen_imza <> (
    select string_agg(m.ad || ':' || rm.miktar_gram, '|' order by m.ad || ':' || rm.miktar_gram)
    from recete_malzemeleri rm join malzemeler m on m.id = rm.malzeme_id
    where rm.recete_id = r.id
)
order by b.ad;